### ISSUE TITLE
Validação de campos obrigatórios na lista de produtos, durante a criação de orçamentos

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#1]
Quando eu tento inserir um item na lista de produtos, ao criar um Orçamento, o app realça todos os campos obrigatórios não preenchidos fora da lista e não indica qual o campo na lista de produtos que não está preenchido.

![image](https://cloud.githubusercontent.com/assets/7696307/17610444/52424c2c-6014-11e6-8c82-1cdcd824a25d.png)

**Comment by raphaelMCarvalho** [comment]
Resolvido, cabe apontar que:

1. Removemos a função padrão do Enter, que costuma submeter o formulário.
2. No layout recebido não há a indicação específica em texto de quais campos precisam de preenchimento (ex.: "Obrigatório o preenchimento do campo Material"). No entanto, conforme a captura de tela da issue, os campos que precisam de preenchimento ficam com background vermelho.

**Comment by wespatrocinio** [comment]
@raphaelMCarvalho dois pontos:
1. Se vocês removeram o Enter para incluir o item na lista, eu abrirei uma outra issue para que isso seja corrigido. É um requisito contido na especificação.
2. Sobre o realce dos campos, a queixa da issue é que os alertas são exibidos após uma ação normal de preenchimento do cadastro. Se eu tivesse clicado em "Criar orçamento", eu esperaria ver o realce dessa maneira que está na tela capturada. Mas não esperaria ver isso após incluir um item na lista.

**Comment by wespatrocinio** [comment]
Issue sobre o ENTER foi criada: https://github.com/PraConstruir/web_app/issues/26
