### ISSUE TITLE
Falha na exibição das informações do Orçamento na página detalhada

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#10]
Ao clicar em cima de um orçamento, na página de Meus Orçamentos, para ver a página detalhada do orçamento, é aberta uma página sem o conteúdo do Orçamento.

![image](https://cloud.githubusercontent.com/assets/7696307/17611147/0e20e786-601b-11e6-8713-6fcb2f9808bb.png)

**Comment by raphaelMCarvalho** [comment]
A página detalhada refere-se à página em que ocorre a otimização de orçamento, que informei a vocês que não estava finalizada nessa entrega parcial.

**Comment by wespatrocinio** [comment]
@raphaelMCarvalho Ok. A issue permancerá aberta então até que seja liberada a página de detalhe. Apenas um dado que faltou na issue: essa tela de detalhe seria referente a um orçamento "Salvo", ou seja, que ainda não havia sido enviado aos lojistas e, portante, não seria aplicado o Otimizador.

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio não há uma tela para cada status, há apenas uma tela de detalhes e as ações possíveis na tela são determinadas pelo status. Como foi liberada uma versão inicial do otimizador, acredito que essa issue possa ser fechada.
