### ISSUE TITLE
Não é possível escolher manualmente o material no Explorer

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#100]
![image](https://cloud.githubusercontent.com/assets/20990100/18495979/4fbb1aee-79f8-11e6-8ec6-59e6a2184aea.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo informar versão do navegador

**Comment by lucasretondo** [comment]
@raphaelMCarvalho segue...

![image](https://cloud.githubusercontent.com/assets/20990100/18529557/f08d8640-7aa3-11e6-98d2-a495401dc7ec.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo até o momento não conseguimos reproduzir o problema. Funcionou normalmente nos nossos testes; no entanto, embora a versão do IE na captura de tela abaixo seja a 11, o SO é o Windows 10 (vi que você usa o 7). Você poderia tentar novamente e nos dizer se aconteceu novamente, e se ocorreu, nos dar mais detalhes?

![avaliando lojista](https://cloud.githubusercontent.com/assets/20994342/19010055/f4b86492-8750-11e6-9b71-37fe3699654c.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo você poderia testar novamente e informar se obteve a mesma anomalia?

**Comment by lucasretondo** [comment]
Infelizmente não, quando eu clico o valor desejado ele seleciona e em seguida volta para a seleção anterior. Em alguns casos muda a seleção, veja este vídeo:
https://drive.google.com/file/d/0B_JJI1HknOluMndoTlhleG1rdzQ/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo acho que houve um mal entendito, acho que nessa issue não cabe a label Correção não efetivada, pois não realizamos nenhuma correção, o que houve na verdade é que não conseguimos reproduzir o problema e queríamos saber se ele ainda está afetando sua navegação

**Comment by lucasretondo** [comment]
@raphaelMCarvalho infelizmente ainda não funcionou...
https://drive.google.com/file/d/0B_JJI1HknOluanBzNVp6VlJ5V3M/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo você pode testar novamente? Este é outro ponto que não conseguimos reproduzir e acreditamos que possa ter sido efeito do problema de cache que solucionamos hoje.
