### ISSUE TITLE
O botão exportar não esta funcionando

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#101]
![image](https://cloud.githubusercontent.com/assets/20990100/18495998/73e123dc-79f8-11e6-8a85-a342aa4b6e41.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho o botão exportar esta funcionado, porém a planilha em excel esta fora do formato e layout que enviamos. Este requisito para nós não é uma prioridade, portanto não acho interessante gastarmos mais tempo corrigindo este bug por enquanto.
https://drive.google.com/file/d/0B_JJI1HknOlud1VEQ3RKaWMwWFU/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo a correção foi efetivada
