### ISSUE TITLE
Tamanho texto material no Explorer

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#102]
A caixa de texto do material não esta ocupando o espaço da coluna...

![image](https://cloud.githubusercontent.com/assets/20990100/18496060/05b9b788-79f9-11e6-980d-36d3550059b3.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo informar versão do navegador

**Comment by lucasretondo** [comment]
@raphaelMCarvalho segue....

![image](https://cloud.githubusercontent.com/assets/20990100/18529544/e4e78dae-7aa3-11e6-93a9-e80c69336f96.png)
