### ISSUE TITLE
Avaliação lojista não funciona no Explorer

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#103]
![image](https://cloud.githubusercontent.com/assets/20990100/18496089/5603edf8-79f9-11e6-8c0a-5b2d896c9937.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo informar versão do navegador

**Comment by lucasretondo** [comment]
@raphaelMCarvalho segue...

![image](https://cloud.githubusercontent.com/assets/20990100/18529530/d992d260-7aa3-11e6-8c99-582e7a89c1a2.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo até o momento não conseguimos reproduzir o problema. Funcionou normalmente nos nossos testes; no entanto, embora a versão do IE na captura de tela abaixo seja a 11, o SO é o Windows 10 (vi que você usa o 7). Você poderia tentar novamente e nos dizer se aconteceu novamente, e se ocorreu, nos dar mais detalhes?

![avaliando lojista](https://cloud.githubusercontent.com/assets/20994342/19010103/94a161e8-8751-11e6-886e-62445c9d84c8.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho fiz o teste novamente e primeiro apareceu uma mensagem de erro e depois que eu cliquei novamente funcionou. Como não estamos priorizando o Explorer vou marcar como não será corrigido.
