### ISSUE TITLE
Explorer e outros - Homogenizar os layouts

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#104]
Esta borda preta é muito feia...

![image](https://cloud.githubusercontent.com/assets/20990100/18496148/ed31ae90-79f9-11e6-846a-04d6e3a0a8ed.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo informar versão do navegador

**Comment by lucasretondo** [comment]
@raphaelMCarvalho segue...

![image](https://cloud.githubusercontent.com/assets/20990100/18529519/d0036926-7aa3-11e6-97b0-e628e2c4e25d.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo dependendo do navegador e versão, a aparência desse componente pode variar. Uma possibilidade seria não utilizar o componente default (select), criando um nosso e deixando ele com aparência homogênea entre os navegadores. Isso irá requerer algumas horas.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo essa alteração irá requerer algumas horas, quão importante ela é frente às outras issues?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho tratar os detalhes do layout no Explorer não é prioridade devido ao pequeno marketshare. Importante garantirmos que o layout esta padronizado nos outros navegadores com grande participação no mercado, exemplo: firefox.
