### ISSUE TITLE
Largura coluna Criar Orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#105]
Aumentar a largura das colunas unidade
![image](https://cloud.githubusercontent.com/assets/20990100/18572154/0a7f0a10-7b8f-11e6-9d54-af534d0c6732.png)

e qtd
![image](https://cloud.githubusercontent.com/assets/20990100/18572157/101c8e20-7b8f-11e6-9318-301aee851c87.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo pode fechar essa issue duplicada
