### ISSUE TITLE
Falta informações quando esta aguardando resposta

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#107]
Esta faltando o encerra e status.
![image](https://cloud.githubusercontent.com/assets/20990100/18572376/267abb40-7b91-11e6-966a-b9d887c5bf35.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Este bug estará resolvida com a resolução da issue #35

**Comment by lucasretondo** [comment]
Corrigiu a primeira tabela, mas da um erro e...
![image](https://cloud.githubusercontent.com/assets/20990100/18605061/191fbc84-7c5e-11e6-8c97-1b4e283dbe29.png)

estragou a tabela principal.
![image](https://cloud.githubusercontent.com/assets/20990100/18605068/35fec098-7c5e-11e6-8b71-cf61d7da86dd.png)

**Comment by raphaelMCarvalho** [comment]
Limpou o cache?
