### ISSUE TITLE
Resposta Orçamento - Exibir as dúvidas respondidas antes

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#108]
Acho melhor o lojista ver dúvidas já foram respondidas antes de enviar uma nova, o que vocês acham?

É fácil exibir primeiro as dúvidas já respondidas e depois enviar dúvida?

![image](https://cloud.githubusercontent.com/assets/20990100/18572660/767c56c4-7b93-11e6-8f4f-33c24ea96ebc.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo você se refere a apenas inverter no layout? Exibir as dúvidas primeiro e só depois exibir a parte em que ele pode enviar dúvidas?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho sim, só inverter o layout.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo é tranquilo fazer então

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vamos aumentar um pouco o tamanho da fonte da dúvida e resposta.
