### ISSUE TITLE
Orçamento #152 está no limbo

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#11]
O orçamento ID 152, do usuário weslley.1985@gmail.com, está no "limbo", pois está vazio e não é possível inserir itens no mesmo, nem exclui-lo.

![image](https://cloud.githubusercontent.com/assets/7696307/17611205/978ba448-601b-11e6-9642-d09cd60e21eb.png)

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio essa anomalia foi prevenida na issue #4
