### ISSUE TITLE
Perda dos meus orçamentos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#113]
Salvar não funcionar e não dá nenhuma mensagem
 ![image](https://cloud.githubusercontent.com/assets/20990100/18608681/4b8119e4-7cc6-11e6-9794-36c0eb8eaa9e.png)

Depois de colocar um endereço o salvar funcionou
 ![image](https://cloud.githubusercontent.com/assets/20990100/18608682/4f241998-7cc6-11e6-93a8-b70b495331b1.png)

Mas deu erro na página em seguida
![image](https://cloud.githubusercontent.com/assets/20990100/18608684/54bf1e98-7cc6-11e6-9cae-50382185b520.png)
E novamente eu perdi todos os meus orçamentos

Curioso que o meu resumo aparentemente funciona
![image](https://cloud.githubusercontent.com/assets/20990100/18608686/5e19166a-7cc6-11e6-8081-f05b3b7de49f.png)
 
Mas ao abrir o detalha aparece uma mensagem de erro 
![image](https://cloud.githubusercontent.com/assets/20990100/18608687/621b99cc-7cc6-11e6-8683-82c577285854.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo vi que já haviam orçamentos solicitados pra essa conta. O erro surgiu antes de salvar já ao listar os orçamentos ou somente após salvar?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho somente após salvar

**Comment by lucasretondo** [comment]
@raphaelMCarvalho aconteceu novamente este problema, desta vez com o usuário cliente1@mailinator.com. Apenas selecionei um orçamento manualmente e quando cliquei em Enviar Pedido deu erro e sumiu o Meus Orçamentos

**Comment by raphaelMCarvalho** [comment]
@lucasretondo identificamos um bug relacionado às categorias/subcategorias dos produtos que poderiam causar falha no carregamento das páginas de orçamentos e pedidos. Por favor limpe o cache e faça o teste novamente.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho funcionou para os usuários lucas.retondo e cliente2, mas não funcionou para os usuários cliente1 e cliente4, veja o vídeo: https://drive.google.com/file/d/0B_JJI1HknOlucDcyczFJNnpjOEk/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo cheque novamente por favor
