### ISSUE TITLE
Meus Pedidos Cliente e Lojista - Incluir data entrega nos pedidos que aguardam confirmação

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#117]
Colocar a data de entrega do pedido que aguardam confirmação

![image](https://cloud.githubusercontent.com/assets/20990100/18610361/2ea1120e-7cf1-11e6-94ca-225c00b4074e.png)

**Comment by raphaelMCarvalho** [comment]
Não há uma data de entrega neste momento pois o pedido ainda não foi confirmado.
#43 e https://github.com/PraConstruir/web_app/issues/54#issuecomment-244383537

**Comment by raphaelMCarvalho** [comment]
@lucasretondo marcarei como inválida segundo a justificativa apresentada em #43 e #54

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Não concordo, independente o lojista já tem confirmado o pedido a data de entrega já esta estabelecida. Acho que esta informação pode ser útil inclusive para o lojista confirmar a entrega.
