### ISSUE TITLE
Não arquiva

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#119]
Abri o orçamento e cliquei em arquivar
![image](https://cloud.githubusercontent.com/assets/20990100/18610398/cbe9326c-7cf1-11e6-9e0b-15eb558b12d6.png)

Cliquei em Arquivar novamente
![image](https://cloud.githubusercontent.com/assets/20990100/18610400/d5ea4be8-7cf1-11e6-9b19-09740ea46d72.png)

e não foi criado o orçamento arquivado
![image](https://cloud.githubusercontent.com/assets/20990100/18610403/e5d27b5c-7cf1-11e6-98cf-fd624387b61d.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo identificamos que os orçamentos estavam sendo arquivados normalmente no backend, no entanto um bug no frontend impedia que eles fossem listados. Isso foi corrigido.
