### ISSUE TITLE
Texto com alinhamento diferente dos demais similares

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#12]
Na página onde o lojista vai preencher os dados de um orçamento solicitado, a mensagem de ajuda para inserir a marca no campo, "Insira a marca", está com alinhamento diferente das demais mensagens.

![image](https://cloud.githubusercontent.com/assets/7696307/17611362/f630b82a-601c-11e6-8e83-263be560528c.png)

**Comment by raphaelMCarvalho** [comment]
Resolvido.

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio @lucasretondo Foi possível validar esta issue?
