### ISSUE TITLE
Notificação quando não esta logado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#121]
Esta aparecendo esta notificação em Meus Pedidos sendo que o usuário não esta logado.
![image](https://cloud.githubusercontent.com/assets/20990100/18610527/dea941be-7cf4-11e6-9d94-269c029e2621.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo informar sempre os passos para chegar até o resultado, apenas captura de tela não é o suficiente. Havia algum usuário previamente logado? Foi realizado logout? etc.
