### ISSUE TITLE
Cadastro Cliente e Lojista - Não permitir copiar e colar senha

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#122]
A página confirmar senha não deve permitir copiar e colar e nem carregar o histórico (clientes e lojistas).
![image](https://cloud.githubusercontent.com/assets/20990100/18611814/5c8645be-7d1d-11e6-8cfc-a29fe1b6e2be.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo carregar histórico? Quando você entrou nesta página já havia uma senha nos campos? Temos que lembrar que algumas coisas registradas como bug ou melhoria são comportamento do navegador. Por exemplo, se o usuário salva uma senha, o navegador identifica campos de password nesse site e pode já mostrar preenchido. Quanto a não deixar o usuário colar senha, melhoria.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ok.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo @wespatrocinio esta é uma alteração que eu não recomendo, no entanto, foi marcada como importante. Faremos o que for viável.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho pq você não recomenda? estamos falando de não permitir e copiar e colar no campo confirmar senha, correto?

**Comment by wespatrocinio** [comment]
@raphaelMCarvalho, o que o @lucasretondo está sugerindo é que seja feito o mesmo que vocês fizeram para o campo de "Confirmar e-mail", onde o navegador não sugere nenhum preenchimento anterior e exige que o usuário coloque o input novamente. Os próprios navegadores + HTML5 já possuem mecanismos para isso.

Entretanto, a parte de evitar que ele copie e cole é agressiva e também um pouco vulnerável, uma vez que estaremos, de fato, dando _override_ em funcionalidades do navegador. Isso será um ponto que sempre terá bug quando surgirem novas runtimes nos navegadores, sendo que o ganho é muito baixo.

Eu seguiria apenas com o não carregamento de senhas anteriores no campo de confirmar senha e permitindo que ele copie e cole. O risco maior é ele perder a senha por conta de _typo_, e para superar isso ele teria que recuperar a senha.

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio concordo
