### ISSUE TITLE
Histórico confirmar e-mail

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#123]
Não deve mostrar histórico (Cliente e lojista).
![image](https://cloud.githubusercontent.com/assets/20990100/18611817/6e905e52-7d1d-11e6-8682-227d7167aa52.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo esse é o comportamento padrão do navegador pra campos de input deste tipo. Para dar override nisso, é preciso estudar alguns métodos e não é garantia que isso funcionará de maneira uniforme em todos os navegadores. Veja aí a importância e prioridade dessa melhoria.
