### ISSUE TITLE
Meus Orçamentos Lojista - Unificar meus orçamentos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#127]
Tornar o Meus orçamentos dos lojistas igual dos clientes.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo o que seria exatamente "unificar meus orçamentos"? Seria remover do menu lateral os sub-itens que filtram os orçamentos do lojista por status?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho sim, a ideia é deixar somente um item no menu lateral (Meus Orçamentos) e incluir todos os orçamentos em uma única tabela igual a visão do cliente. Lembre que no caso do lojista a ordenação da tabela deve considerar os status na seguinte ordem: Pendente, Em andamento, Finalizado, Prazo expirado e Não finalizado.
