### ISSUE TITLE
Não tem regra de validação para ano de nascimento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#128]
![image](https://cloud.githubusercontent.com/assets/20990100/18611838/008fc004-7d1e-11e6-9058-a3f8563262ac.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo há alguns pontos para validar na data de nascimento:

1) aniversários em dias de fevereiro para anos bissextos
2) data não pode ser no futuro
3) o dia do mês precisa ser válido (30/02 por exemplo é inválido)
4) a idade da pessoa

As 3 primeiras regras de validação já se encontravam no sistema, faltando apenas essa última regra quanto à idade da pessoa que subimos neste update.
