### ISSUE TITLE
Criar Orçamento - Incluir legenda para "*"

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#129]
Falta legenda do asterisco
![image](https://cloud.githubusercontent.com/assets/20990100/18611841/259ad8a2-7d1e-11e6-8547-f7a33c6f4c1a.png)

**Comment by lucasretondo** [comment]
Não é mais interessante excluir o "*" e colocar uma legenda dizem que todos os campos são obrigatórios exceto outras informações?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho temos que seguir um padrão. No cadastro a legenda esta no canto superior direito
![image](https://cloud.githubusercontent.com/assets/20990100/19169914/bbc0f1d6-8bec-11e6-87e8-a1ae5314a91d.png)

Já a legenda criada esta no canto inferior direito com uma fonte diferente
![image](https://cloud.githubusercontent.com/assets/20990100/19169934/d227335e-8bec-11e6-83d1-4fc63ef84380.png)

Sugiro seguirmos o padrão já estabelecido no cadastro e alterar o criar orçamento para
![image](https://cloud.githubusercontent.com/assets/20990100/19170008/07af890e-8bed-11e6-8314-52fa74e738f7.png)

**Comment by raphaelMCarvalho** [comment]
![captura de tela de 2016-10-06 18-12-28](https://cloud.githubusercontent.com/assets/20994342/19170877/776d014c-8bf0-11e6-8599-9ed360c9e90f.png)

**Comment by lucasretondo** [comment]
Fechou...
