### ISSUE TITLE
Excesso de dígitos na exibição da distância

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#13]
Na página de Orçamentos Pendentes, onde o lojista preenche os dados do orçamento solicitado pelo cliente, a distância da obra do cliente está sendo exibida com mais de 10 dígitos depois da vírgula. Isso pode ser reduzido para apenas 1 dígito após a vírgula.

![image](https://cloud.githubusercontent.com/assets/7696307/17611394/3a77a6ba-601d-11e6-8a62-43fbe7cd6336.png)

**Comment by raphaelMCarvalho** [comment]
Resolvido.

**Comment by lucasretondo** [comment]
Ainda existem casos com mais de uma casa decimal. Sugiro chegar todos os templates.

![image](https://cloud.githubusercontent.com/assets/20990100/18221375/c13af896-7152-11e6-9ec2-3efb95f7fe62.png)
