### ISSUE TITLE
Divergência status orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#133]
Na visão do cliente o orçamento 72 esta com o status "Verficiar orçamento"
![image](https://cloud.githubusercontent.com/assets/20990100/18611895/046d7ed0-7d20-11e6-9754-0cee332a6281.png)

Já na visão do lojista ele aparece como finalizado
![image](https://cloud.githubusercontent.com/assets/20990100/18611902/1d8c759c-7d20-11e6-8c73-8c59ef8d2312.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo informar sempre os passos até chegar ao resultado em tela, informando se tudo ocorreu normalmente, se houve mensagem de erro, etc. Isso precisa ser operação padrão no registro de issues.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho neste caso assim que eu respondi o orçamento com o lojista o status mudou de pendente para finalizado.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo testamos aqui seguindo as informações fornecidas e não foi possível reproduzir este problema. Pela descrição da issue, esse foi o fluxo que você realizou:

1 - solicitou orçamento com o cliente
2 - em tempo hábil (ou seja, sem expirar) você respondeu o orçamento com o lojista em questão
3 - em tempo hábil (ou seja, sem expirar) você verificou o orçamento
4 - não realizou a solicitação de pedido

Veja essa captura de tela com a consulta a cada passo desse fluxo no banco de dados. Os status de cliente 1, 0 e 5 correspondem a 'WAITING_ANSWER', 'VERIFY' e 'FINALIZED', nesta mesma ordem.

![captura de tela de 2016-09-28 12-44-31](https://cloud.githubusercontent.com/assets/20994342/18921116/f5bb554e-8579-11e6-8476-4dca84977a48.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não identifiquei novamente...
