### ISSUE TITLE
Orçamento não exibido

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#134]
O lojista Godoy respondeu o orçamento 72
![image](https://cloud.githubusercontent.com/assets/20990100/18611911/55b53562-7d20-11e6-9846-2890cdb4fa72.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18611912/5b50abf0-7d20-11e6-931e-fbb8dbb3bc6f.png)

Porém o cliente não tem acesso
![image](https://cloud.githubusercontent.com/assets/20990100/18611917/85cfb9ca-7d20-11e6-8fd4-4612bbbe354f.png)

**Comment by lucasretondo** [comment]
O mesmo ocorre com o Materiais Carrai
![image](https://cloud.githubusercontent.com/assets/20990100/18611922/a4e7e74c-7d20-11e6-9c2d-89c0913fc8ab.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18611924/abaab5b4-7d20-11e6-96ab-a318af492907.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo irei marcar esta issue como duplicada pois a causa do comportamento é a mesma da issue #132
