### ISSUE TITLE
Orçamento Recebido - Caixa texto da segunda opção de marca

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#135]
A caixa tem que ficar embaixo e não ao lado (verificar todas as caixas de texto).
![image](https://cloud.githubusercontent.com/assets/20990100/18611988/5c698834-7d22-11e6-8838-97e063427782.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo não entendi a issue. Não está de acordo com o layout recebido?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho esta igual o layout sim, mas lembro que você alertou que esta caixa deveria ficar em baixo para caber na página quando a exibição for 100%.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho temos que revisar todas as caixas de textos que ficam nas últimas colunas da direita.
