### ISSUE TITLE
Cadastro Obra - Criar apelido para uma obra

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#137]
Podem existir duas obras dentro do mesmo condomínio.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo trazendo para discussão, precisamos definir exatamente como seria essa melhoria e como resolveremos a issue #8

**Comment by lucasretondo** [comment]
@raphaelMCarvalho a ideia é criar uma regra de validação para quando o endereço + número foram iguais o sistema exibir endereço+ número + complemento. Por enquanto esta não é uma prioridade.
