### ISSUE TITLE
Loop para fazer o cadastro

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#138]
![image](https://cloud.githubusercontent.com/assets/20990100/18612127/60bfd97e-7d27-11e6-9ea6-afe3cbd12d34.png)
![image](https://cloud.githubusercontent.com/assets/20990100/18612128/628728e8-7d27-11e6-8cd3-ebfebe04890d.png)
![image](https://cloud.githubusercontent.com/assets/20990100/18612129/6488bcf6-7d27-11e6-8f0e-08a7a67eebbe.png)
Cliquei em solicitar orçamento
![image](https://cloud.githubusercontent.com/assets/20990100/18612130/668b5fb8-7d27-11e6-86b3-525a6c7dd743.png)
Cliquei em continuar
![image](https://cloud.githubusercontent.com/assets/20990100/18612134/700e72dc-7d27-11e6-9e57-506ae5948441.png)
voltei e fiquei em loop
![image](https://cloud.githubusercontent.com/assets/20990100/18612138/7e0e5cc6-7d27-11e6-9766-e4ca6f772527.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo o que você quer dizer com "voltei e fiquei em loop"? Qual foi a ação exatamente após clicar no botão Continuar, que abre a tela de cadastro em que você precisa informar os dados pra registro?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho reproduzi no exemplo acima tela a tela, após clicar em Continuar no termo de uso eu fui direcionado para a tela de criar um novo cadastro novamente, não abre a tela para registrar os dados.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho fiz um novo teste a pouco e dessa vez o usuário foi direcionado para a página de cadastro, porém tive que clicar, temos que eliminar este clique.

https://drive.google.com/file/d/0B_JJI1HknOluWW9SQjloLTFUSGM/view

**Comment by raphaelMCarvalho** [comment]
Entendi, você precisou clicar pra que o diálogo fechasse. É um bug.

**Comment by lucasretondo** [comment]
Achei o looping... https://drive.google.com/file/d/0B_JJI1HknOluVWd5eDJfZnc3SDQ/view
