### ISSUE TITLE
Perdeu a obra salva

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#139]
Loop para fazer o cadastro #138
![image](https://cloud.githubusercontent.com/assets/20990100/18612147/f18b95ec-7d27-11e6-8367-1d4f00a8f718.png)
![image](https://cloud.githubusercontent.com/assets/20990100/18612148/f4358cd0-7d27-11e6-8574-e891acc578c9.png)
![image](https://cloud.githubusercontent.com/assets/20990100/18612150/0550c354-7d28-11e6-9e49-dfd96b37ad95.png)
![image](https://cloud.githubusercontent.com/assets/20990100/18612151/0a1ba0de-7d28-11e6-8209-1486b4e8a08f.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo "perdeu a obra salva" = quando você abriu novamente o orçamento salvo, não estava exibindo a obra no select?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo issue duplicada, #114
