### ISSUE TITLE
Botão "Grave sua dúvida" não funciona

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#14]
Na página de Orçamento pendente, o botão "Grave sua dúvida", onde o lojista pode gravar uma mensagem para tirar uma dúvida com o cliente, não executa nenhuma ação.

Chrome Versão 51.0.2704.103 m

![image](https://cloud.githubusercontent.com/assets/7696307/17611430/8ff1b978-601d-11e6-8ab5-f0d8498fe2e7.png)

**Comment by lucasretondo** [comment]
Quanto testei como parceiro funcionou, mas quando testei como consumidor não funcionou:
![image](https://cloud.githubusercontent.com/assets/20990100/17622370/55315f34-6070-11e6-9f86-94a6019a8c51.png)

**Comment by raphaelMCarvalho** [comment]
O navegador Chrome passou a exigir origem segura para recursos como a gravação de áudio. Quando estivermos com https isso estará resolvido, por ora fica a issue aberta. Fora isso, havia outro bug relacionado que foi resolvido.

**Comment by wespatrocinio** [comment]
Ok, @raphaelMCarvalho. Vou manter essa issue aberta até que estejamos aptos a testa-la
