### ISSUE TITLE
Status Divergentes

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#140]
O pedido 75 para o lojista esta finalizado
![image](https://cloud.githubusercontent.com/assets/20990100/18612267/bd7e9124-7d2b-11e6-88f0-92de530c2533.png)

E para o cliente esta aguardando entrega
![image](https://cloud.githubusercontent.com/assets/20990100/18612274/cb3bb5ee-7d2b-11e6-8a79-6aa1f4baa885.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo quais foram os passos para chegar a esse resultado? O que houve durante a realização dos passos? Tudo ocorreu normalmente? Houve alguma mensagem de erro?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não ocorreu nenhum erro. No teste do lojista eu fiz todos os passos da confirmação do pedido a avaliação em um único acesso.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo não foi possível reproduzir o problema apontado, nos nossos testes o fluxo é completo com sucesso. Veja esta relação de status, para acompanhar as mudanças no banco de dados que cito logo em seguida:

![captura de tela de 2016-09-28 14-10-26](https://cloud.githubusercontent.com/assets/20994342/18924191/906b47ce-8585-11e6-9a48-5031ad41c50f.png)

No banco de dados, temos na captura de tela abaixo as mudanças de status de cliente e lojista conforme as ações são executadas. Neste caso, após o cliente realizar o pedido, seguimos o mesmo fluxo apontado na issue: seguimos todas as ações com o lojista até o fim, e depois continuamos com o cliente. Cabe ressaltar o quanto essa independência entre lojista e cliente é importante pra deixar a experiência de ambos bem fluida.

![captura de tela de 2016-09-28 14-05-47](https://cloud.githubusercontent.com/assets/20994342/18924267/edb36ace-8585-11e6-8d8f-15528f143704.png)

**Comment by lucasretondo** [comment]
igual #133
