### ISSUE TITLE
Erro Meus Pedidos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#141]
Criei um usuário cliente3@mailinator.com novo e cheguei até o verificar orçamento sem nenhum erro, personalizei um orçamento e enviei o pedido normalmente. Após a mensagem de pedidos criados a página Meus Pedidos apresentou um erro e travou.
![image](https://cloud.githubusercontent.com/assets/20990100/18616990/f235fce2-7d9c-11e6-93b7-9b0ef58e512c.png)
Desta vez o Meu Resumo também travou
![image](https://cloud.githubusercontent.com/assets/20990100/18616994/fbe38124-7d9c-11e6-9e99-4bfa9cab355d.png)
Porém o Meus Orçamentos esta normal
![image](https://cloud.githubusercontent.com/assets/20990100/18616995/046bbec4-7d9d-11e6-9516-09c87db0d9b1.png)

**Comment by raphaelMCarvalho** [comment]
Pode estar relacionada à issue #113

**Comment by raphaelMCarvalho** [comment]
@lucasretondo identificamos um bug relacionado às categorias/subcategorias dos produtos que poderiam causar falha no carregamento das páginas de orçamentos e pedidos. Por favor limpe o cache e faça o teste novamente.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho funcionou.
