### ISSUE TITLE
Melhorar ordem auto complete

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#144]
Qual é a ordem neste caso?
![image](https://cloud.githubusercontent.com/assets/20990100/18617270/352ad680-7da2-11e6-9b6a-0232afd23427.png)

**Comment by lucasretondo** [comment]
Ainda não esta 100%
![image](https://cloud.githubusercontent.com/assets/20990100/18772758/ee457e42-811f-11e6-9515-7d9ff96a9ca3.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo este bug se dá porque os algoritmos de ordenação mais comuns ordenam essas strings alfanuméricas segundo valores ASCII, não ordenam como nós, olhando letras e números. Dessa forma, enquanto nós identificamos facilmente que 'barra 3 m' deve vir antes de 'barra 12 m', o algoritmo não enxerga dessa forma. Veja abaixo:

- barra 3 m -> 098 097 114 114 097 032 **051 032 109** (em destaque o valor referente a 3 m)

- barra 12 m -> 098 097 114 114 097 032 **049 050 032 109** (em destaque o valor referente a 12 m)

Segundo os valores ASCII, o algoritmo vai acabar colocando 'barra 12 m' antes de 'barra 3 m' ao se deparar com o valor 049.

Já temos uma alternativa em mãos e vamos implementar.

Se tiver curiosidade, segue a tabela ASCII:
https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/ASCII-Table-wide.svg/2000px-ASCII-Table-wide.svg.png

**Comment by lucasretondo** [comment]
@raphaelMCarvalho o problema acima foi corrigido e ficou ótimo:
![image](https://cloud.githubusercontent.com/assets/20990100/19014357/a0387314-87c1-11e6-8ada-963ed5432f99.png)

Porém encontrei outra caso que precisamos arrumar:
![image](https://cloud.githubusercontent.com/assets/20990100/19014361/b1115c96-87c1-11e6-93e5-2a219a12015c.png)

Você prefere abrir outra issue ou mantemos esta aberta?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo aparentemente é algo bem simples de resolver, vamos manter essa aberta mesmo, na segunda a gente já sobe o ajuste

**Comment by raphaelMCarvalho** [comment]
@lucasretondo o problema era que o web service estava enviando todas as unidades registradas no banco de dados, mesmo aquelas que os usuários inserem manualmente. A unidade 'un' por exemplo, que aparece em sua captura de tela, não deveria estar sendo enviada, já que ela não consta na última planilha que utilizamos para inserir os produtos. Acredito que tenha sido substituída por Peça.
