### ISSUE TITLE
Mapa obrigatório

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#146]
Cliquei em "Utilizar endereço dos dados pessoais" e não carregou o mapa
![image](https://cloud.githubusercontent.com/assets/20990100/18617324/6622f690-7da3-11e6-9880-49e63062dbf3.png)
Em seguida tentei avançar e deu este erro de campo obrigatório
![image](https://cloud.githubusercontent.com/assets/20990100/18617327/6e44e0b8-7da3-11e6-8ed7-6c654aa6d9c2.png)
Como eu avanço?

**Comment by raphaelMCarvalho** [comment]
Caso aconteça algum problema no carregamento automático da localização no mapa, o usuário poderá clicar para reiniciar a ação. Lembrando que o usuário também pode manualmente marcar a posição navegando pelo mapa.

![2016-09-23 1](https://cloud.githubusercontent.com/assets/20994342/18798646/d9f6b318-81a9-11e6-97e0-2ea0ca41cc0d.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho infelizmente não funcionou o link de recarregar o mapa. O mapa tem que ser obrigatório?

Segue o vídeo com o teste: https://drive.google.com/file/d/0B_JJI1HknOluV2hja0hjeGs1bDQ/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo identifiquei o problema aqui, a API do Google não está retornando resultados pro endereço que você utilizou no cadastro, logo o botão não ajuda em nada, pois ele apenas realiza a consulta novamente. Temos uma solução em mente pra essa chamada.

A título de curiosidade, essa é a URL da chamada que fazemos e que retorna 0 resultados:
https://maps.googleapis.com/maps/api/geocode/json?address=Rua%20Ant%C3%B4nio%20Ferraz%20de%20Almeida,%20200%20-%20Terra%20Nova,%20Piracicaba%20-%20SP,%2013423700
