### ISSUE TITLE
Cadastro Lojista - Melhorar layout cadastro horário de funcionamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#148]
Não está bom o layout e comunicação da localização do horário de funcionamento e vencimento do boleto.
![image](https://cloud.githubusercontent.com/assets/20990100/18617486/d8c011da-7da6-11e6-8c5b-efb1e2d0d987.png)

**Comment by raphaelMCarvalho** [comment]
#151

**Comment by raphaelMCarvalho** [comment]
@lucasretondo veja se o ajuste realizado na issue #151 já atende a solicitação, caso não atenda, por favor apresente a proposta de como precisamente deve ser realizada a melhoria
