### ISSUE TITLE
Campo "Marca ou origem" não é obrigatório para todos os produtos

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#15]
O campo "Marca ou origem", exibido na tela de Orçamentos Pendentes a ser preenchida pelo lojista, não é obrigatório para todos os itens / subcategorias.

![image](https://cloud.githubusercontent.com/assets/7696307/17611472/f8b7beee-601d-11e6-843d-da640d4df154.png)

**Comment by raphaelMCarvalho** [comment]
Quais são as categorias/subcategorias cujos itens possuem obrigatoriedade de preenchimento de marca?

**Comment by wespatrocinio** [comment]
@raphaelMCarvalho na planilha de Cadastro de Materiais, que vocês usaram para popular o banco de dados para o autocomplete, tem uma coluna "Marca ou Origem" com os valores "Sim" ou "Não". É essa informação que vai ditar se é obrigatório ou não

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio o que deve ser feito com casos como o abaixo? Deve ser inserido no banco de dados? Se sim, como será o nome do produto?

**ID | Categoria | Sub-categoria | Código | Produto**
1 | 03 - Tijolo & Bloco | 06 - Tijolo ecológico | 03060001 | NA

**Comment by wespatrocinio** [comment]
@raphaelMCarvalho eu sugiro não inserir no banco, e nós corrigirmos o cadastro deste item. É importante para mantermos a homogeneidade dos dados em nossas bases

**Comment by wespatrocinio** [comment]
@raphaelMCarvalho fui validar o bug, e me deparei com a seguinte situação:

![image](https://cloud.githubusercontent.com/assets/7696307/19037215/75d99b12-894b-11e6-9b4a-15f9b02e3238.png)

Quando fui tentar responder o orçamento sem inserir nenhuma marca, tive o feedback de que "Existem marcas não preenchidas". Entretanto, tem os seguintes pontos:
- Não tinha um indicativo explícito de quais itens tem a marca como obrigatória;
- Na linha do item "Cabo flexível", os campos da marca estão em branco, e não em vermelho. Entretanto, a marca para este item é obrigatória. O único item com a marca não obrigatória é a Areia.

Resumindo, da maneira atual o lojista tem que ir na tentativa e erro ou então ele sempre será levado a preencher todos os campos.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho @wespatrocinio eu cadastrei este mesmo bug na issue #228.

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio @lucasretondo nesse caso acho melhor fechar a issue #228 já que a issue em que estamos foi marcada como Correção não efetivada

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio @lucasretondo Pessoal, para fazer as validações e exibir os feedbacks das marcas obrigatórias, só quero deixar aqui definido que sempre o primeiro preço é obrigatório o preenchimento (ou o lojista informa o preço 1, ou marca como indisponível ou fora de escopo). Atendido esse requisito, daí é verificado se para a categoria em questão, o preenchimento de marca é obrigatório. O outro caso é (já pegando o gancho da issue #203): vamos implementar para que seja validado quando o lojista informar dois preços e apenas uma das marcas; o preenchimento da outra marca nesse caso será obrigatório.
