### ISSUE TITLE
Meus Orçamentos - Exibir todos os orçamentos pendentes já existentes no primeiro acesso

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#150]
Primeiro cadastrei um cliente novo e criei e solicitei um orçamento normalmente. Em seguida cadastrei um novo lojista e quando terminei não apareceu nenhum orçamento pendente. O orçamento criado anteriormente não deveria aparecer?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo não, pois o orçamento é enviado para os lojistas que atendam no raio da obra cadastrada pelo cliente, no momento em que ele envia. Se o lojista não existe naquele momento, ele não tem como receber a solicitação.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho entendi o fluxo do sistema, mas o ideal é que o lojista tenha visibilidade sobre todos os orçamentos disponíveis assim que fizer o cadastro. Imagine que você é um lojista e ao cadastrar já tem visibilidade sobre vários orçamentos pendentes, com certeza a experiencia será melhor do que ao cadastrar não ter nenhum orçamento pendente, concorda?

Outra dúvida, se um lojista aumentar o seu raio médio, ele só terá visibilidade sobre os novos orçamentos? Esta é outra experiência ruim para o usuário.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo essa seria uma melhoria que aumenta o nível de complexidade da feature, essa regra de negócio está bem fechada e testada atualmente.

Se o lojista aumenta o raio, isso terá efeito para novos orçamentos, não para os já pendentes.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho entendi, vamos desconsiderar esta melhoria por enquanto, mas não quero excluí-la, quero usar o GitHub para organizar todas as melhorias que eu tenho anotadas.
