### ISSUE TITLE
Cadastro Lojista - Reduzir as opções de hora e minuto

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#151]
Esta ruim de preencher, temos que pensar em alguma forma de reduzir as opções de horas e minutos
![image](https://cloud.githubusercontent.com/assets/20990100/18617517/ab0ab46a-7da7-11e6-9b2e-9b4c54252bcd.png)

Sugestão:
Horas Abertura - 5h as 12h
Horas Fechamento - 12h as 18h
Minutos - 00 e 30

**Comment by raphaelMCarvalho** [comment]
@lucasretondo está ruim de inserir sim, o vilão é a escolha do componente no layout. Ao utilizar select, quem criou o layout obrigou o usuário a realizar 5 cliques para informar, por exemplo, que abre das 08h às 18h de segunda a sexta-feira, fora os scrolls e o trabalho do usuário localizar os valores em cada uma das 4 listas de valores.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo temos que ter parcimônia ao realizar essas restrições de valores que o usuário pode ou não inserir. Reduzimos as opções de minutos para 00 e 30, e o range de horas inicia em 05h. O mesmo range de horas e minutos é compartilhado entre os dias da semana, não se pode afirmar que um lojista não teria fechamento às 11h30 num sábado ou mesmo que ele não possa fechar sua loja às 20h.

Como comentei acima, o problema aqui não é a quantidade de valores, mas sim o componente escolhido para a inserção dos mesmos.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho blz, concordo com vc. Qual componente você julga ser mais adequado para melhorar no futuro? E mais, depois de lançarmos o MPV teremos condições de avaliar a utilidade destas informações na visão usuários e fluxo.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo acho que podem ser 2 campos de texto, um para abertura e outro para fechamento, com máscara de hora e minuto

**Comment by lucasretondo** [comment]
@raphaelMCarvalho entendi e gostei. Vou criar uma nova issue com este ponto e em seguida vou fechá-la apenas para deixarmos documentado esta melhoria para o futuro.
