### ISSUE TITLE
Cadastro Lojista - Excluir opções inválidas dos acréscimos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#152]
Não existe dinheiro, débito, deposito e construcard parcelado?
![image](https://cloud.githubusercontent.com/assets/20990100/18617529/ff92c784-7da7-11e6-9265-51b878f3d12c.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo basta definir quais opções de pagamento devem aparecer aí

**Comment by lucasretondo** [comment]
@raphaelMCarvalho somente os meios de pagamento cartão de crédito, cheque e boleto devem ter parcelas.
