### ISSUE TITLE
Notificação - Somar confirmar entrega somente quando próximo da entrega

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#154]
Somar o status confirmar entrega na notificação somente quando o prazo estiver para vencer, caso contrário irá alertar o usuário sem necessidade. Usar este mesmo critério para exibir ou não o pedido no Meu Resumo.

![image](https://cloud.githubusercontent.com/assets/20990100/18617572/e348062e-7da8-11e6-861d-a4704e1b2d73.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo pelo que lembro da especificação, não há essa granularidade de quantidade de notificações dependendo do prazo. Sendo assim, irei marcar como melhoria.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho concordo, é melhoria.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho qual é a regra de negócio neste caso? Quanto tempo antes passa a contar?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo 1 hora antes

**Comment by lucasretondo** [comment]
@raphaelMCarvalho legal, obrigado.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho pq você reabriu esta issue?

**Comment by raphaelbluteau** [comment]
@lucasretondo Identifiquei um bug na solução da issue que precisa ser corrigido

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Relendo a descrição da issue, entendo agora que não era um bug, mas sim uma mudança de desejo da parte de vocês quanto ao que exibir ou não no resumo.

**Comment by lucasretondo** [comment]
Os pedidos com status "confirmar entrega" só devem somar na notificação e aparacer no Meu Resumo quando estiver próximo de vencer o prazo.
![image](https://cloud.githubusercontent.com/assets/20990100/20548001/10b90eb4-b107-11e6-86dc-8ab64b9c44f9.png)
