### ISSUE TITLE
Encerra calcula erro

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#156]
Este prazo para encerrar esta errado.
![image](https://cloud.githubusercontent.com/assets/20990100/18617594/7a0db748-7da9-11e6-95d3-4a9c9860bbb7.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo precisamos sempre de detalhes pra apurar as issues, apenas uma screenshot não é o suficiente. Nos informe por favor os passos até chegar a esta tela, o prazo que solicitou de entrega, o horário e dia em que solicitou, etc.

**Comment by lucasretondo** [comment]
Vamos fechar este bug por enquanto. Vou tentar simular novamente gravando.
