### ISSUE TITLE
Resposta Orçamento - Criar botão voltar ou pular (desistir)

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#157]
Temos que rever estes botões, não ter a opção voltar ou pular trava o lojista nesta página quando o pedido mínimo não é atingido.
![image](https://cloud.githubusercontent.com/assets/20990100/18617603/a16ffabc-7da9-11e6-88b9-5d12a05fe4f4.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho a opção de voltar destravou o usuário, mas não ficou fluído. É muito complicado implementar o pular e desistir?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo não entendi o motivo pelo qual essa issue foi marcada como 'Correção não efetivada'. O título e a descrição apontavam que a solução seria o lojista conseguir sair da tela, no próprio texto é apresentado que o botão Voltar resolveria (o que foi efetivamente implementado). Nesta issue você fala do lojista conseguir sair da tela por não atingir o pedido mínimo (imagino que pra talvez alterar o pedido mínimo se necessário). A issue #83 se refere a salvar o orçamento; são assuntos distintos.

Perguntas:

- O que quis dizer com "a opção de voltar destravou o usuário, mas não ficou fluído"?
- O que significa precisamente "pular e desistir" e qual a diferença entre "Voltar" e "Pular e desistir"? Aponto que no título está escrito "voltar **ou** pular (desistir)" e no novo comentário, está escrito "pular **e** desistir". 
- Por que, embora o "Voltar" tenha sido apresentado como possível solução no título e na descrição da issue, não é agora uma solução aceita?

De qualquer forma, assumindo que não foi expressada de forma clara o que se esperava como solução dessa issue, e respondendo objetivamente a pergunta "É muito complicado implementar o pular e desistir", e, assumindo que quando se fala de "pular e desistir" esteja se referindo ao lojista cancelar sua participação nesse orçamento (ou seja, o orçamento não é respondido e some da lista de orçamentos pendentes), esses pontos precisam ser trabalhados:

- Implementar no backend essa nova possibilidade, do lojista de forma ativa desistir do orçamento e não respondê-lo;
- Revisar o fluxo no backend para identificar de que forma essa nova possibilidade impacta no fluxo existente;
- Tratar as exceções e casos que surgirem da análise acima (por exemplo, de que forma será apresentado ao cliente um caso em que apenas um lojista pode atender sua solicitação e este desiste);
- Implementar o botão no frontend, com caixa de diálogo e as chamadas pro backend.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho segue as respostas as suas dúvidas:

Pergunta: O que quis dizer com "a opção de voltar destravou o usuário, mas não ficou fluído"?
Resposta: O lojista consegue voltar para o Meus Orçamentos (isso destravou), porém se ele tem mais orçamentos pendentes ele deve clicar o próximo orçamento pendente, abrir novamente a tela de resposta para continuar a responder os orçamentos (isso não é fluído). Acredito que com este procedimento o lojista terá dificuldade em lembrar qual era o orçamento, correndo assim o risco de clicar novamente no mesmo orçamento e ter que repetir o ciclo.

Pergunta: O que significa precisamente "pular e desistir" e qual a diferença entre "Voltar" e "Pular e desistir"? 
Resposta: Voltar -> direciona o usuário para a página Meus Orçamentos; Pular -> direciona o usuário para o próximo orçamento pendente, mas não exclui orçamento; Desistir -> excluir o orçamento na visão do lojista em questão (cancela a sua participação) e direciona o usuário para o próximo orçamento pendente.

Pergunta: Aponto que no título está escrito "voltar ou pular (desistir)" e no novo comentário, está escrito "pular e desistir".
Resposta: Concordo que o título e descrição ficaram confusas, não fechei a questão entre voltar, pular ou desistir pq queria ouvir a opinião de vocês sobre o esforço vs. benefício.

Pergunta: Por que, embora o "Voltar" tenha sido apresentado como possível solução no título e na descrição da issue, não é agora uma solução aceita?
Resposta: Sorry, exclui o label "Correção não efetiva"

Última pergunta antes de fecharmos esta issue, para implementar o botão Pular como descrito acima é necessário alterar o backend?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo isso mesmo, é necessário alterar o backend. A alteração em si não é grande, o maior trabalho seria checar todo o fluxo, identificar os pontos de impacto da mudança e fazer os ajustes necessários pra que não hajam comportamentos inesperados.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ok, vamos manter somente o botão voltar por enquanto e depois vemos se a inclusão da função pular ou desistir são realmente importantes.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho estou reabrindo este issue pois estamos tendo muitas reclamações sobre este ponto. Falei com o @claudineicaetano a pouco e precisamos pensar em uma solução para este problema.

**Comment by lucasretondo** [comment]
Não esta aparecendo o botão "Desistir":
![image](https://cloud.githubusercontent.com/assets/20990100/25437787/ec60ff8c-2a6d-11e7-97e6-f1269b94f4f8.png)

Já neste caso apareceu o botão (Orçamento 502):
![image](https://cloud.githubusercontent.com/assets/20990100/25437851/283f0a1c-2a6e-11e7-854f-fcd14ab63c18.png)

Porque?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo É pra aparecer sempre quando o status for este que você acessou a tela. Vou verificar o que ocorreu.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Foi resolvido o problema
