### ISSUE TITLE
Página após confirmar entrega

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#158]
Quando confirmar a entrega na página detalhada (por item) o cliente não direciona em seguida para avaliação lojista. Atualmente o usuário volta para a página meus pedidos.

**Comment by raphaelMCarvalho** [comment]
Issue relacionada: #115

**Comment by lucasretondo** [comment]
Após confirmar o pedido item a item o cliente continua sendo direcionado para o meus pedidos ao invés da avaliação do lojista.

https://drive.google.com/open?id=0B_JJI1HknOluLUhCQkV0WUhVYlk

**Comment by raphaelMCarvalho** [comment]
@lucasretondo de acordo com a tabela de status que tenho na especificação dos requisitos, a sequência é:

**Confirmar entrega > Confirmar pagamento > Avaliar cliente**

E não:

**Confirmar entrega > Avaliar cliente > Confirmar pagamento**

**Comment by raphaelMCarvalho** [comment]
@lucasretondo esclarecendo: a mudança realizada foi permitir que o lojista confirme a entrega item a item, isto não estava acontecendo
