### ISSUE TITLE
Orçamento digitado em outro dispositivo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#159]
O usuário criou uma lista de compras e ao Solicitar Orçamento ele foi obrigado a fazer o cadastro.

Ele fez o cadastro normalmente até a página abaixo no notebook
![image](https://cloud.githubusercontent.com/assets/20990100/18617634/9f3c042e-7daa-11e6-92da-918097d58717.png)

Em seguida recebeu o e-mail com o link para configurar a senha, cadastrou normalmente só que desta vez no iPad. Finalizar e voltar para criar orçamento o sistema não carregou o orçamento digitado.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo se o usuário ainda não existe no sistema, não há como mantermos uma lista de compras acessível a partir de outro dispositivo. Se ele prossegue após criar a senha e entra no mesmo dispositivo, essa lista é recuperada do ambiente local (seja app ou seja interface web). Isso está funcionando conforme esperado.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho é possível salvar o orçamento digitado ou o usuário só é criado após confirmar a senha?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo é possível sim salvar o orçamento, localmente, como já está sendo feito e funcionando conforme especificação. Após o registro da conta, o usuário já existe porém não é autenticado automaticamente, haja vista a confirmação do endereço de e-mail e criação da senha. Logo, não há como salvar o orçamento no servidor nessa fase.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo essa issue não será fechada?
