### ISSUE TITLE
Resposta Orçamento - Não exibição de valores para bloqueio de pedido mínimo

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#16]
Na tela de detalhe de um Orçamento pendente para o lojista, não são exibidos os valores totais dos pedidos para comparação com o valor de pedido mínimo.

![image](https://cloud.githubusercontent.com/assets/7696307/17611504/341f23be-601e-11e6-8879-fc5b9929417a.png)

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio resolvido.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho exibir também o valor total do pedido.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo @wespatrocinio Podemos tranquilamente exibir o valor do pedido mínimo quando este não for atingido. Quanto a exibir o valor total do pedido, como solicitado, é preciso definir exatamente o que se almeja alcançar, já que não temos um valor único como total de pedido.

Posso elencar algumas possibilidades:

1) Exibir o total da soma da opção 1 e o total da soma da opção 2 separadamente
2) Exibir o total como a soma do item mais barato de cada opção
3) Exibir o total como as somas que são inferiores ao pedido mínimo
4) Exibir todas as somas possíveis, cruzando as duas listas

* Para julgar se o pedido mínimo não foi atingido, pegamos o extremo em que o usuário seleciona os itens mais baratos de cada opção, e comparamos com o pedido mínimo. Se esta possibilidade cai na regra, o erro é exibido, não sendo necessário testar as demais possibilidades. Pode haver o caso em que pegando todos da opção 1 ou da opção 2, a soma seja superior ao pedido mínimo, o que pode causar confusão ao lojista.

### Exemplo 1:

**Opc 1** | **Opc 2**
A1 30 | A2 30
B1 29 | B2 30

Pedido mínimo: 61

- Opção 1 **não** atende ao pedido mínimo; (30 + 29)
- Opção 2 **não** atende ao pedido mínimo (30 + 30);
- Produtos A2 e B1 **não** atendem ao pedido mínimo (30 + 29);
- Produtos A1 e B2 **não** atendem ao pedido mínimo (30 + 30).

Ou seja, no caso acima temos 4 possibilidades, nenhuma delas atende ao pedido mínimo. Qual(is) soma(s) deve(m) ser exibida(s)? Como exibir?

### Exemplo 2:

**Opc 1** | **Opc 2**
A1 40 | A2 50
B1 51 | B2 41

Pedido mínimo: 91

- Opção 1 atende ao pedido mínimo; (40 + 51)
- Opção 2 atende ao pedido mínimo (50 + 41);
- Produtos A2 e B1 atendem ao pedido mínimo (50 + 51);
- Produtos A1 e B2 **não** atendem ao pedido mínimo (40 + 41).

Ou seja, no caso acima temos 4 possibilidades, uma delas não atende ao pedido mínimo, sendo este caso uma lista customizada, não uma "lista corrida". Qual(is) soma(s) deve(m) ser exibida(s)? Como exibir?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo @wespatrocinio Utilizei exemplo com 2 itens para facilitar a leitura e compreensão, mas imaginem agora com 10, 15 ou 30 itens na análise dessa questão.

**Comment by wespatrocinio** [comment]
@raphaelMCarvalho o que eu penso é o seguinte: se o propósito é informar ao lojista se o orçamento atende ao pedido mínimo configurado, o valor a ser exibido e comparado com o pedido mínimo é a menor configuração de valor do orçamento, ou seja, a opção número **2** dentre as que você listou.

Uma vez que a soma dos menores valores atinja o pedido mínimo, todas as outras combinações - contendo alguma das opções de todos os itens do orçamento - alcançará o pedido mínimo.

A primeira pergunta que surge é: e se tivermos uma situação como a do **Exemplo 2**, a comparação vai exibir que o valor mínimo não foi alcançado, mesmo tendo cenários que alcançam. Entretanto, eu vejo isso como uma enganação ao cliente, uma vez que ele receberá um orçamento para o qual não poderá executar o pedido.

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio Veja se a solução proposta está adequada. O que foi feito, além de exibir o valor do pedido mínimo, foi exibir a menor soma explicando de que forma ela é composta. Se tiver alguma ideia de como exibir isto de uma forma mais educativa, just let me know.
