### ISSUE TITLE
Feedback resposta dúvida

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#168]
O layout não muda depois que você envia uma resposta, assim não tem como saber se já vou enviado ou não.
![image](https://cloud.githubusercontent.com/assets/20990100/18620188/c3a476dc-7de3-11e6-9015-5b3d7651b6f6.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo não apareceu uma mensagem de aviso em verde?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho apareceu a mensagem verde, mas o botão "Enviar resposta" não mudou causando uma certa confusão. Não é melhor deixar mudar o layout para o formato de dúvida respondida?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Concordo

**Comment by lucasretondo** [comment]
@raphaelMCarvalho infelizmente o layout não esta mudando...

![image](https://cloud.githubusercontent.com/assets/20990100/18910078/c8591b40-854c-11e6-90cc-10caa6c0434d.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo realmente, não está funcionando como esperado. A tela atualiza quando o lojista envia uma dúvida, porém quando o cliente responde, não atualiza. Já identifiquei o problema.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho estou reabrindo esta issue pq quando o cliente responde uma dúvida o sistema mantém o bloco "Dúvidas à responder" mesmo quando não existe nenhum dúvida pendente.

![image](https://cloud.githubusercontent.com/assets/20990100/19275333/c527522c-8fa9-11e6-8207-876f12e4ba7c.png)

**Comment by raphaelMCarvalho** [comment]
![captura de tela de 2016-10-11 16-00-29](https://cloud.githubusercontent.com/assets/20994342/19284431/381f33e0-8fcc-11e6-9b8f-652c0f722b48.png)
