### ISSUE TITLE
Solicitar Orçamento -> Mensagem de orçamento salvo ao enviar o orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#169]
# Template para bugs

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Solicitação do orçamento

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Exibir somente a mensagem de pedido criado.

## 3. Descrição do que ocorreu

Ao clicar no botão enviar orçamento o sistema dá uma mensagem de orçamento salvo antes de exibir a mensagem de pedido criado.

## 4. Captura de tela

Video abaixo.

## 5. Passos para reproduzir a ocorrência

https://drive.google.com/file/d/0B_JJI1HknOluUnhVOEhqd1NyQXM/view?usp=sharing

## 6. Dados envolvidos na ocorrência (e-mails dos usuários)

Usuário: lucas.retondo@gmail.com

**Comment by raphaelMCarvalho** [comment]
@lucasretondo obrigado pela clareza nas informações. Este bug é duplicado, o problema já foi apontado na issue #155
