### ISSUE TITLE
Cadastro da obra - não é possível avançar para próxima página

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#174]
## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Cadastro da obra.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Validar o endereço.

## 3. Descrição do que ocorreu

Todos os campos obrigatório foram preenchidos e a mensagem de erro não mostra qual campo esta faltando. Não avançou para a próxima página mesmo depois de preencher todos os campos.

## 5. Passos para reproduzir a ocorrência

https://drive.google.com/file/d/0B_JJI1HknOluWW9SQjloLTFUSGM/view

## 6. Dados envolvidos na ocorrência (e-mails dos usuários)

Esta tudo no vídeo.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo qual navegador e versão você estava utilizando? Detectei que o campo de data de nascimento não estava sendo exibido no vídeo

**Comment by lucasretondo** [comment]
@raphaelMCarvalho segue o navegador. Pq não deu a mensagem de erro na primeira página?

![image](https://cloud.githubusercontent.com/assets/20990100/18692940/42a9de36-7f74-11e6-8d88-f3c0268b9ae0.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo é isso que vamos verificar

**Comment by raphaelMCarvalho** [comment]
@lucasretondo após diversas tentativas, não foi possível reproduzir este problema. Você conseguiu obter esse mesmo resultado com as mesmas ações apresentadas no vídeo?

**Comment by lucasretondo** [comment]
Não consegui reproduzir...
