### ISSUE TITLE
Resposta Orçamento - Incluir trajeto entre da loja e obra no mapa

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#175]
Continuação do bug Resposta Orçamento - Incluir endereço da loja no mapa #59

**Comment by raphaelMCarvalho** [comment]
@lucasretondo não entendi a diferença entre essa issue e a #59 . É porque esta é em uma fase diferente do orçamento?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho separei em duas issues para não confundir, mas se for melhor podemos unificar.

**Comment by lucasretondo** [comment]
Não conseguir minimizar o balão dificulta ver a rua exata no mapa.
![image](https://cloud.githubusercontent.com/assets/20990100/21658910/80834754-d2af-11e6-8d14-5e823a1b4321.png)
