### ISSUE TITLE
Criar Orçamento - Ao reenviar duplica o orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#178]
## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Criação do orçamento

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Ao reenviar um orçamento o sistema deveria mudar o status do orçamento e manter a mesma numeração.

## 3. Descrição do que ocorreu

Ao reenviar o orçamento sistema criou um novo orçamento e não excluiu o orçamento anterior.

## 4. Captura de tela

Orçamento 60 e 157.
![image](https://cloud.githubusercontent.com/assets/20990100/18728451/9192cbd4-8023-11e6-91a2-540199951f5d.png)

## 5. Passos para reproduzir a ocorrência

https://drive.google.com/file/d/0B_JJI1HknOluUlp3ZFVNN2NXVWs/view

## 6. Dados envolvidos na ocorrência (e-mails dos usuários)

Usuário: lucas.retondo@gmail.com

**Comment by raphaelMCarvalho** [comment]
@lucasretondo apurando essa issue verificamos que é exatamente o mesmo problema apresentado na issue #155 , sendo diferente apenas o caminho para se deparar com ele. Já estamos trabalhando na correção da issue #155, dessa forma esse bug é duplicado.
