### ISSUE TITLE
Criar Orçamento - Ao salvar duplica o orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#179]
## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Criação do orçamento

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Ao salvar um orçamento o sistema deveria mudar o status do orçamento e manter a mesma numeração.

## 3. Descrição do que ocorreu

Ao salvar o orçamento sistema criou um novo orçamento e não excluiu o orçamento anterior.

## 4. Captura de tela

Orçamento 60 e 159.
![image](https://cloud.githubusercontent.com/assets/20990100/18728728/f13e74d8-8024-11e6-8a4a-e85925a0b7fc.png)

## 5. Passos para reproduzir a ocorrência

https://drive.google.com/file/d/0B_JJI1HknOluUlp3ZFVNN2NXVWs/view

## 6. Dados envolvidos na ocorrência (e-mails dos usuários)

Usuário: lucas.retondo@gmail.com

**Comment by raphaelMCarvalho** [comment]
@lucasretondo no vídeo é selecionado um orçamento com status Reenviar e é solicitado um orçamento, diferente do título da issue, que indica que a ação executada foi salvar o orçamento e então ocorreu duplicata. Você pode fornecer maiores detalhes? A princípio me parece uma issue duplicada em relação à #178

**Comment by lucasretondo** [comment]
@raphaelMCarvalho devo ter postado o vídeo errado, o orçamento duplicou ao solicitar e ao salvar, porém a origem do erro deve ser a mesma. Segue o vídeo correto.

https://drive.google.com/open?id=0B_JJI1HknOluZERTcEdxRmVtMEk

**Comment by raphaelMCarvalho** [comment]
@lucasretondo no início do vídeo há um orçamento com ID 159 e status Salvo. Ao final do vídeo, há o mesmo orçamento de mesma ID, e mesmo status Salvo. Não percebi a duplicação.

**Comment by lucasretondo** [comment]
Ok.
