### ISSUE TITLE
Resposta Orçamento - Para sem categoria marca não é obrigatória

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#180]
## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Responder Orçamento Lojista

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Para materiais sem categoria o preenchimento do campo marca não é obrigatório.

## 3. Descrição do que ocorreu

Apareceu uma mensagem de erro obrigando a preencher a marca.

## 4. Captura de tela

[Insira as imagens aqui]
![image](https://cloud.githubusercontent.com/assets/20990100/18734363/1fe8dea2-804a-11e6-82a5-43c6900039b8.png)

## 5. Passos para reproduzir a ocorrência

[Descreva aqui]

## 6. Dados envolvidos na ocorrência (e-mails dos usuários)

[Descreva aqui]

**Comment by raphaelMCarvalho** [comment]
Issue relacionada à #15

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio Resolvido
