### ISSUE TITLE
Otimização não considera o desconto de meio de pagamento adequadamente

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#183]
# Bug
## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Na otimização dos orçamentos enviados pelos lojistas
## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Que os descontos, fixos por meio de pagamento, sejam considerados na otimização dos preços.
## 3. Descrição do que ocorreu

No formato atual, a otimização do meio do pagamento não está sendo feita adequadamente pois não considera algumas situações de fronteira.
## 4. Captura de tela

Problema de back-end. Não se aplica.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho aparentemente o otimizador de menor custo total esta considerando o descontos e acréscimos, porém a "menor avaliação" e a "menor quantidade de lojistas" não estão considerando os descontos e acréscimos.

https://drive.google.com/file/d/0B_JJI1HknOluY2RLVHl3SW9BRXM/view

Também achei estranho este erro que esta ocorrendo quando eu tento personalizar o orçamento, note que o valor total (última linha) não é calculado. No final de semana eu não lembro de ter tido este problema.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo os otimizadores de menor avaliação e menor quantidade de lojistas estão funcionando conforme a especificação. Esse resultado com anomalia que você está tendo aí, se entendi o que você tentou expressar, é que não estão aparecendo descontos na tabela; se for isso, quase certeza que tem relação com o erro que está aparecendo. Vamos verificar. Não houve modificação nos otimizadores desde sexta-feira.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ok, vou fazer mais alguns testes e qualquer coisa abro uma nova issue depois.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho olha este exemplo com o usuário cliente1@mailinator.com. Como ainda não temos nenhuma avaliação o valor das opções Melhor avaliação deve ser igual ao Menor quantidade, porém na Melhor Avaliação o sistema esta exibindo a opção com a loja Quinta Avenida, apesar o valor os itens serem autos, o desconto é muito grande em dinheiro, assim o valor total fica em R$ 4.035:
![image](https://cloud.githubusercontent.com/assets/20990100/19058870/6cdd6352-89b1-11e6-954d-4e188ea303ee.png)
Já a opção Menor Quantidade esta exibindo o valor de R$ 5.554,56, por que esta selecionando o Parceiro Um, que tem entrega todos os itens e tem o menor custo total sem desconto:
![image](https://cloud.githubusercontent.com/assets/20990100/19058884/97ef7bac-89b1-11e6-8f4e-7640c0130b3a.png)
Isto sugere que o otimizador de menor quantidade não esta considerando os descontos.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho veja este exemplo com o orçamento 359, o otimizador de menor custo total este sugerindo a Primeira Loja com R$ 950:
![image](https://cloud.githubusercontent.com/assets/20990100/19518985/93e51948-95e8-11e6-9a2f-383f606a6010.png)
Enquanto o menor custo é com a loja custo com a Segunda Loja Nova é bem inferior R$ 623:
![image](https://cloud.githubusercontent.com/assets/20990100/19518999/a4a0410e-95e8-11e6-8239-830a0438e429.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho neste outro exemplo com o orçamento 254 o otimizador de menor custo esta vazio:
![image](https://cloud.githubusercontent.com/assets/20990100/19519106/225ed006-95e9-11e6-9e2b-8e0f17935024.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho neste outro exemplo (orçamento 102), os otimizadores de menor custo total e menor quantidade de lojas não deveriam ser iguais?
![image](https://cloud.githubusercontent.com/assets/20990100/19519239/d2927900-95e9-11e6-8647-bdb39977c0e7.png)
![image](https://cloud.githubusercontent.com/assets/20990100/19519244/d7c1d60a-95e9-11e6-82b4-ffc34c3d4088.png)
E mais, ambos não estão selecionando a melhor opção de pagamento em dinheiro:
![image](https://cloud.githubusercontent.com/assets/20990100/19519275/fe217d3c-95e9-11e6-9e68-f1ded185bf8e.png)

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio @lucasretondo Pessoal, como houve alteração no sistema removendo os descontos e acréscimos por forma de pagamento, vou adicionar a label **Para validar** apenas para sinalizar que esta issue deve ser fechada.

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio @lucasretondo Pessoal, nos testes finais identificamos alguns casos ainda pra tratar com a remoção dos descontos, melhor deixar essa issue aberta.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho esta issue acabou ficando muito grande depois de anexarmos tantos exemplos, não sei mais o que devo validar.

O otimizador nas maioria das vezes esta funcionando corretamente, porém ainda existem situações onde ele se perde.

Para organizar melhor vou abrir uma nova issue para cada tipo de erro, acho que fica melhor para controlar e validar, concorda?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Como há as novas issues relativas ao otimizador e não temos mais descontos por tipo de pagamento (assunto desta issue), acredito que possamos fechá-la sem prejuízo às atividades.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho concordo.
