### ISSUE TITLE
Criar Orçamento - Criar um botão que permita limpar todas as informações

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#187]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

[Descreva aqui]

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

[Descreva aqui]

## 3. Captura de tela de como está hoje

[Insira as imagens aqui]

## 4. Captura de tela de como deve ficar após a melhoria (se a descrição detalhada for clara e precisa, esse passo é opcional)

[Insira as imagens aqui]

**Comment by raphaelMCarvalho** [comment]
@lucasretondo não ficou claro pra mim o que devo fazer quando a label é Dúvida

**Comment by lucasretondo** [comment]
@raphaelMCarvalho marquei como dúvida as melhorias que eu julgo menos prioritária, ou seja, estou na dúvida se devemos incluir no MPV ou não. De qualquer forma temos que ter uma noção do esforço.
