### ISSUE TITLE
Cadastro Cliente e Lojista - Criar checkbox no termo de uso para "autorizar e-mail marketing" e "li e acordo" 

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#190]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

[Descreva aqui]

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

[Descreva aqui]

## 3. Captura de tela de como está hoje

[Insira as imagens aqui]

## 4. Captura de tela de como deve ficar após a melhoria (se a descrição detalhada for clara e precisa, esse passo é opcional)

[Insira as imagens aqui]

**Comment by raphaelMCarvalho** [comment]
@lucasretondo acredito que essa melhoria implica também em criar uma área no web app para que o usuário possa posteriormente marcar que sim ou não quanto a receber e-mail marketing, e essa mudança deveria automaticamente implicar no recebimento ou não dessas mensagens. Ou seja, acho que o checkbox seria apenas a ponta, há toda uma feature a ser desenvolvida por trás.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho concordo, mas tratar esta issue depois do MPV...
