### ISSUE TITLE
Regra de validação para informar a marca

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#20]
Não consigo testar a regra que obriga o lojista a preencher a marca, no exemplo a marca esta como obrigatória para todas as categorias:
![image](https://cloud.githubusercontent.com/assets/20990100/17621980/c92c4064-606d-11e6-993c-2162765df801.png)

Também não esta bom o feedback para o usuário de quando marca não foi preenchida. Temos que destacar quais campos precisam ser preenchidos tornando a borda laranja por exemplo:
![image](https://cloud.githubusercontent.com/assets/20990100/17622532/513914de-6071-11e6-8258-8c10c12a89dc.png)

**Comment by raphaelMCarvalho** [comment]
Essa issue já foi cadastrada, é a #15 . Quanto a melhorar o feedback, isso está previsto no layout que recebemos?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo por favor fecha esta issue duplicada. Caso ache necessário, crie uma nova issue de melhoria de feedback.
