### ISSUE TITLE
Meus Orçamentos Lojistas - Não esta exibindo os orçamentos expirados

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#202]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Tabela resumo dos Meus Orçamentos Finalizados.

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Quando o o lojista não responde o orçamento no prazo de 2 horas o status do orçamento muda para Expirado. Este status não é exibido na tabela resumo.

## 3. Captura de tela de como está hoje

[Insira as imagens aqui]

## 4. Captura de tela de como deve ficar após a melhoria (se a descrição detalhada for clara e precisa, esse passo é opcional)

[Insira as imagens aqui]

**Comment by raphaelMCarvalho** [comment]
@lucasretondo acho que faltou preencher os detalhes da issue

**Comment by lucasretondo** [comment]
@raphaelMCarvalho veja se dá para entender agora.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo como não há previsão no layout para os orçamentos expirados, e considerando a issue #127 , de que forma eles devem aparecer? Conforme descrito na issue apontada?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho deve seguir o mesmo layout do orçamento finalizado nos meus orçamentos. Confesso que não estou tão seguro dos benefícios de exibirmos os orçamentos expirados, o que vc acha?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo não sei também se vale a pena. Atualmente o lojista é notificado por e-mail quando um orçamento expirou, a exibição dessa tela seria um complemento, mas não essencial.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vamos deixar esta cara de fora por enquanto...
