### ISSUE TITLE
Resposta Orçamento - Obrigatoriedade de Marca/Origem para item com duas opções de preço

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#203]
# Melhoria
## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

No preenchimento da resposta de uma solicitação orçamento, recebida pelo lojista.
## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Quando o lojista for informar duas opções de preço para um mesmo item, deve ser obrigatório que ele preencha os dados de Marca/Origem para ambas, para que o cliente possa identificar qual a diferença entre ambas as opções
## 3. Captura de tela de como está hoje

Como o lojista vê:
![image](https://cloud.githubusercontent.com/assets/7696307/18882109/4a592548-84b4-11e6-9d57-fd1958bf80aa.png)

Como o cliente vê:
![image](https://cloud.githubusercontent.com/assets/7696307/18882125/574a7b6c-84b4-11e6-8a2a-1af73b5f53d1.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho na minha visão o sistema para aplicando a regra de marca vs. material corretamente e estamos exibindo as mensagem de erro corretamente, porém o feedback pode melhorar.

Assim que o lojista inicia o preenchimento já são exibidas as mensagens de campo faltando no final da tabela...
![image](https://cloud.githubusercontent.com/assets/20990100/19274238/daa61b1e-8fa5-11e6-9334-209acccbbcfd.png)

Porém o campo exato que esta pendente só é exibido após o lojista clicar em enviar....
![image](https://cloud.githubusercontent.com/assets/20990100/19274245/df014256-8fa5-11e6-89fd-1ab166e63dda.png)

Na minha visão temos que escolher entre:
- Exibir as mensagens de erro e os campos pendentes assim que o lojista inicia o preenchimento; ou
- Exibir as mensagens de erro e os campos pendentes somente quando o lojista clicar em finalizar

Da forma esta esta hoje fica confuso, concorda?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho @wespatrocinio temos dois assuntos distintos sendo tratados nesta issue.

O primeiro é o ponto que o Weslley colocou que o sistema não obrigado o lojista a informar a marca quando informa dois preços, mesmo quando o material não obrigado informar a marca. Este ponto continua pendente.
![image](https://cloud.githubusercontent.com/assets/20990100/20191616/6be4643a-a76d-11e6-87d2-aff123027b77.png)
![image](https://cloud.githubusercontent.com/assets/20990100/20191627/77dffdda-a76d-11e6-948d-333d13373eed.png)

O segundo é sobre quando a mensagem de erro é exibida, hoje é exibida assim que o lojista inicia o preenchimento. Não vejo problema ficar assim por enquanto, mas eu prefiro a outra opção "Exibir as mensagens de erro e os campos pendentes somente quando o lojista clicar em finalizar".

**Comment by lucasretondo** [comment]
A regra e obrigar ele a informar a marca quando tem dois preços esta funcionando, porém depois que ele desiste de informar o 2º preço o sistema continua exigindo que ele informe a marca.
![image](https://cloud.githubusercontent.com/assets/20990100/20835019/7277fe6a-b87f-11e6-8319-25d6df280a6b.png)
