### ISSUE TITLE
Criar Orçamento - Exibição dos termos homônimos no autocomplete

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#204]
# Melhoria
## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Na criação de um orçamento, pelo cliente.
## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

O autocomplete deveria carregar o homônimo do produto na lista, quando a digitação corresponde a ele. Por exemplo, ao digitar **tijolo**, o autocomplete carrega os itens **Bloco cerâmico de vedação**. Deveria exibir **Tijolo...**
## 3. Captura de tela de como está hoje

![image](https://cloud.githubusercontent.com/assets/7696307/18882337/2c0f9c92-84b5-11e6-9e13-bff019f3c388.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não esta exibindo a dimensão deste homonimo
![image](https://cloud.githubusercontent.com/assets/20990100/19952412/2bc73548-a14c-11e6-995f-c269e89dcc05.png)
