### ISSUE TITLE
Meu Resumo Lojista - Alteração dos status exibidos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#209]
No Meu Resumo devemos exibir somente os orçamentos e pedidos que dependente de alguma ação do lojista. Assim, na minha opinião, devemos exibir no Meu Resumo somente:
Meus Orçamentos - Pendente
Meus Pedidos - Confirmar entrega (quando estiver próximo do período da entrega), Confirma pagamento e Avaliar cliente

**Comment by raphaelMCarvalho** [comment]
Como solicitado, agora em Meu Resumo o lojista não visualiza os novos pedidos assim que eles chegam, apenas a partir do status Confirmar entrega, passando por Confirmar pagamento e Avaliar cliente.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho marquei toca, esqueci de incluir o Confirmar pedido... neste status o lojista também tem ação, concorda? é muito difícil incluir? desculpe.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Feito

**Comment by lucasretondo** [comment]
@raphaelMCarvalho obrigado.
