### ISSUE TITLE
Resposta Orçamento - Ao enviar uma mensagem os preços informados são apagados

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#215]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Quando o lojista responde um orçamento.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Ao enviar uma dúvida os preços já informados não fossem apagados.

## 3. Descrição do que ocorreu

Ao enviar uma dúvida os preços foram apagados.

## 4. Captura de tela

https://drive.google.com/file/d/0B_JJI1HknOluVFM0blFXbk5yODg/view

## 5. Passos para reproduzir a ocorrência

[Descreva aqui]

## 6. Dados envolvidos na ocorrência (e-mails dos usuários)

Usuário: parceiro2@mailinator.com

**Comment by raphaelMCarvalho** [comment]
Relacionado à issue #168
