### ISSUE TITLE
Cadastro Lojista - Reduzir as casas decimais do desconto e acréscimo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#219]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Quando o lojista esta cadastrando os percentuais de desconto e acréscimos.

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Achei muito legal o layout, mas estou achando exagerado duas casas decimais para desconto e acréscimo, deixar apenas uma casa decimal para mim é o ideal.

## 3. Captura de tela de como está hoje

3:30 do vídeo: https://drive.google.com/file/d/0B_JJI1HknOlubTRQWkVFT04zQ0E/view

## 4. Captura de tela de como deve ficar após a melhoria (se a descrição detalhada for clara e precisa, esse passo é opcional)

[Insira as imagens aqui]

**Comment by raphaelMCarvalho** [comment]
@lucasretondo isso é parte da máscara que foi utilizada, essa library faz validação de percentual; não recomendo a mudança, mas se for importante podemos fazer (talvez não possamos exibir mais utilizando a mesma máscara que importamos no projeto)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho acho muito desconfortável para o lojista digitar duas casas decimais, mas se o esforço for muito alto não vale a pena. Qual o tamanho do esforço?
