### ISSUE TITLE
Resposta Orçamento - Incluir itens e regras no filtro

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#22]
No filtro devemos incluir as categorias "Indisponível" e "Fora do escopo":
![image](https://cloud.githubusercontent.com/assets/20990100/17622159/081512dc-606f-11e6-8d49-7cf31accad26.png)

O filtro deve ser aplicado somente para os itens da opção 1, a opção 2 é opcional, no exemplo abaixo todos os itens da opção 1 foram preenchidos e quando filtro vazios eles continuam aparecendo:
![image](https://cloud.githubusercontent.com/assets/20990100/17622224/5c7008f0-606f-11e6-96fb-6a754d1e5cf7.png)

Ocorreu algum erro na primeira linha, após aplicar o filtro as colunas ficaram deslocadas:
![image](https://cloud.githubusercontent.com/assets/20990100/17622253/7e35351e-606f-11e6-8b36-e208a36faed9.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo este bug é duplicado, refere-se à issue #15 .

**Comment by lucasretondo** [comment]
Mais um exemplo...

![image](https://cloud.githubusercontent.com/assets/20990100/18572280/3411c4ac-7b90-11e6-866c-35aef706c5bc.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18572282/38864e40-7b90-11e6-9105-c0803abd9850.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18572284/3da924d8-7b90-11e6-9221-d9e11783d851.png)
