### ISSUE TITLE
Cadastro Cliente - Melhorar texto das formas de pagamento no cadastro

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#222]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Quando o cliente preenche as formas de pagamento na primeira vez que faz o cadastro.

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

A comunicação não é boa, sugiro excluir substituir o texto "Formas de Pagamento" por "Como você deseja pagar as suas compras"

## 3. Captura de tela de como está hoje

1:03 no vídeo: https://drive.google.com/file/d/0B_JJI1HknOluZ3poWlpIa2t6UXc/view

## 4. Captura de tela de como deve ficar após a melhoria (se a descrição detalhada for clara e precisa, esse passo é opcional)

[Insira as imagens aqui]

**Comment by raphaelMCarvalho** [comment]
@lucasretondo o título diz para melhorar o texto. Na descrição fala-se de excluir. Assumindo que a tarefa seja a descrita no título, qual seria precisamente a melhoria do texto?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho no call realizado ontem decidimos mudar esta issue. Mudei a descrição da issue, veja se ficou mais claro.
