### ISSUE TITLE
Resposta Orçamento - Excluir o feedback dos dados da obra

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#229]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Quando o lojista responde o orçamento.

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Nesta página (1:14) a tabela com os dados o orçamento não tem link, portanto os feedbacks de tornar a linha laranja e incluir link ao passar o mouse induzem o usuário a clicar em algo que não é link. Não devemos exibir nenhum feedback nesta página.

## 3. Captura de tela de como está hoje

1:14 - https://drive.google.com/file/d/0B_JJI1HknOluUkc0LVdTSlZNMVk/view

## 4. Captura de tela de como deve ficar após a melhoria (se a descrição detalhada for clara e precisa, esse passo é opcional)

[Insira as imagens aqui]

**Comment by raphaelMCarvalho** [comment]
@lucasretondo fiquei confuso nessa issue, o título diz uma coisa, mas a descrição detalhada diz outra. Ou a observação na descrição é algo adicional?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho maluquice minha, o título estava errado. Lembrando que esta issue se repete para todas as tabela de dados do cliente, lojista, orçamento e pedido. Sempre que a tabela não tiver link o feedback deve ser excluído.
