### ISSUE TITLE
Não foi possível ouvir o áudio associado à dúvida

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#23]
Não foi possível ouvir o áudio associado à dúvida, pois o botão não dispara nenhuma ação quando clicado.

![image](https://cloud.githubusercontent.com/assets/7696307/17625375/029f0622-607f-11e6-87a1-c5e90a5bb8d7.png)

**Comment by raphaelMCarvalho** [comment]
Bug possivelmente relacionado: https://github.com/PraConstruir/web_app/issues/14#issuecomment-239563892
