### ISSUE TITLE
Orçamento Recebido - Excesso de informações de marca

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#231]
## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Quando o cliente abre um orçamento com o status verificar orçamento

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Hoje o sistema esta exibindo o botão + mesmo para itens sem marca. Além de poluir a tabela induz o cliente a clicar em algo atoa.

## 3. Captura de tela de como está hoje

1:00 - https://drive.google.com/file/d/0B_JJI1HknOludHQ1bTVoMHhScFU/view

## 4. Captura de tela de como deve ficar após a melhoria (se a descrição detalhada for clara e precisa, esse passo é opcional)

Exibir o botão + somente quando existir pelo menos uma marca.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo não entendi a issue, o botão + passou a ser exibido para 1 item quando esse bug foi registrado: #66 .

**Comment by lucasretondo** [comment]
@raphaelMCarvalho O "+" esta sendo exibido para todos os campos, com ou sem marca. Ele deve ser exibido somente para existir marca, caso contrário ele não deve ser exibido.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo entendi, vou checar

**Comment by lucasretondo** [comment]
@raphaelMCarvalho a caixa da marca não desaparece quando o usuário clica em outro lugar, é interessante incluir esta função, concorda?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho na minha visão esta issue foi parcialmente corrigida, atualmente o sistema esta exibindo o + somente para os itens com marca corretamente, porém a caixa de texto não fecha quando o cliente clica fora da caixa e o layout da caixa quando existe somente uma marca esta ruim, veja os exemplos abaixo:

Hoje:
![image](https://cloud.githubusercontent.com/assets/20990100/19275018/a0afd7ee-8fa8-11e6-9724-6f03cf05f96e.png)

Ideal:
![image](https://cloud.githubusercontent.com/assets/20990100/19275027/ae15f3dc-8fa8-11e6-84b6-d04a264e6087.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo o **bug** foi corrigido, conforme solicitado na issue, implementado exatamente com a solução sugerida no comentário https://github.com/PraConstruir/web_app/issues/231#issuecomment-251188497

Se há outros problemas que precisam ser corrigidos ou melhorias que gostaria de ver nessa tela, fique à vontade para criar novas issues.
