### ISSUE TITLE
Geral - Cálculo do tempo de resposta do cliente

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#233]
# Bug
## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

No cálculo do tempo que o cliente tem para verificar o orçamento.
## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Era esperado que o sistema permitisse que o cliente verificasse o orçamento até as 24h do dia 4/out e não 12h como esta reportado no passo a passo abaixo.
## 3. Descrição do que ocorreu

Criei um orçamento no dia 3/out as 22:06 com o usuário cliente1@mailinator.com
![image](https://cloud.githubusercontent.com/assets/20990100/19059922/1e3fd0c8-89ba-11e6-8530-6532e2e415c3.png)
A mensagem confirma que irei receber as respostas até as 10h do dia 4/out - CORRETO
![image](https://cloud.githubusercontent.com/assets/20990100/19059924/267fe2dc-89ba-11e6-8683-0ac58c60cbc0.png)
O Meus Orçamentos diz que o prazo encerra em 11:52, ou seja, as 10h do dia 4/out dado que são 22:07 - CORRETO
![image](https://cloud.githubusercontent.com/assets/20990100/19059936/3576574e-89ba-11e6-9af8-312fba8dcc19.png)
Quando acesso com o parceiro1@mailinator.com o prazo esta CORRETO
![image](https://cloud.githubusercontent.com/assets/20990100/19059950/51bc4968-89ba-11e6-8358-2d2c0dbf0558.png)
Após responder o orçamento o prazo passa para 13:47, ou seja, as 12h do dia 4/out - ERRADO
![image](https://cloud.githubusercontent.com/assets/20990100/19059968/6bb617f4-89ba-11e6-806a-cd5eae4b6cf9.png)
![image](https://cloud.githubusercontent.com/assets/20990100/19059970/6d05104c-89ba-11e6-865a-96c0ad3ec5bf.png)
Quando acesso o cliente1 novamente confirmo que o prazo esta ERRADO
![image](https://cloud.githubusercontent.com/assets/20990100/19059985/7d82cf18-89ba-11e6-9db4-fc6658f3fa24.png)
## 4. Captura de tela

Acima
## 5. Passos para reproduzir a ocorrência

Acima
## 6. Dados envolvidos na ocorrência (e-mails dos usuários)

Acima

**Comment by lucasretondo** [comment]
@raphaelMCarvalho fiz mais dois testes com sobre o cálculos dos SLAs e encontrei mais alguns pontos que julgo errados.

Criei um orçamento as 6:19 (4/out) com o usuário cliente1@mailinator.com e o sistema calculou corretamente o prazo para a resposta em 3:40, ou seja, até as 10h de 4/out. Porém, depois que o orçamento foi respondido pelo primeiro parceiro1, o sistema calculou como para para o cliente analisar o orçamento 11:38, ou seja, pelo cálculo o cliente teria até as 18h de 4/out para analisar o orçamento, isso esta ERRADO, o cliente tem até as 24h de 4/out. Em seguida respondi o orçamento com o parceiro3, após preencher o orçamento e o prazo mudou novamente, só que desta vez reduziu 30 minutos. Segue abaixo a tabela com o passo a passo e as datas e horas que foram feitos as medições.
![image](https://cloud.githubusercontent.com/assets/20990100/19072409/711ac130-8a0b-11e6-94d7-08141a06a99d.png)

Neste segundo exemplo criei um novo orçamento com o usuário cliente3@mailinator.com as 8:09. Já na mensagem de confirmação o prazo aparece 10h, quando o correto seria 10h10. Segui os mesmos passos do exemplo acima e os erros se repetiram, ou seja, primeiro o sistema calculou errado o tempo para o cliente verificar o orçamento (18h quando o correto é 24h) e depois reduziu 30 min (vale a pena lembra que o horário de atendimento dos parceiro3 é diferente do parceiro1).
![image](https://cloud.githubusercontent.com/assets/20990100/19072427/85a57078-8a0b-11e6-929c-dc1b56e61ff1.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo sabe informar a qual requisito se refere a regra que originou a abertura desse bug?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho [RF009] Solicitar Orçamento

![image](https://cloud.githubusercontent.com/assets/20990100/19081167/b32d3fe8-8a2f-11e6-87c0-a8aedce67bbf.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho tem o [RF018] Solicitar Orçamento durante final de semana também...

**Comment by raphaelMCarvalho** [comment]
@lucasretondo a regra que você destacou refere-se ao prazo de retorno do lojista. O bug cadastrado refere-se ao tempo de resposta do cliente.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo revisamos aqui, o prazo do cliente é calculado da seguinte forma: ele tem até o final do período seguinte pra responder. Se o lojista por exemplo tem até as 10h da manhã pra responder um orçamento específico, o cliente teria até o final do período seguinte, ou seja, 18h. Isso está na especificação do Orçamento, na seção referente à validade.

![captura de tela de 2016-10-06 14-49-13](https://cloud.githubusercontent.com/assets/20994342/19163865/14e7917a-8bd4-11e6-8d1f-f2e72276d369.png)

Não é bug.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho no call realizado ontem com o Claudinei ficou alinhado que nós faremos uma revisão completa nos SLAs, vale a pena você falar com ele. Por enquanto vamos deixar esta issue em standy by.

**Comment by raphaelMCarvalho** [comment]
Esta issue será executada em conjunto com o ajuste da #30

**Comment by lucasretondo** [comment]
@raphaelMCarvalho o cálculo do tempo para os lojista responderem o orçamento já esta considerando os feriados nacionais? Hoje por exemplo é feriado e o sistema esta considerando como dia útil.
![image](https://cloud.githubusercontent.com/assets/20990100/19926432/ad618e76-a0db-11e6-8c26-16a0581af63d.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não está considerando, nós ainda não recebemos a lista de feriados que vocês ficaram de fornecer.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ok, pensei que vocês iriamos usar os feriados nacionais e estaduais da api do google. Sem stress, vou providenciar a lista completa e disponibilizo para vocês até 6ª feira. Obrigado

**Comment by lucasretondo** [comment]
O cli2@mailinator criou o orçamento antes das 14h em um dia útil, portanto os lojista tem até as 18h do mesmo dia para responder e ele terá até as 14h do dia útil seguinte para criar os pedidos. No orçamento abaixo o prazo que esta aparecendo para o cliente é de 13h28, sendo o horário atual de 10h30, o cliente tem até as 23h58 para fazer o que? Este prazo não bate com nenhumas das definições acima.

![image](https://cloud.githubusercontent.com/assets/20990100/19928859/98011f90-a0e7-11e6-8226-ba7405dd79df.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho estou homologando o praconstruir.com.br e encontrei este exemplo de cálculo errado do SLA. Solicitei um orçamento as 22h40 e o sistema esta me retornando que a loja tem até amanhã as 18h para responder, quando o correto seria até as 14h.
![image](https://cloud.githubusercontent.com/assets/20990100/20123320/7ece8bca-a605-11e6-8e38-743801128fc4.png)
![image](https://cloud.githubusercontent.com/assets/20990100/20123324/87ca8df0-a605-11e6-8c46-538a4e507769.png)
Não consigo testar em QAS (pdcc.angularlabs...), mas acredito que este erro esteja se repetindo.
Você precisa do usuário e senha?

**Comment by lucasretondo** [comment]
Criei o orçamento 1205 as 15:55 do dia 2/dez (6ª feira)...
![image](https://cloud.githubusercontent.com/assets/20990100/20860246/92998958-b95a-11e6-865f-2b036aa9f3c7.png)
Logo o lojista teria até as 14h do dia 3/dez (Sábado) para responder e o cliente até as 14h do dia 5/dez (2ª feira) para criar os pedidos, porém o prazo esta até as 23:59
![image](https://cloud.githubusercontent.com/assets/20990100/20860250/bf9a3c18-b95a-11e6-8d7e-051bddbc38e8.png)
