### ISSUE TITLE
Criar Orçamento - Não foi possível solicitar orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#237]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Ao solicitar um novo orçamento.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Ao clicar em "solicitar orçamento" era esperado que o orçamento foi enviado para o lojista.

## 3. Descrição do que ocorreu

Travou (botão solicitar orçamento não funciona) e o usuário teve que sair e ao voltar perdeu o orçamento digitado.

## 4. Captura de tela

abaixo

## 5. Passos para reproduzir a ocorrência

Passo a passo da criação do cadastro e alguns orçamento
https://drive.google.com/file/d/0B_JJI1HknOluSks2YWNfVW15S2s/view

Continuação quando ocorre o erro
https://drive.google.com/file/d/0B_JJI1HknOluZEowYTFuYVJsdGM/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não foi possível reproduzir o problema. Ele ainda afeta sua navegação?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho criei mais diversos orçamentos hoje e este erro não surgiu novamente, vamos fechar por falta de provas...
