### ISSUE TITLE
Meus Orçamentos Cliente - Exibi mensagem de erro ao desarquivar

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#239]
# Bug
## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Quando o cliente clica para desarquivar um orçamento.
## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Não exista mensagem de erro.
## 3. Descrição do que ocorreu

Quando o usuário clicou em desarquivar o sistema exibiu uma mensagem de erro, mas desarquivou o orçamento corretamente.
## 4. Captura de tela

Abaixo
## 5. Passos para reproduzir a ocorrência

2:43 - https://drive.google.com/file/d/0B_JJI1HknOluT0R5ckZqTFVBYXc/view

**Comment by lucasretondo** [comment]
A mensagem de erro sumiu, porém também sumiu o botão botão para acessar os orçamentos arquivos que ficava em baixo do quadro Meus orçamentos.
![image](https://cloud.githubusercontent.com/assets/20990100/19913603/50f11fc6-a08b-11e6-94d3-56b6fae33c7d.png)
![image](https://cloud.githubusercontent.com/assets/20990100/19913606/52c3259c-a08b-11e6-9746-0ae57341ae3f.png)

Preferem que eu abra um novo issue ou tratamos neste?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo O botão só é exibido quando há orçamentos arquivados, como você solicitou na issue #78

**Comment by lucasretondo** [comment]
@raphaelMCarvalho perfeito, neste exemplo existe um orçamento arquivado e o botão não esta aparecendo.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Você pode acessar novamente e dar um refresh na página? Se há orçamento arquivado, tenho uma suspeita do problema que pode ter acontecido

**Comment by lucasretondo** [comment]
@raphaelMCarvalho infelizmente não funcionou, veja o vídeo: https://drive.google.com/file/d/0B_JJI1HknOludkYzQ3NaSWphWWM/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Resolvido
