### ISSUE TITLE
Edge - Não é possível mudar o usuário

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#240]
# Bug
## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Ao tentar fazer o login com outro usuário no navegador Edge.
## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Ao fazer o login com outro usuário que o sistema mudasse de usuário.
## 3. Descrição do que ocorreu

Mesmo informando outro e-mail e senha o usuário carregado no navegador é sempre o mesmo.
## 4. Captura de tela

Abaixo.
## 5. Passos para reproduzir a ocorrência

Fiz uma comparação entre o Edge e o Chrome quando eu faço o login de 3 usuários diferentes.
https://drive.google.com/file/d/0B_JJI1HknOlueHh2cUgyTWE4ZXM/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo esse problema continua afetando sua navegação? Testamos no Edge e não conseguimos reproduzir.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho infelizmente sim, acabei de limpar a memória cache e testar novamente e ocorreu o mesmo problema.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Faça o teste novamente por favor, acreditamos que o cache do server pode ter causado essa experiência no seu Edge e que não conseguimos reproduzir.

**Comment by lucasretondo** [comment]
Show...
