### ISSUE TITLE
Orçamento Recebido - Otimizar o orçamento a cada resposta recebida

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#241]
# Bug

~~Este ponto já esta alinhado com o Claudinei. Estou criando a issue apenas para formalizar.~~
## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Cálculo dos otimizadores.
## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

A cada orçamento recebido, o sistema deve recalcular a otimização e armazenar este resultado no banco de dados.
## 3. Descrição do que ocorreu

O usuário fica aguardando otimização a cada vez que entra na tela de orçamentos respondidos.
## 4. Captura de tela

[Insira as imagens aqui]
## 5. Passos para reproduzir a ocorrência

[Descreva aqui]
## 6. Dados envolvidos na ocorrência (e-mails dos usuários)

[Descreva aqui]

**Comment by raphaelMCarvalho** [comment]
@lucasretondo @wespatrocinio O que vocês acharam do desempenho atual?

**Comment by lucasretondo** [comment]
Vou testar com calma essa noite.

---- On Qui, 10 Nov 2016 19:48:53 -0200 notifications@github.com wrote ----

@lucasretondo @wespatrocinio O que vocês acharam do desempenho atual?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho fiz vários testes ontem e a performance e cálculos do otimizador funcionaram muito bem. fiquei feliz. Vou fechar esta issue e as outras do otimizador. Obrigado
