### ISSUE TITLE
Orçamento Salvo - O sistema não permite que existam dois ou mais orçamentos salvos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#242]
# Bug
## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Quando o cliente tenta reenviar um orçamento salvo automaticamente.
## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Que o sistema permitisse que o cliente reenviasse o orçamento salvo.
## 3. Descrição do que ocorreu

O sistema não permite reenviar o orçamento e no exemplo filmado depois que é criada uma nova obra o sistema permitiu enviar o primeiro orçamento, porém na segunda tentativa ocorreu um conflito e em seguida o Meus Orçamento passou a exibir a contagem regressiva.
## 4. Captura de tela

https://drive.google.com/file/d/0B_JJI1HknOluSUpoTVQxdFJsQnM/view
## 5. Passos para reproduzir a ocorrência

Primeiro o cliente solicitou 4 orçamentos distintos em 2 endereços diferentes, nesta etapa o sistema funcionou como esperado.

Estes 4 orçamentos foram respondidos pelos lojista normalmente, porém o cliente não cumpriu o prazo para enviar o pedido, logo o sistema mudou o status destes 4 orçamentos para salvo corretamente.

Porém quando o cliente tenta enviar novamente estes orçamentos salvos automaticamente o sistema trava e exibe as mensagem de erro gravadas no vídeo acima. 

Precisamos checar se esta situação ocorre quando nenhum lojista responde o orçamento e o sistema altera o status para Reenviar automaticamente.
## 6. Dados envolvidos na ocorrência (e-mails dos usuários)

Usuário: cliente1@mailinator.com

**Comment by raphaelMCarvalho** [comment]
Possivelmente relacionado à issue #239

**Comment by raphaelMCarvalho** [comment]
@lucasretondo é preciso limpar o cache do navegador
