### ISSUE TITLE
Resposta Orçamento - Não é possível responder o orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#243]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Quando o lojista tenta responder um orçamento.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Que o orçamento fosso respondido ao preencher todos os itens.

## 3. Descrição do que ocorreu

Não é possível enviar o orçamento devido a regra de pedido mínima não atingida, porém o pedido mínimo no exemplo abaixo é de R$ 100 e todos os itens superam este valor.

## 4. Captura de tela

https://drive.google.com/file/d/0B_JJI1HknOludEowSF9BWVQ0dXM/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo verificamos na semana passada que a validação do pedido mínimo não estava considerando os descontos, no entanto a correção desse problema acabou gerando este bug. O cálculo agora está correto.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ok, vou testar mais tarde, obrigado.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho consegui responder um orçamento com o usuário par1@mailinator.com, se não em engano criei este usuário no domingo. Porém não consegui responder com os usuários parceiro1 e parceiro3@mailinator.com que foram criados no início da semana passada.

https://drive.google.com/file/d/0B_JJI1HknOluZjFta1V3VmdmSEE/view
