### ISSUE TITLE
Orçamento Recebido - Não esta permite mudar a forma de pagamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#244]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Quando o cliente recebe um orçamento respondido por 1 lojista.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Qual mudar a marca ou forma de pagamento o valor total do pedido mudasse.

## 3. Descrição do que ocorreu

Aparece uma mensagens de erro e o valor total do pedido não altera.

## 4. Captura de tela

https://drive.google.com/file/d/0B_JJI1HknOluUjlxZUNxMEFiNDA/view

## 5. Passos para reproduzir a ocorrência

https://drive.google.com/file/d/0B_JJI1HknOluUjlxZUNxMEFiNDA/view

## 6. Dados envolvidos na ocorrência (e-mails dos usuários)

Usuário: cli1@mailinator.com

**Comment by raphaelMCarvalho** [comment]
@lucasretondo não foi possível reproduzir. Esse problema ainda afeta sua navegação?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho este erro não voltou a aparecer...
