### ISSUE TITLE
Layout dúvidas e resposta

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#25]
O layout das páginas do consumidor e parceiro estão muito diferentes do layout enviado.

Layout enviado:
![image](https://cloud.githubusercontent.com/assets/20990100/17634278/3d339d74-60a8-11e6-9028-802f7d787781.png)

Site:
![image](https://cloud.githubusercontent.com/assets/20990100/17634295/53f8946a-60a8-11e6-80dc-87731589318d.png)

**Comment by raphaelMCarvalho** [comment]
Segue o layout recebido. Houve algum engano da sua parte ou da minha?

![screen shot 2016-08-12 at 6 40 17 pm](https://cloud.githubusercontent.com/assets/20994342/17637806/7c40b5ec-60bc-11e6-8aa1-c8ca3b8694a5.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vc tem razão, a versão final ficou a sua. Peço apenas que revise o tamanho das fontes que estão diferente do layout enviado.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo foi possível validar essa issue?
