### ISSUE TITLE
Cadastro Lojista - Colocar o horário de funcionamento com o pedido mínimo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#250]
@raphaelMCarvalho quando "excluirmos" os Descontos e Acréscimo do cadastro do lojista a página ficará somente com o "pedido mínimo"...
![image](https://cloud.githubusercontent.com/assets/20990100/19655915/6514130e-99fc-11e6-936c-672895f0166e.png)
já a página onde esta o "horário de funcionamento" esta apertada...
![image](https://cloud.githubusercontent.com/assets/20990100/19655949/8b8569f2-99fc-11e6-965d-e6935c102840.png)
é fácil transferir o "horário de funcionamento"  para a mesma página do "pedido mínimo"?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo esta issue ainda não estava no radar quando fizemos a alteração dos descontos, e fizemos a proposta de trazer o pedido mínimo pra tela 2, reduzindo assim 1 passo no registro do lojista. Veja se a proposta é interessante, se sim, podemos aperfeiçoar ela ou fazer a adequação que essa issue 250 pede.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Segue a captura de tela de como ficou nossa proposta; acho que a redução de número de passos no cadastro foi uma boa.

![captura de tela de 2016-10-28 15-00-43](https://cloud.githubusercontent.com/assets/20994342/19815157/531ca856-9d20-11e6-9827-e7ded808adb2.png)
