### ISSUE TITLE
Meus Pedidos Lojista - Incluir botão para confirmar pedido detalhada

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#251]
Hoje quando o lojista abre o pedido detalhado, não existe um botão para ele confirmar o pedido, ele tem que voltar e confirmar pelo botão de atalho.

Temos que substituir o botão laranja pelo comando de confirmar o pedido e incluir um botão cinza com o volta, assim mantemos o padrão com o confirmar entrega e pagamento.

https://drive.google.com/file/d/0B_JJI1HknOluSHE5YmpvYkF5bkE/view

**Comment by lucasretondo** [comment]
Ao invés de criar um botão esta direcionando direto para a página confirmar entrega.
![image](https://cloud.githubusercontent.com/assets/20990100/19913541/af995404-a08a-11e6-9d5c-b03ea1fddf50.png)
![image](https://cloud.githubusercontent.com/assets/20990100/19913542/b1cdb4b8-a08a-11e6-96aa-2eb022b016d0.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Acho que houve um mal entendido da sua parte. Veja na captura de tela abaixo que há sim o botão Confirmar pedido quando o lojista clica para ver os detalhes do pedido. Pela sua captura, entendi que você clicou na tela anterior no botão Confirmar pedido, que é o atalho que já confirma e direciona pra confirmação de entrega, como esperado.

![captura de tela de 2016-11-08 11-40-53](https://cloud.githubusercontent.com/assets/20994342/20101242/44f1ed8c-a5a8-11e6-853a-9d0159c0af80.png)

**Comment by lucasretondo** [comment]
Raphael



O botão esta correto, mas esta direcionando para a página errada.



Os meus pedidos estão travados como um todo.


Obrigado









---- On Ter, 08 Nov 2016 11:43:46 -0200Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo Acho que houve um mal entendido da sua parte. Veja na captura de tela abaixo que há sim o botão Confirmar pedido quando o lojista clica para ver os detalhes do pedido. Pela sua captura, entendi que você clicou na tela anterior no botão Confirmar pedido, que é o atalho que já confirma e direciona pra confirmação de entrega, como esperado.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Acredito que você não tenha visualizado a captura de tela que anexei na issue, comprovando que sim, está direcionando para a página planejada.

**Comment by lucasretondo** [comment]
Ok, vou testar novamente e te retorno.

---- On Ter, 08 Nov 2016 11:51:36 -0200 notifications@github.com wrote ----

@lucasretondo Acredito que você não tenha visualizado a captura de tela que anexei na issue, comprovando que sim, está direcionando para a página planejada.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho fiz novos testes a pouco no vídeo https://drive.google.com/file/d/0B_JJI1HknOluQjhzMGY5Q2llLUE/view

Identifiquei os seguintes problemas:
- Meu Pedidos Cliente não abre (1:16)
- Meu Pedidos Lojista não abre (1:51)
- Foi direto para confirmar entrega com mensagem de erro (pulou o confirmar pedido) (1:56)
- Cliente não consegue enviar o pedido (3:00)

Sem contar as diversas vezes que apareceram mensagens de erro.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Revendo seu vídeo diversas vezes, pude verificar que você está errado quando diz que foi direto para confirmar entrega, pulando confirmar pedido; porém seu erro foi induzido por um bug que não exibiu na lista o pedido que você solicitou (o número do seu pedido era 132), exibiu apenas o pedido 110 que já estava no status de confirmar entrega, o qual você confirmou. As mensagens de erro eram referentes a esse bug que citei.

Por favor faça o teste novamente, fizemos um fix no homolog (pdcc.angularlabs.com.br) e limpamos os orçamentos e pedidos. Vamos publicar essa correção em produção, sem alterar os orçamentos e pedidos existentes.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não sei o que aconteceu, agora quando eu acesso pelo Chrome não mudo mais de usuário, igual ocorre com Edge. Veja esse vídeo: https://drive.google.com/file/d/0B_JJI1HknOluR1Y1YkE4ai1US28/view

Estou usando um computador com windows 10 e Chrome Versão 54.0.2840.71 .

As senhas são sempre o e-mail + $$, por exemplo, cli1$$.
