### ISSUE TITLE
Auto Complete - Melhorar Nomes Compostos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#255]
Alguns produtos tem nome composto, ou seja, quando o categorizador separa por espaço acaba criando sub categorias que não fazem sentido, por exemplo, não faz sentido criar a sub-categoria "cimento cp III" para agrupar o "cimento cp III 32" e "cimento cp III 40".

Outro exemplo é o caso a "areia média" abaixo:
![image](https://cloud.githubusercontent.com/assets/20990100/19945758/b2d00ed0-a128-11e6-9af7-e14168f7f08f.png)
![image](https://cloud.githubusercontent.com/assets/20990100/19945775/c047236e-a128-11e6-9986-26d1ee67d9b9.png)

Correto - a Areia não tem subcategoria:
AREIA FINA
AREIA MÉDIA FINA
AREIA MÉDIA
AREIA MÉDIA GROSSA
AREIA GROSSA
AREIA PARA ATERRO
AREIA PARA LEITO FILTRANTE FINA (0,5 A ,07 MM)
AREIA PARA LEITO FILTRANTE MÉDIA (0,7 A 1,0 MM)
AREIA PARA LEITO FILTRANTE GROSSA (0,42 A 1,68 MM)

Criei uma nova coluna no cadastro de materiais para identificar este produtos (Sub = Não):
![image](https://cloud.githubusercontent.com/assets/20990100/19951301/3f1d3e2e-a144-11e6-8ff7-a8a03edb5024.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Você ainda irá detalhar de que forma espera uma melhoria nessa categorização, mas posicionando o status atual: o autocomplete foi atualizado seguindo exatamente a sugestão da issue #74 . O que foi feito na issue para alcançar o resultado esperado e descrito na referida issue foi "categorizar" separando por espaços, sendo cada palavra um item de importância para seguir na árvore.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vou detalhar todas as issues de auto complete conforme acima, funciona? dá para entender?
