### ISSUE TITLE
Inserir item na lista usando ENTER

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#26]
Esta issue está sendo aberta devido ao comentário abaixo:
https://github.com/PraConstruir/web_app/issues/1#issuecomment-239557765

A inserção de um item na lista usando ENTER é um requisito do produto que deve ser implementado.

**Comment by raphaelMCarvalho** [comment]
Funcionando como esperado, os itens continuam sendo inseridos usando o ENTER; esse comportamento não foi modificado na issue mencionada no comentário.

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio por favor valide essa issue e a feche caso a funcionalidade esteja conforme especificado.

**Comment by lucasretondo** [comment]
Já foi corrigido.
