### ISSUE TITLE
Auto Complete - Telha de Alumínio duplicada

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#262]
![image](https://cloud.githubusercontent.com/assets/20990100/19952388/fba8f8ec-a14b-11e6-98a9-1873a5bc5f33.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Antes de tratar estes casos específicos, vale a pena revisar a planilha que foi utilizada pra popular o banco. Na planilha, por exemplo, há alumínio escrito das duas formas, com e sem acento.

![captura de tela de 2016-11-05 17-44-45](https://cloud.githubusercontent.com/assets/20994342/20033088/c4a3f5d2-a37f-11e6-983a-9237f95eed45.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho perfeito, já revisei este caso. Você identificou mais algum?

**Comment by raphaelbluteau** [comment]
@lucasretondo Não identifiquei, vocês teriam que fazer uma revisão completa da planilha mesmo pra garantir, aproveitar que vamos fazer esse novo update.

**Comment by lucasretondo** [comment]
@raphaelbluteau blz, deixa comigo.
