### ISSUE TITLE
Página Inicial - Redes Sociais

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#266]
Apenas para não esquecer de atualizar os links das redes sociais da página inicial. Precisamos também substituir o Twitter pelo Pinterest.

![image](https://cloud.githubusercontent.com/assets/20990100/19983095/c808bbe0-a1ef-11e6-8ade-904d4e5acc23.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo 

- Informar nesta issue os links das redes sociais para inserirmos
- Anexar nesta issue o ícone do Pinterest a ser usado

**Comment by lucasretondo** [comment]
@raphaelMCarvalho neste momento iremos exibir na home e e-mails transacionais somente os ícones do Facebook e YouTube, segue os endereços:
Facebook - https://www.facebook.com/praconstruiroficial/
YouTube - https://www.youtube.com/channel/UC2sPrwTKLIqMdnZczmaNQHQ
