### ISSUE TITLE
Meu Cadastro Lojista - Mensagem de erro e não exibição do mapa

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#267]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Ao consultar o meu cadastro lojista.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Não ocorre-se nenhum erro e que o mapa foi exibido.

## 3. Descrição do que ocorreu

Teve uma mensagem de erro e o mapa não foi exibido.

## 4. Captura de tela

https://drive.google.com/file/d/0B_JJI1HknOluYjJmdGxkQ3ppYXM/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não possuo as credenciais de acesso do usuário em questão, mas a solução apresentada na issue #268 deve resolver este problema.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho funcionou.
