### ISSUE TITLE
Cadastro Lojista - Não exibe o mapa

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#268]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Ao cadastrar um novo lojista.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Que o mapa com o raio médio fosse exibido.

## 3. Descrição do que ocorreu

Não carregou o mapa.

## 4. Captura de tela

https://drive.google.com/file/d/0B_JJI1HknOluOTBBNGdwa3RLSm8/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo @wespatrocinio  Resolvido, no entanto é necessário que vocês criem chaves para a API do Google Maps com a conta do PraConstruir. O mapa não estava sendo exibido porque estava liberado na conta da Angular apenas o domínio angularlabs.com.br . Adicionei temporariamente o praconstruir.com.br até que vocês realizem essa operação e me passem a chave para utilizar.

Se preferirem, me passando o login e senha da conta Google, posso realizar todo o procedimento.

https://developers.google.com/maps/documentation/javascript/get-api-key?hl=pt-BR

**Comment by lucasretondo** [comment]
@raphaelMCarvalho continua não carregando: https://drive.google.com/file/d/0B_JJI1HknOluUzJqTXl4eDFyVTA/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo @wespatrocinio 
![captura de tela de 2016-11-08 14-47-16](https://cloud.githubusercontent.com/assets/20994342/20108176/5134f412-a5c2-11e6-8178-25ac701db117.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo você está testando em http://praconstruir.com.br ?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho sim

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Acabo de testar novamente:

![captura de tela de 2016-11-08 17-01-13](https://cloud.githubusercontent.com/assets/20994342/20112822/f9fe424e-a5d4-11e6-89bf-fd017009482e.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho agora funcionou, bizarro...
