### ISSUE TITLE
Não carrega nova obra

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#271]
Adicionei uma nova obra e após criar sem mensagem de erro o Minhas Obras não adicionou a nova obra na tabela resumo como esperado: https://drive.google.com/file/d/0B_JJI1HknOluNkwzN3RXZkxtNlE/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Relacionado à #272

**Comment by lucasretondo** [comment]
@raphaelMCarvalho agora não esta exibindo o mapa: https://drive.google.com/file/d/0B_JJI1HknOlueVNqSGFiTUdRNzA/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo @wespatrocinio 
https://drive.google.com/file/d/0B3g0Um5tXZKUdWdnRnpkN2RFYmc/view

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vc esta em PRD?

![image](https://cloud.githubusercontent.com/assets/20990100/20150846/09f4e2a0-a69f-11e6-87df-c85058c21658.png)

esse negócio não é de deus...

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Sim, em produção mesmo. Bem estranho, dá a entender que a API do Google Maps não está liberada pro domínio. Removi a permissão do domínio no console do Google e adicionei novamente, tenta testar de novo em uns 15 min.

**Comment by lucasretondo** [comment]
Esta funcionando, isso é coisa do demo...
