### ISSUE TITLE
Não é possível trocar de usuário

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#272]
Sempre carrega o usuário lucas.retondo@gmail.com: https://drive.google.com/file/d/0B_JJI1HknOlud2s1WWh6bzQySEE/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Este é um problema relacionado ao cache. Era, por exemplo, o que estava afetando sua visualização da resolução da issue #251 . Ontem iniciamos algumas configurações de cache no servidor, vamos continuar essas configurações hoje.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Resolvido

**Comment by lucasretondo** [comment]
Funcionou...
