### ISSUE TITLE
Não esta exibindo Meu Resumo e as notificações

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#273]
Estou usando o usuário lojista loj1@mailinator.com, senha loj1$$. Existe um pedido pendente de confirmação
![image](https://cloud.githubusercontent.com/assets/20990100/20158607/799695d6-a6c2-11e6-976e-7a7a23603c0f.png)
porém não esta sendo exibido no Meu Resumo
![image](https://cloud.githubusercontent.com/assets/20990100/20158617/872388b2-a6c2-11e6-9813-d4662f24ec0d.png)
e também não estão sendo exibidas as bolinhas laranjas de notificação no menu lateral.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho em homologação já estava funcionando. O que esta impedindo que funcionasse em produção?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não está funcionando em produção?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Marcando esta issue como melhoria, pois ela especificamente desfaz a melhoria #154

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não é isso, em produção não estava exibindo as notificações do meus pedidos e também não esta exibindo os pedidos pendentes no meu resumo. Não tem nada haver com a issue #154. Ela esta duplicada com a issue #285, ok?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Descrição da issue #154 

> Somar o status confirmar entrega na notificação somente quando o prazo estiver para vencer, caso contrário irá alertar o usuário sem necessidade. **Usar este mesmo critério para exibir ou não o pedido no Meu Resumo.**

Na issue em que estamos, a 273, é solicitado que se altere o critério que havia sido solicitado na issue #154 .

**Comment by lucasretondo** [comment]
@raphaelMCarvalho este critério esta certo e não deve ser mudado, inclusive eu testei em homologação e encerrei a issue #154. Você reabriu não sei pq.

Nesta issue estou reportando que em PRODUÇÃO não estão aparecendo as notificações dos Meus Pedidos e o Meu Resumo esta sempre vazio. O mesmo foi reportado na issue #285 . Sempre em PRODUÇÃO.

Ficou claro? Se preferir falamos por fone.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Acredito que estejamos falando de assuntos diferentes. Vou reformular.

1. A issue #154 foi reaberta e já se encontra fechada, adicionei comentário com a explicação te marcando. (https://github.com/PraConstruir/web_app/issues/154#issuecomment-261308485)

2. A mesma regra que filtra as notificações estava filtrando o que exibir no Meu Resumo, exatamente como você solicitou, está na descrição da issue #154, releia a frase em negrito no comentário anterior. 

3. Esta issue em que estamos, presume que todos os pedidos devem ser exibidos no Meu Resumo, independente se estão próximos ou não do prazo. Inicialmente, assumi que era um bug, mas analisando o histórico de issues percebi que na verdade era uma melhoria, pois estávamos mudando novamente o critério do que exibir ou não no Meu Resumo.

4. Os pedidos não estavam sendo exibidos em Produção até ontem, pois as regras da issue #154 encontravam-se ativas.

5. O que fizemos agora: os pedidos serão exibidos no Meu Resumo, independente do prazo (já que houve mudança no critério apresentado). Quanto à notificação, continuará seguindo a regra estipulada na issue #154.

6. Adicionei o label Development porque a questão afetava os dois embientes, e o ajuste havia sido publicado apenas em Development, não em Produção.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não quero mudar o critério, temos que usar o mesmo critério para exibir a notificação e no Meu Resumo, ou seja, só exibimos quando esta próximo do vencimento.

O que eu estou falando nesta issue e na #285 é que em Produção os status Confirmar Pedido, Confirmar Entrega (próximo do fechamento) e Confirmar Pagamento não estavam sendo exibidos no Meu Resumo e contados na notificação. No homologação isso não estava ocorrendo, ou seja, era um problema exclusivo da Produção.

Vocês identificaram a causa deste erro da Produção e corrigiram na homologação, é isso?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Vou pedir que o Claudinei faça uma chamada pra conversar melhor com você, pois tudo que eu podia esclarecer sobre essa questão já está nos comentários acima e bem frisado.

**Comment by lucasretondo** [comment]
ok
