### ISSUE TITLE
Meus Pedidos - Não funciona e apresenta erro

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#275]
https://drive.google.com/file/d/0B_JJI1HknOluMmVGemJGZURudkU/view

**Comment by lucasretondo** [comment]
@raphaelMCarvalho a mensagem de erro ainda ocorre quando troco de usuário, mesmo limpando o cache do navegador. Sei que vocês ainda estão ajustando as configurações do cache, mas tem algo que eu possa fazer para evitar este erro?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Acredito que dê para contornar abrindo uma nova janela privativa quando for fazer login com outro usuário. Se não conseguir sucesso assim me dê um toque que vemos mais opções.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho o usuário loj1@mailinator.com (loj1$$) não funciona de jeito nenhum. Fiz vários testes no Chrome: 1º como anomimato, 2º como visitante, 3º como uma nova janela, 4º sem fazer o login no Chrome... Os usuários loj2, loj3 e loj4 funcionam normalmente.
