### ISSUE TITLE
Resposta Orçamento - Ordenação dos preços e marcas

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#276]
Qual é o critério utilizado hoje para ordenar os preços e marcas? Na primeiro vez preenchi na opção 1 Tigre e na 2 Amanco, depois quando carregou automático o sistema aparentemente ordenou as três primeiras linhas do menor para maior, porém não aplicou este critério para a 4ª linha.

Esta mudança dificulta a vida do lojista para fazer a manutenção dos preços cadastrados.

![image](https://cloud.githubusercontent.com/assets/20990100/20200483/9f0f1afa-a798-11e6-8873-3fb0bc7c2fde.png)

**Comment by raphaelMCarvalho** [comment]
Veja meu segundo orçamento trazendo do histórico de preços. Após essa captura de tela, eu alterei os valores da primeira linha, colocando o mais caro em primeiro no valor de R$ 13,00 e em segundo o valor R$ 12,00

![captura de tela de 2016-11-29 10-57-25](https://cloud.githubusercontent.com/assets/20994342/20710800/4a641606-b623-11e6-89fc-ceff92315daa.png)

Depois o cliente arquivou o orçamento, desarquivou e solicitou os mesmos itens. O sistema trouxe do histórico os preços, exibindo os valores que intencionalmente eu havia colocado em ordem maior para menor na ordem menor para maior.

![captura de tela de 2016-11-29 11-01-59](https://cloud.githubusercontent.com/assets/20994342/20710803/503a284a-b623-11e6-9874-3955eccea135.png)

O sistema, portanto, ordena do menor para o maior preço.

Nos meus testes não foi possível reproduzir seu caso apresentado na captura de tela, se possível, detalhe as ações até chegar a esse resultado pra que consigamos avaliar.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho é possível mudar este critério? Em algumas situações a ordenação do menor para o maior pode ser ruim para o lojista.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo deve ser ordenado com qual critério?

**Comment by lucasretondo** [comment]
Não deve ser ordenado, deve seguir a ordem informada pelo lojista.



Obrigado









---- On Ter, 29 Nov 2016 11:54:34 -0200 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo deve ser ordenado com qual critério?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Vou discutir essa possibilidade

**Comment by lucasretondo** [comment]
@raphaelMCarvalho além da ordenação das colunas, acho que temos uma oportunidade de melhorar a ordenação das linhas (categorias e produtos). Criei uma nova issue para discutirmos esta possibilidade.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Como solicitado, não está mais havendo ordenação, o lojista verá na ordem que informou.
