### ISSUE TITLE
Paginação - Erro ao mudar de página

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#277]
Erro ao tentar mudar de página, estou achando que não existe a página 3.

https://drive.google.com/file/d/0B_JJI1HknOluSzVab25rMW9jWDg/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Enquanto trabalhávamos na área administrativa, identificamos um bug ao listar pedidos, e o corrigimos na sexta-feira. Acredito que essa issue esteja relacionada ao problema que foi resolvido.
