### ISSUE TITLE
Fale Conosco - As cidades estão erradas

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#278]
Depois de selecionar o estado de São Paulo não aparece as cidades de São Paulo e Piracicaba.
![image](https://cloud.githubusercontent.com/assets/20990100/20242843/472ec9b0-a924-11e6-859e-8d3bd6ffbb6a.png)

**Comment by raphaelMCarvalho** [comment]
As cidades estavam aparecendo, porém não estavam em ordem alfabética

**Comment by lucasretondo** [comment]
Perfeito.
