### ISSUE TITLE
Criar Orçamento - Esta exigindo usuário e senha

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#279]
Após digitar as três primeiras letras o site exige usuário e senha para continuar.
![image](https://cloud.githubusercontent.com/assets/20990100/20242861/0ae21d8a-a925-11e6-9de9-81664550bcf9.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não percebi nenhum diferença no auto complete, já limpei o cache. Tenho que fazer mais alguma ação ou não alteramos o auto complete na build de homologação?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo o autocomplete teremos mais novidades hoje, quanto a esta issue, está resolvida
