### ISSUE TITLE
Fale Conosco - O link do menu lateral esta direcionando para a página errada

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#280]
Ao clicar no item Fale Conosco do menu lateral o usuário é direcionado para a página principal quando deveria abrir o fale conosco.
![image](https://cloud.githubusercontent.com/assets/20990100/20242903/640ddf7e-a926-11e6-9da8-16f14999739d.png)
![image](https://cloud.githubusercontent.com/assets/20990100/20242911/9d620aa2-a926-11e6-85db-4af0d19b812e.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não funcionou, continua direcionando para a home: https://drive.google.com/file/d/0B_JJI1HknOluTXBsMFRDeFJ0Z0U/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Testou em development?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Lembrando que a parte interna requer autenticação, inclusive o Fale conosco

**Comment by raphaelMCarvalho** [comment]
@lucasretondo ![captura de tela de 2016-11-16 07-53-52](https://cloud.githubusercontent.com/assets/20994342/20342507/d909bf84-abd1-11e6-9230-0498d4b3dbdd.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho quando autenticado esta funcionando corretamente. Faz sentido exibir que ele esta autenticado para usar o fale conosco? Se o usuário clicar no Fale Conosco do menu inferior ele pode usar o fale conosco sem estar autenticado. Eu não me lembro de ter visto um site que obrigue o usuário estar autenticado para usar o fale conosco.

**Comment by raphaelbluteau** [comment]
@lucasretondo Exige a autenticação pela facilidade de trazer os campos nome e e-mail já pré preenchidos. Essa facilidade pode ser removida sem problemas.

**Comment by lucasretondo** [comment]
@raphaelbluteau entendi, no call que fizemos a pouco com o Claudinei falamos sobre este e os outros itens que não exigem autenticação dos parceiros (vantagens e como funciona), vale a pena entender com ele, obrigado.

**Comment by raphaelbluteau** [comment]
@lucasretondo Feito
