### ISSUE TITLE
Meus Pedidos - Não esta carregando o responsável pelo recebimento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#282]
O usuário informou que a Rachel é a responsável pelo recebimento dos materiais no cadastro da Obra
![image](https://cloud.githubusercontent.com/assets/20990100/20245634/b425f058-a98c-11e6-98cf-37320dec59d3.png)
![image](https://cloud.githubusercontent.com/assets/20990100/20245637/ba8ce578-a98c-11e6-91be-9bc2491f9634.png)
porém no pedido não aparece a Rachel como responsável pelo recebimento dos materiais
![image](https://cloud.githubusercontent.com/assets/20990100/20245652/f3be2a14-a98c-11e6-9c3f-1601bcaed47a.png)

Tentei em PRD, mas o mesmo erro deve esta ocorrendo na buil de homologação.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Correção publicada em Development

**Comment by lucasretondo** [comment]
Perfeito.
