### ISSUE TITLE
Meu Resumo Lojista - Os pedidos com status confirmar pedido, entrega e pagamento não aparecem no meu Resumo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#285]
![image](https://cloud.githubusercontent.com/assets/20990100/20245709/15a9cf42-a98e-11e6-9319-fd1f0457804c.png)
![image](https://cloud.githubusercontent.com/assets/20990100/20245712/1b88e272-a98e-11e6-8c77-5a98e73a3be5.png)

![image](https://cloud.githubusercontent.com/assets/20990100/20263752/45e3ac3e-aa4f-11e6-8560-dbd6615813a3.png)
![image](https://cloud.githubusercontent.com/assets/20990100/20263758/49db97fc-aa4f-11e6-9a4e-0b42670538d7.png)

![image](https://cloud.githubusercontent.com/assets/20990100/20263851/9e857188-aa4f-11e6-86fa-7d16d580c207.png)
![image](https://cloud.githubusercontent.com/assets/20990100/20263852/a438f258-aa4f-11e6-8f4c-e86fc5c89fc5.png)

**Comment by raphaelMCarvalho** [comment]
Issue duplicada: #273
