### ISSUE TITLE
Página Parceiros - Faltou incluir as figuras na página principal

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#297]
Site:
![image](https://cloud.githubusercontent.com/assets/20990100/20429114/bfc202cc-ad73-11e6-8fab-60d08c8db16b.png)

Layout:
![image](https://cloud.githubusercontent.com/assets/20990100/20429110/bb7cde62-ad73-11e6-8e8e-19a87faef163.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Uma das imagens está fora do container, onde não irá aparecer. A outra está desalinhada em relação ao container. O resultado ficará bem diferente do layout enviado, que está incorreto. Devemos proceder?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vamos deixar fora por enquanto, no futuro revemos a página como um todo, obrigado.
