### ISSUE TITLE
Página Parceiros - Faltou as figuras na página vantagem

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#298]
Site:
![image](https://cloud.githubusercontent.com/assets/20990100/20429132/e58dd648-ad73-11e6-8e83-3195dc5fa83a.png)

Layout:
![image](https://cloud.githubusercontent.com/assets/20990100/20429143/fe02934e-ad73-11e6-8550-e82d54121ede.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Dois pontos:

1. Parte da área onde está esta figura encontra-se fora do container. O container é a área onde se encontra o conteúdo do site, é fácil identificar: basta olhar no cabeçalho, ele começa no logotipo e termina no último item do menu superior. Os layouts enviados infelizmente costumam não respeitar os containers, a gente acaba corrigindo por aqui.

2. No dashboard, o conteúdo das páginas limita-se à área da direita, onde você está vendo os itens de Vantagens. A área onde a figura se encontra não faz parte da página Vantagens, é uma área comum a todo o dashboard do vendedor.

Ou seja: caso queira se usar este imagem, ela deve aparecer em todas as páginas do lojista e ela irá aparecer cortada, não inteira.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho entendi, não precisa implementar, obrigado.
