### ISSUE TITLE
Meus Orçamentos - Não consigo acessar os meus orçamentos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#299]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Ao acessar o Meus Orçamentos como cliente.

## 3. Descrição do que ocorreu

Ao clicar em Meus Orçamentos esta ocorrendo um erro "Internal Server Error".

O orçamento é criado, mas não é possível abrir os meus orçamentos.

## 4. Captura de tela

https://drive.google.com/file/d/0B_JJI1HknOlueDJnOXRlY1hmM2c/view

**Comment by lucasretondo** [comment]
Ocorre este mesmo erro ao abrir um orçamento após a resposta do lojista.
https://drive.google.com/file/d/0B_JJI1HknOlua3JodFhIcXdLaHc/view

Na homologação este erro não ocorre.

**Comment by lucasretondo** [comment]
Testei com outro usuário e o erro não ocorre.

**Comment by raphaelMCarvalho** [comment]
Favor informar o e-mail do usuário em que ocorre o problema.

**Comment by lucasretondo** [comment]
Não esta ocorrendo mais.
