### ISSUE TITLE
Criar Orçamento - Não permitir prazo muito curto

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#30]
o sistema não deve permitir que seja solicitado um orçamento a noite com data de entrega no outro dia de manhã.

![image](https://cloud.githubusercontent.com/assets/20990100/18151519/36cdb7e4-6fc6-11e6-82ef-1a880f6a7691.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo podemos alterar essa regra, sem problemas. Nos requisitos temos:

> Se a solicitação foi feita antes das 10h do dia atual, a data de entrega pode ser
> a mesma da data de criação, com o período sendo obrigatoriamente “Tarde”;
> Caso contrário, a data mínima de entrega será no dia útil seguinte, com o período
> livre;

Desta forma, irei marcar essa issue como melhoria e podemos dar a prioridade que desejarem (esta seria na linha que você chamou de melhoria dentro do escopo).
