### ISSUE TITLE
Dúvida - O cliente não consegue visualizar a dúvida

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#308]
O lojista loj1 enviou um dúvida no orçamento 105, o cliente recebeu o e-mail de notificação abaixo normalmente
![image](https://cloud.githubusercontent.com/assets/20990100/20482970/c97b565a-afd6-11e6-9132-93a36c5de904.png)
mas ao abrir o orçamento 105 ele não consegue visualizar a dúvida, pois o sistema carrega o layout do criar orçamento dado que nem preço foi respondido
![image](https://cloud.githubusercontent.com/assets/20990100/20482990/e4c878ca-afd6-11e6-8137-7ba1aa1aed2a.png)
a regra que direciona o layout deve verificar se existe alguma dúvida para direcionar para a página abaixo
![image](https://cloud.githubusercontent.com/assets/20990100/20483032/1a9b5d46-afd7-11e6-8190-e6c10cccaf15.png)

**Comment by lucasretondo** [comment]
Funcionou, mas o layout esta quebrado.

É muito difícil corrigir?

![image](https://cloud.githubusercontent.com/assets/20990100/20859415/aecbfbde-b945-11e6-84bd-3425c8143eaf.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Limpe o cache do seu navegador e tente novamente, por favor.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho infelizmente não funcionou, continua quebrado.
![image](https://cloud.githubusercontent.com/assets/20990100/20868777/de901d40-ba4a-11e6-9309-4bb14e1291f4.png)
Não quero perder tempo com isso agora, se para corrigir isso precisarmos de mais de 10 min vamos marcar como "não será corrigida" e fechar esta issue.
