### ISSUE TITLE
E-mail Notificação - Dúvida respondida

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#309]
Ao clicar no visualizar do e-mail de notificação de dúvida respondida
![image](https://cloud.githubusercontent.com/assets/20990100/20483394/ed125170-afd8-11e6-84ce-e9f793973ad5.png)
o usuário é direcionado para uma página que não existe
![image](https://cloud.githubusercontent.com/assets/20990100/20483399/f87310e0-afd8-11e6-874c-fe7c1c8836f6.png)

**Comment by lucasretondo** [comment]
Infelizmente ainda esta ocorrendo o mesmo erro: https://drive.google.com/file/d/0B_JJI1HknOluYmg1ck9uWmpyUm8/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo No vídeo não aparece o resultado do clique. Apareceu a mesma página do seu primeiro teste?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho tem razão, o vídeo estava fixo na página. Sim, apareceu a mesmo tela na homologação.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Refiz o teste aqui e está funcionando normalmente. Encaminhei o e-mail do meu teste.

![captura de tela de 2016-11-29 09-37-42](https://cloud.githubusercontent.com/assets/20994342/20708580/afdc8416-b617-11e6-8b86-309066b4cfa7.png)

![captura de tela de 2016-11-29 09-38-03](https://cloud.githubusercontent.com/assets/20994342/20708582/b5981dc0-b617-11e6-8318-d838ccd51bfc.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Identifiquei o problema, acabei confundindo as mensagens

**Comment by lucasretondo** [comment]
Blz.








---- On Ter, 29 Nov 2016 09:46:43 -0200 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo Identifiquei o problema, acabei confundindo as mensagens
