### ISSUE TITLE
Criar Orçamento - Orçamento sem lojas não expira

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#323]
Solicitei um orçamento com o cli1@mailinator.com em um endereço onde não existe lojistas. O sistema exibiu a mensagem corretamente, mas criou um orçamento com status "Aguardando resposta" quando o correto seria "Salvo".
https://drive.google.com/file/d/0B_JJI1HknOlueVBsbjZNOHNUQ2c/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Acredito que este passo não tenha sido especificado. Vamos colocar na pauta.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Quando um orçamento não possuir lojistas, iremos armazenar com o status Salvo, já que não faz sentido ele ficar com o status Aguardando resposta, se a resposta não virá a princípio.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho perfeito...
