### ISSUE TITLE
Criar orçamento - Usar o endereço da obra para carregar feriados municipais

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#324]
Atualmente o sistema esta considerando a cidade do cadastro para carregar os feriados municipais. Para mim o correto é usar a cidade da obras, veja os exemplos abaixo:

Usuário: cli1@mailinator.com, esta considerando o dia 8/dez como feriado, mas a obra é em São Carlos:
![image](https://cloud.githubusercontent.com/assets/20990100/20868209/113d4c62-ba3d-11e6-8736-19020225468f.png)

Usuário: cli2@mailinator.com, não esta considerando o dia 8/dez feriado pq o cadastro esta vazio e a cidade do obra é em Piracicaba, onde é feriado:
![image](https://cloud.githubusercontent.com/assets/20990100/20868217/415e47ca-ba3d-11e6-9dfb-5b8d34164454.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo quanto a essa questão de feriados, aproveitando o ensejo, como você pensa lidar com o fato de que até esse momento da escolha de data o usuário pode não estar autenticado, logo desconhecemos tanto sua cidade de cadastro quanto a cidade da obra?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho para mim enquanto o usuário não é autenticado devemos carregar somente os feriados nacionais. Após ele autenticar (dado que é obrigatório), nós devemos checar se a data selecionada cai em algum feriado estadual ou municipal, caso sim, devemos informar o usuário e obrigá-lo a escolher outra data. Podemos ainda colocar como data de entrega o próxima dia útil, mas acho que é melhor obrigar o usuário a escolher uma nova data. O que vc acha?
