### ISSUE TITLE
Confirmar Entrega Parcial - Esta alterando o status para finalizado mesmo com item com entrega pendente

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#331]
Após confirmar uma entrega parcialmente o sistema alterou o status para "finalizado" quando o correto seria manter o status "confirmar entrega".
https://drive.google.com/file/d/0B_JJI1HknOluV3BXSjZ6c3FwbHM/view

**Comment by raphaelbluteau** [comment]
O que deve acontecer se o lojista não confirmar posteriormente a entrega dos outros itens?

**Comment by lucasretondo** [comment]
Se o lojista confirmou a entrega de todos os itens e o cliente confirmou parcialmente, temos que manter o status do cliente como confirmar entrega e nós vamos ter que entrar em contato com eles para entender o que esta acontecendo, ou seja, temos que ter uma forma de identificar estas situações para depois decidir que nós iremos fazer no sistema.

**Comment by lucasretondo** [comment]
@raphaelbluteau pensando mais um pouco, acho melhor alterar o status do pedido na visão do lojista para "confirmar entrega" e notificar por e-mail quando o cliente confirmar a entrega parcialmente, assim o pedido não sai do radar do lojista. É possível e fácil fazer assim?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Esse fluxo alternativo, como não havia sido previsto de antemão, requer algumas modificações adicionais. É possível e requer horas de trabalho.

**Comment by lucasretondo** [comment]
@raphaelbluteau vamos deixar este fluxo alternativo para depois, por enquanto vamos seguir com o fluxo atual.
