### ISSUE TITLE
Avaliação lojista

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#34]
Tenho uma avaliação pendente...

![image](https://cloud.githubusercontent.com/assets/20990100/18152018/4e5b36ae-6fc9-11e6-9787-e9ab922a3c0e.png)

mas quando eu clico vai para a tela errada (abaixo) e com erro...

![image](https://cloud.githubusercontent.com/assets/20990100/18152037/6cf73f2c-6fc9-11e6-8f7b-a0b11af65c82.png)

**Comment by raphaelMCarvalho** [comment]
Resolvido.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo foi possível validar essa issue? Em caso positivo, vamos fechando as issues resolvidas.
