### ISSUE TITLE
Criar Orçamento - Esta carregando o período de entrega, mas não a data quando o orçamento esta com status salvo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#344]
Esta exibindo do período da entrega, porém não esta exibindo a data quando abre um orçamento com status salvo: https://drive.google.com/file/d/0B_JJI1HknOlueUdsOTFWX3Q5NFk/view

Tenho a impressão que isso ocorre somente quando a data de entrega salva não atende o período de entrega mínimo, pois quando carregamos um orçamento salvo onde a data de entrega ainda é válida este erro não ocorre.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não é um erro, a data não é carregada intencionalmente. Isso é feito para que o cliente selecione uma nova data, tendo em vista que a anterior não é mais válida. O período não deveria aparecer também, fizemos um ajuste para que ele seja limpo usando o mesmo critério que a data de entrega.
