### ISSUE TITLE
Resposta Orçamento - Ordenação das categorias de produtos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#345]
Qual é o critério utilizado hoje para ordenar as categorias de produtos? Em algumas situação os produtos sem categoria estão aparecendo no começo quando o ideal seria ser o último: 
![image](https://cloud.githubusercontent.com/assets/20990100/21658555/3e52d0bc-d2ae-11e6-8a1f-1d3f007d886b.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho o que foi alterado? o que eu devo testar?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo As categorias agora estão em ordem alfabética, sendo que o "Sem categoria" sempre aparecerá por último, quando houver.
