### ISSUE TITLE
Resposta Orçamento - Ordenação dos produtos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#346]
Qual é o critério utilizado atualmente para ordenar os produtos? Em algumas situações a ordenação atual dificulta o preenchimento e análise do orçamento. O ideal seria utilizar ordem do cadastro, mas por enquanto podemos usar a ordem alfabética.

No exemplo abaixo o bloco cerâmico aparece no começo e no final:
![image](https://cloud.githubusercontent.com/assets/20990100/21658693/b71374ca-d2ae-11e6-97f4-b105d112d645.png)

Já neste exemplo o rejunte fica separado:
![image](https://cloud.githubusercontent.com/assets/20990100/21658710/c43b66d0-d2ae-11e6-97ce-d00d20939b01.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho o que foi alterado? o que eu devo testar?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Foi realizada a alteração solicitada:

>  por enquanto podemos usar a ordem alfabética
