### ISSUE TITLE
Página orçamento finalizado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#35]
A página do orçamento finalizado detalhado esta errada.

Meus orçamentos
![image](https://cloud.githubusercontent.com/assets/20990100/18153144/f5dc0d9c-6fd1-11e6-828b-1d75eda29de1.png)

Orçamento detalhado
![image](https://cloud.githubusercontent.com/assets/20990100/18153159/065a82c0-6fd2-11e6-9c42-f2152e838169.png)

**Comment by raphaelMCarvalho** [comment]
Resolvido.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo foi possível validar essa issue? Em caso positivo, vamos fechando as issues resolvidas.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho continua errado...

![image](https://cloud.githubusercontent.com/assets/20990100/18459529/b40e5870-7940-11e6-9429-fa6606c1ed95.png)
