### ISSUE TITLE
Criar Orçamento - Permite solicitar entrega com 3 períodos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#354]
Em 12/jan é feriado em Piracicaba, logo ao solicitar um orçamento no dia 10/jan após as 14h o sistema deveria permitir que a entrega mínima seria dia 13/jan a tarde. Hoje ele permite a entrega no dia 13//jan de manhã. Obs. este erro ocorre somente para os orçamentos salvos.
![image](https://cloud.githubusercontent.com/assets/20990100/21816355/13d1e2e0-d747-11e6-9831-17b9b4f58d10.png)

**Comment by raphaelMCarvalho** [comment]
Issue duplicada #350

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ok, vou fechar essa.
