### ISSUE TITLE
Meus Orçamento Expirados Lojista - Não é possível acessar a página

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#360]
Esta ocorrendo um erro que impede que o usuário acessar a página de orçamentos expirados.
![image](https://cloud.githubusercontent.com/assets/20990100/21931502/f059a846-d982-11e6-9cc5-eaeac4d110ea.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Você lembra qual o e-mail do lojista que usou nessa tela?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo De qualquer forma, acredito que esta issue esteja resolvida, pois suspeito que esteja relacionada à issue #361 que já foi corrigida.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho este erro ocorreu com todos os usuários: loj1@mailinator.com, loj2@mailinator.com, loj3@mailinator.com,... e assim por diante...

Vamos marcar para validar, se o erro persistir eu te posiciono. Obrigado
