### ISSUE TITLE
Meus Orçamentos Cliente - Não é possível acessar um o cli4

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#361]
Não é possível abrir a página Meus Orçamentos com o usuário cli4@mailinator.com devido ao erro Internal Server Error. Com outros usuários este erro não ocorre.

https://drive.google.com/file/d/0B_JJI1HknOludWRRTE84bFU1d3c/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não tenho permissão para adicionar a label 'Para validar', mas fizemos a correção em um dado inválido num dos orçamentos do cliente cli4@mailinator.com.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Blz, eu marquei para validar. 

Você conseguia adicionar labels antes, não? Mudou o seu perfil?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Tinha dado um problema do meu lado para visualizar as issues, daí eu saí do projeto e o Weslley me convidou de volta, imagino que precise settar alguma permissão novamente.
