### ISSUE TITLE
Ajuda - Link errado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#362]
Não tinha visto isso antes, mas ao invés de aparecer o e-mail, esta aparecendo este Jon Doe.
![image](https://cloud.githubusercontent.com/assets/20990100/22355586/8f34350a-e412-11e6-8aab-aca0de8d5bae.png)
![image](https://cloud.githubusercontent.com/assets/20990100/22355597/a500f828-e412-11e6-909a-fdae69be0cff.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Isso é conteúdo, nada a ser feito no desenvolvimento. Basta enviar uma nova versão do json de Ajuda para substituirmos. Revisamos no repositório e esse Jon Doe não existia até a última versão do arquivo que recebemos.
