### ISSUE TITLE
Edge - Meus Pedidos Lojista - Transformou CPF e Celular em link

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#364]
Utilizando o navegador Edge o CPF e Celular dos Meus Pedidos do Lojista esta como link.
![image](https://cloud.githubusercontent.com/assets/20990100/22355905/b385dbfa-e414-11e6-91b2-631f47f54970.png)
ao clicar no CPF
![image](https://cloud.githubusercontent.com/assets/20990100/22355909/b8338c9c-e414-11e6-8af4-c0b38870e055.png)
ao clicar no Celular
![image](https://cloud.githubusercontent.com/assets/20990100/22355915/bf85db4e-e414-11e6-8159-74ed709280ce.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Irá ao ar amanhã
