### ISSUE TITLE
Edge - Avaliação Comprador - Estrelas cortadas

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#365]
Utilizando o navegador Edge as estrelas da avaliação esta cortada...

Edge
![image](https://cloud.githubusercontent.com/assets/20990100/22356057/a1a8e2f0-e415-11e6-8331-67d7625b75fe.png)

Chrome
![image](https://cloud.githubusercontent.com/assets/20990100/22356076/c4a26416-e415-11e6-82c4-004ed6f84d87.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Irá ao ar amanhã
