### ISSUE TITLE
Meu Cadastro Lojista

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#38]
A página "Meu cadastro" o usuário pdcc.parceiro1@mailinator.com esta vazio.

![image](https://cloud.githubusercontent.com/assets/20990100/18153399/8a6496d6-6fd3-11e6-849c-745158c03c89.png)

**Comment by raphaelMCarvalho** [comment]
Resolvido.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo foi possível validar essa issue? Em caso positivo, vamos fechando as issues resolvidas.
