### ISSUE TITLE
ADM - Não estão sendo exibidas todas as mensagens

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#382]
Não estão sendo exibidas todas as mensagens, exemplo orçamento 202 abaixo:

ADM:
![image](https://cloud.githubusercontent.com/assets/20990100/22592982/7d3ac05c-ea03-11e6-8561-42f4a9b03028.png)

Visão Lojista:
![image](https://cloud.githubusercontent.com/assets/20990100/22592984/7f11657a-ea03-11e6-82e1-149e7ca58ec3.png)
![image](https://cloud.githubusercontent.com/assets/20990100/22592985/816e59b8-ea03-11e6-90ac-d6df7d2f804f.png)
![image](https://cloud.githubusercontent.com/assets/20990100/22592988/82f97dbc-ea03-11e6-94b9-b3e92c33d88e.png)
![Uploading image.png…]()

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não sei se foram adicionadas todas as capturas de tela na issue (pra mim apareceu um "Uploading image.png", mas se entendi, não foi encontrada a mensagem na visão de administrador, é isso? Se for isso, ela está sendo listada sim, conforme captura de tela, último item:

![screenshot_20170203_132559](https://cloud.githubusercontent.com/assets/20994342/22596906/9dea29b2-ea14-11e6-8154-335ce0f2a0cb.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho estranho, para mim aparecem somente 4 mensagens...

![image](https://cloud.githubusercontent.com/assets/20990100/22597841/69588848-ea18-11e6-90a3-c440606ac650.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Tenho a impressão que é porque o meu estava filtrando por Orçamentos, e o seu por Comissões. Troca aí pra ver se aparece a lista completa.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vc tem razão, estou me sentindo um asno... obrigado...
