### ISSUE TITLE
ADM - Não permite cancelar um orçamento solicitado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#385]
Não é possível cancelar um orçamento solicitado pelo cliente (status “Aguardando resposta” ou “Verificar orçamento”).

Situações: o cliente esqueceu de incluir algum item, ou errou data de entrega, ou preencheu errado a forma de pagamento...

![image](https://cloud.githubusercontent.com/assets/20990100/22854228/db9aee44-f050-11e6-9b5c-3ddd47854e14.png)
![image](https://cloud.githubusercontent.com/assets/20990100/22854230/dd64ff80-f050-11e6-9bcc-799f9770a2cf.png)

**Comment by raphaelMCarvalho** [comment]
O admin agora pode arquivar orçamentos.
