### ISSUE TITLE
Chat - Não esta funcionando

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#388]
O chat não esta funcionando...
chrome-extension://mmeijimgabbpbgpdklnllpncmdofkcpn/app.html#/files/698f0675-ec61-4081-ya74-1486a9c8ee33

**Comment by raphaelMCarvalho** [comment]
@lucasretondo A princípio analisando os logs, não vemos nenhum problema do nosso lado (nós apenas inserimos o código recebido). Como o site apenas consome a API desse serviço, não temos como avaliar onde estaria o problema, não temos nenhum acesso a registros do serviço. Verifique no painel do serviço contratado se é necessário gerar uma nova versão do código para inserirmos novamente ou abra um ticket com o suporte da empresa e nos comunique posteriormente.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vou verificar com a equipe do TomTicket, obrigado.
