### ISSUE TITLE
Seja um representante - Padronizar posição texto

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#389]
Atual:
![image](https://cloud.githubusercontent.com/assets/20990100/23137502/1ea6c258-f781-11e6-9815-2754c71bdb72.png)

Desejado:
![image](https://cloud.githubusercontent.com/assets/20990100/23137523/354753d8-f781-11e6-9c59-1fdcb3c75e8f.png)

**Comment by raphaelMCarvalho** [comment]
Publicado na homolog.
