### ISSUE TITLE
Ordem tabela resumo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#39]
As tabelas resumos não estão seguindo a ordenação especificadas. Revisar todas as tabelas resumo.

![image](https://cloud.githubusercontent.com/assets/20990100/18153462/e7bcff58-6fd3-11e6-9ad2-543a0751effd.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo temos a correção em mãos, porém foi necessário realizar uma mudança nos status que fará com que pedidos atuais fiquem com status trocados após o update (poderíamos scriptar para fazer esse upgrade, mas como não estamos em produção, a maneira mais rápida seria remover todos os pedidos e orçamentos). Para não atrapalhar seus testes e validação de hoje à noite, vou deixar para subir esse update amanhã cedo.

**Comment by lucasretondo** [comment]
Não foi resolvido.
![image](https://cloud.githubusercontent.com/assets/20990100/18610432/acfaebec-7cf2-11e6-816e-54393edcccfa.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo a ordem já havia sido corrigida, no entanto restava tratar casos específicos de fluxo de confirmação de pedido que poderiam trazer resultados como na captura de tela que foi exibida
