### ISSUE TITLE
Impossibilidade de inserir item em um Orçamento com status "Salvo" cujos itens foram todos excluídos

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#4]
Ao pegar um orçamento que estava com status "Salvo" e excluir todos os itens, não é possível inserir novos itens para dar prosseguimento ao processo do Orçamento.

Versão do Chrome: 51.0.2704.103 m

![image](https://cloud.githubusercontent.com/assets/7696307/17610817/62e2d7be-6018-11e6-8fcd-09cef377fcae.png)

**Comment by raphaelMCarvalho** [comment]
Realizamos testes aqui e as ações ocorreram normalmente, não foi possível reproduzir esse problema. Você pode nos fornecer o passo a passo com detalhes?
