### ISSUE TITLE
Erro no orçamento recebido

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#40]
Não estou conseguindo analisar os orçamentos recebidos pelo usuário lucas.retondo@gmail.com.
![image](https://cloud.githubusercontent.com/assets/20990100/18153499/4336b2e8-6fd4-11e6-82d2-665abf2c376d.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18153502/50020eaa-6fd4-11e6-8378-476b9b48617c.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo você poderia testar novamente? Acreditamos que este problema tenha sido resolvido com os updates da última semana, mas não tenho como confirmar sem acessar com sua conta.
