### ISSUE TITLE
Edge - menu lateral - botões habilitados para usuário sem login

### ISSUE THREAD

**Issue by gustavosouza1** [PraConstruir/web_app#401]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Criação do orçamento
## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Era esperado que os botões laterais estivessem desabilitados para usuários não autenticados 

## 3. Descrição do que ocorreu

Todos os botões estão habilitados

## 4. Captura de tela

![menu lateral](https://cloud.githubusercontent.com/assets/25325792/24002189/d96ab9f8-0a3e-11e7-9794-d7922c54478a.JPG)

## 5. Passos para reproduzir a ocorrência

Acesse o menu "Criar orçamento" sem ter efetuado login

**Comment by raphaelMCarvalho** [comment]
@gustavosouza1 Melhor alinhar com o @lucasretondo pois o acesso público a essa tela "Criar orçamento" foi habilitado a pedido dele. Todos os outros itens que não tem acesso público encaminham o usuário à tela de login.

**Comment by lucasretondo** [comment]
@gustavosouza1 a tela acima é o Chrome? O @raphaelMCarvalho esta certo, "Criar Orçamento" deve ficar sempre habilitado.
Eu entendi no nosso bate papo ontem que no Edge todos os itens estavam habilitados, mas direcionando para o login, é isso mesmo? Você pode anexar a tela?

**Comment by gustavosouza1** [comment]
Exatamente lucas, todos eles estão habilitados, não apenas o criar orçamento. No print ele aparece cinza mas é possível clicar nele, ao clicar eles direcionam para o login (todos eles).

**Comment by lucasretondo** [comment]
@gustavosouza1 e @raphaelMCarvalho desculpem, eu causei a confusão. Não é um bug, entendi que os itens não apareciam cinza.

Porém, de fato o comportamento são diferentes, enquanto no Chrome os itens aparecem cinza como texto, no Edge eles estão cinza, mas o usuário consegue clicar e ir para a página de login.

Acho o comportamento do Edge mais interessante, mas não sei se é uma funcionalidade do navegador ou do front-end. @raphaelMCarvalho você sabe?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Ajustamos da forma desejada, agora o clique nos itens de menu que estão em cinza encaminham para o login, independente do navegador

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ficou ótimo, obrigado. @gustavosouza1 o que vc achou? Podemos validar e depois fechar a issue?

**Comment by gustavosouza1** [comment]
@raphaelMCarvalho @lucasretondo ótimo, perfeito.
