### ISSUE TITLE
Edge - Criar orçamento - erro ao alterar quantidade com seta do teclado

### ISSUE THREAD

**Issue by gustavosouza1** [PraConstruir/web_app#402]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Criação do orçamento

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Era esperado que a quantidade do material fosse alterada com a seta do teclado 

## 3. Descrição do que ocorreu

Ao aumentar ou diminuir a quantidade com o teclado os únicos números que aparecem são 5 e -1

## 4. Captura de tela

![erro quantidade](https://cloud.githubusercontent.com/assets/25325792/24002403/634d5892-0a3f-11e7-8216-ab28f4acaee3.JPG)

## 5. Passos para reproduzir a ocorrência

Acesse "Criar orçamento"

**Comment by raphaelMCarvalho** [comment]
Na issue #211  foi solicitado que fossem removidas as setas do campo para aumentar ou reduzir a quantidade, indicando que a única inserção desejada era do usuário digitando. É preciso discutir se é realmente esperado que haja algum tipo de inserção além da digitação dos valores numéricos para então partir daí o ajuste que for decidido.

**Comment by gustavosouza1** [comment]
Entendi Raphael, mas notei que nesse caso elas funcionam apenas com esses dois números

**Comment by raphaelMCarvalho** [comment]
@lucasretondo @gustavosouza1 A função de ao utilizar as setas do teclado aumentar ou diminuir a quantidade do campo numérico é implementada pelo navegador, não foi implementada por nós no projeto (tendo inclusive em vista a issue #211). No caso do Chrome, por exemplo, isso passou a ser um comportamento padrão nas últimas atualizações que a Google fez. No caso do Edge, essa função aparentemente não foi implementada pela Microsoft.

Dessa forma não há nada a ser feito quanto a essa issue no momento, podendo ser fechada.

Caso seja de interesse que ocorra essa inserção usando setas do teclado, podemos discutir futuramente a implementação disso no projeto, já que não é uma função implementada em todos os navegadores por padrão.
