### ISSUE TITLE
Edge - Criar Orçamento - permite números decimais 

### ISSUE THREAD

**Issue by gustavosouza1** [PraConstruir/web_app#404]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Criação do orçamento 

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Era esperado que só fossem aceitos números inteiros 

## 3. Descrição do que ocorreu

aceita números decimais 

## 4. Captura de tela

![numeros decimais](https://cloud.githubusercontent.com/assets/25325792/24002965/e08c3638-0a40-11e7-922f-3d98d0d291d8.JPG)

## 5. Passos para reproduzir a ocorrência

Acessar o link criar orçamento

**Comment by lucasretondo** [comment]
@gustavosouza1 você consegue validar esta issue na 2ª feira de manhã? Obrigado

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Vi que agora o sistema deixa o campo quantidade vermelho, mas a mensagem continua de campo obrigatório. Podemos mudar a mensagem para "A quantidade deve ser um número inteiro" ou algo do tipo?

![image](https://cloud.githubusercontent.com/assets/20990100/25010402/6c226b9e-2040-11e7-90ab-d191c3d90023.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Subimos uma atualização dessa mensagem. Como o layout proposto dificulta a exibição de múltiplas mensagens de erro de validação, ela precisa ser mais genérica pra atender ao mesmo tempo o caso de dado obrigatório que não foi preenchido e o caso de valor inválido (valor 0).

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Ficou ótimo, obrigado.
