### ISSUE TITLE
Explorer - Não é possível mudar o usuário

### ISSUE THREAD

**Issue by gustavosouza1** [PraConstruir/web_app#407]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Ao tentar fazer o login com outro usuário no navegador Explorer.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Ao fazer o login com outro usuário que o sistema mudasse de usuário.

## 3. Descrição do que ocorreu

Mesmo informando outro e-mail e senha o usuário carregado no navegador é sempre o mesmo.

## 4. Captura de tela

abaixo

## 5. Passos para reproduzir a ocorrência

https://drive.google.com/file/d/0B0iJD-5QJtCzVXItYXNfakhpWmc/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Tentamos reproduzir essa issue em 3 computadores diferentes e o funcionamento ocorreu normalmente. Você tem como fazer o teste no seu também aí?

**Comment by lucasretondo** [comment]
Já estava corrigida, o Gustavo que esqueceu de fechar, desculpe.
