### ISSUE TITLE
Resposta Orçamento - Permite responder um item com valor zero

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#417]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Quando o lojista responde o orçamento.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

O sistema não deveria permitir o lojista responder com valor zero.

## 3. Descrição do que ocorreu

O sistema permite que ele responda com valor zero desde que informe a marca.

## 4. Captura de tela

![image](https://cloud.githubusercontent.com/assets/20990100/24960055/f2294298-1f6a-11e7-88d7-44f4397ab1bc.png)

![image](https://cloud.githubusercontent.com/assets/20990100/24960065/fd373bd6-1f6a-11e7-9f3d-4f045c34de11.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo No momento da especificação de requisitos, não foi levantada a hipótese de implementar essa regra, especificamente não permitir respostas com valor igual a 0. Como não havia essa regra, deixamos aberto, levando em consideração que um lojista poderia oferecer algum produto de brinde dependendo do valor da compra. Podemos implementar essa regra agora, impedindo respostas com valor 0.

Desta forma, esta issue não se enquadra na label bug, pois não havia especificação nesse sentido e também não é um erro de sistema, seguindo-se o fluxo normalmente.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho blz, obrigado.

**Comment by lucasretondo** [comment]
Acabei de ver mais um caso onde o lojista conseguiu responder com valor zero, é o orçamento 456 da Produção.

![image](https://cloud.githubusercontent.com/assets/20990100/25674130/26ee81cc-3010-11e7-9c12-4d39309ef8ca.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo O ajuste se encontra publicado apenas na homolog, visto que o pacote de ajustes ainda não foi completamente validado (ainda há issues "para validar"). Fechado esse ciclo, ela será publicada em produção; sendo assim, não há a necessidade de reabrir a issue, ela já se encontra resolvida.

![screenshot](https://cloud.githubusercontent.com/assets/20994342/25674870/d6d173d6-3012-11e7-9174-e3f48552c96c.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Por ser um hotfix já não deveria estar em produção tb?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não se a issue foi resolvida há vários dias e você só adicionou a label Hotfix há pouco mais de 30 minutos, conforme captura de tela demonstrando o histórico

![screenshot_20170503_152507](https://cloud.githubusercontent.com/assets/20994342/25675488/020577b2-3015-11e7-8818-aae96d181713.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho marquei toca na criação da issue, a primeira vez que identifiquei foi em produção e mandei para o Claudinei pelo whatsapp, depois confirmei em homolog e abri a issue, mas sempre foi tratado como Hotfix. E mais, se não me engano nesta época não tínhamos ainda a label "Hotfix".

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Minha sugestão é que a gente avance na validação dos itens com "Para validar" que estejam abertos até o momento, daí publicamos em produção até esse ponto. O que acha?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho concordo, vou validar hoje a noite tudo e amanhã cedo fazemos o deploy, ok?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Estava conversando agora há pouco com o Claudinei e vamos conseguir abrir esse caso especial e publicar o hotfix daqui a pouco, já está na linha; vamos apenas tomar um cuidado extra no deploy em produção. Sendo assim, você pode seguir o ritmo normal de validação.

**Comment by lucasretondo** [comment]
Ok, obrigado.









---- On Qua, 03 mai 2017 15:58:02 -0300 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo Estava conversando agora há pouco com o Claudinei e vamos conseguir abrir esse caso especial e publicar o hotfix daqui a pouco, já está na linha; vamos apenas tomar um cuidado extra no deploy em produção. Sendo assim, você pode seguir o ritmo normal de validação.
