### ISSUE TITLE
Mensagens - Incluir o nome da loja que mandou as mensagens

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#418]
Colocar o nome da loja que enviou a mensagem:
![image](https://cloud.githubusercontent.com/assets/20990100/25015395/fa8f51ec-2051-11e7-8d88-9c455b38fb9d.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Apenas para confirmar, durante as discussões na fase de especificação, foi definido que não haveria identificação dos lojistas na troca de mensagens, era um pedido explícito. Caso a gente agora identifique o lojista nas mensagens, a plataforma estará aberta aos riscos que haviam sido discutidos à época. Converse com o Claudinei a respeito desses riscos e depois me confirme por favor.
