### ISSUE TITLE
E-mail de notificação - Esta multiplicando a quantidade de e-mails

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#419]
Esta sendo enviado um e-mail de notificação para cada lojista quando o correto é enviar somente um e-mail de notificação.

![image](https://cloud.githubusercontent.com/assets/20990100/25024235/78324660-2073-11e7-8f65-9151b44adafd.png)
![image](https://cloud.githubusercontent.com/assets/20990100/25024246/7e10b238-2073-11e7-9ef7-533d4f7320f4.png)
![image](https://cloud.githubusercontent.com/assets/20990100/25024264/8e215f1a-2073-11e7-99a2-93129ed8e28d.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Resolvemos a questão dos e-mails e já está publicado o hotfix em produção.
