### ISSUE TITLE
Valor total vazio

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#42]
Não esta informando o valor total.

![image](https://cloud.githubusercontent.com/assets/20990100/18189297/f2a406de-708f-11e6-9dac-63a162d32ddb.png)

**Comment by raphaelMCarvalho** [comment]
Este orçamento estava em qual status?

**Comment by lucasretondo** [comment]
Continua com o bug...
![image](https://cloud.githubusercontent.com/assets/20990100/18459482/3c3f3292-7940-11e6-8d25-b7eaf2516588.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo este bug será solucionado com a resolução da issue #35
