### ISSUE TITLE
Meu Resumo e Meus Orçamentos - Ordenar do menor para o maior prazo de encerramento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#420]
Atualmente o sistema não esta ordenando os orçamentos do Meu Resumo e Meus Orçamentos do menor para o maior prazo de encerramento.

![image](https://cloud.githubusercontent.com/assets/20990100/25103104/a044e1fa-2391-11e7-83db-ba095e187bc9.png)

![image](https://cloud.githubusercontent.com/assets/20990100/25103109/a6c7e900-2391-11e7-9894-6f736a92d0f9.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo publicado na homologação
