### ISSUE TITLE
Criar Orçamento - Não preenche automático quando só existe uma unidade

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#421]
Antes o preenchimento do campo unidade era automático existia somente uma unidade. Agora isso não esta acontecendo.

![image](https://cloud.githubusercontent.com/assets/20990100/25109737/4d1a1724-23b5-11e7-864f-0bce069d7d81.png)

![image](https://cloud.githubusercontent.com/assets/20990100/25109745/56b34c88-23b5-11e7-881c-565c0b06e72c.png)

![image](https://cloud.githubusercontent.com/assets/20990100/25109747/5ada730e-23b5-11e7-9643-9f3ab0610a71.png)

![image](https://cloud.githubusercontent.com/assets/20990100/25109750/6308f532-23b5-11e7-9996-110e3b0ab313.png)

**Comment by raphaelMCarvalho** [comment]
Publicado em homologação
