### ISSUE TITLE
Meu Cadastro - Erro ao confirmar o e-mail

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#424]
![image](https://cloud.githubusercontent.com/assets/20990100/25142215/8e832cfa-243c-11e7-9c43-482f086c7869.png)

![image](https://cloud.githubusercontent.com/assets/20990100/25142232/9a2d117e-243c-11e7-83da-b0fd98c937da.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Publicado na homologação
