### ISSUE TITLE
ADM - Inconsistência relatórios orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#425]
No relatório "Produtos orçamentos" temos as seguintes cotações para os orçamento 404 e 450

![image](https://cloud.githubusercontent.com/assets/20990100/25158963/a48b5432-2482-11e7-8c68-009b0254450e.png)

Notem que poucos lojas responderam.

Porém no relatório "Meus orçamentos lojas" os orçamentos aparecem todos com status "Finalizado".

![image](https://cloud.githubusercontent.com/assets/20990100/25158993/e6ac07da-2482-11e7-9584-e1b40c81338b.png)

As lojas que não responderam não deveria ficar com status "Expirado"?

**Comment by lucasretondo** [comment]
Outro ponto, e as lojas que não receberam o orçamento, pq aparecem na lista?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Acredito que não faça sentido alterar para Expirado os lojistas que não responderam caso o cliente esteja fechando um pedindo ainda dentro do prazo que os lojistas tem para responder. Vamos revisar aqui para ter certeza de que os orçamentos ainda abertos e que não estejam expirados sejam alterados para "Não finalizado".
