### ISSUE TITLE
Status inválido

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#43]
Não existe este status na especificação.

![image](https://cloud.githubusercontent.com/assets/20990100/18189338/4eff564a-7090-11e6-8e7f-d6178d6b7a55.png)

**Comment by lucasretondo** [comment]
Não esta exibindo a data de Entrega.

**Comment by raphaelMCarvalho** [comment]
Status comentado em:
https://github.com/PraConstruir/web_app/issues/54#issuecomment-244383537

**Comment by raphaelMCarvalho** [comment]
@lucasretondo achamos que esse status é necessário no fluxo dos pedidos. A realização do pedido pelo cliente não significa automaticamente que haverá uma entrega pelo lojista, assumir isso é exibir informações para o cliente que podem não condizer com a verdade.
