### ISSUE TITLE
Desconto e Acréscimo - O otimizador não atualizou após a loja aumentar o desconto

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#433]
Na primeira vez o otimizador calculou certo, mas depois que aumentei o percentual de desconto ele não refez a otimização:
![image](https://cloud.githubusercontent.com/assets/20990100/25305611/f75bc50a-2754-11e7-802e-901005977b26.png)

O lado bom é que depois que um outro lojista respondeu ele refez o cálculo correto:
![image](https://cloud.githubusercontent.com/assets/20990100/25305620/4015e42e-2755-11e7-8e4d-e5bf87bc8f76.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Atualmente o recálculo é efetuado no recebimento de novos orçamentos. Promover o recálculo em condição adicional (em mudanças cadastrais), pode gerar um overhead no desempenho da atualização de cadastro (já que a cada atualização deverão ser buscados orçamentos em andamento e executar as ações necessárias) e também overhead nos otimizadores. Esse overhead na prática é sentido em um maior tempo para se ter resposta da API e também em aumento dos custos na AWS. É preciso tomar a decisão se mantém da forma como está por enquanto estudando a necessidade ou mesmo alternativas, ou se deve-se trabalhar nisso efetivamente (não sei estimar nesse momento quantas horas para realizar essa modificação).
