### ISSUE TITLE
Resposta Orçamento - Incoerência na regra de pedido mínimo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#434]
O sistema esta exibindo a mensagem que o usuário não atingiu o pedido mínimo de R$ 200, porém o pedido desta loja soma mais de R$ 360.
![image](https://cloud.githubusercontent.com/assets/20990100/25305635/97f57dbc-2755-11e7-9a93-0723bdd58e7a.png)

**Comment by lucasretondo** [comment]
Outro exemplo no mesmo orçamento:
![image](https://cloud.githubusercontent.com/assets/20990100/25305640/c471a514-2755-11e7-87c4-a6b890c17d0d.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Você lembrou de checar os descontos? No caso do Comercial Andrade, por exemplo, há desconto de 50% para pagamento à vista com dinheiro

![screenshot_20170422_211141](https://cloud.githubusercontent.com/assets/20994342/25309322/4f73eb00-27a0-11e7-95d8-577237d46f6a.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Já o segundo exemplo que você deu, há desconto de 40% com dinheiro, por exemplo...
![screenshot_20170422_211345](https://cloud.githubusercontent.com/assets/20994342/25309332/9cddace6-27a0-11e7-8f87-69ac49dbb55e.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho entendi, acho que nós até já discutimos isso, na minha visão a regra do pedido mínimo deve ser sobre o valor descontado. É muito difícil mudar isso?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo É uma mudança que afeta as otimizações, vou discutir com o @claudineicaetano e a equipe na segunda-feira pra entender qual seria o esforço.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho blz, aguardo o seu retorno, obrigado.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Estava discutindo aqui com o pessoal, e chegamos à conclusão que o que você solicitou é o que já está ocorrendo atualmente: a regra do pedido mínimo é aplicada **sobre o valor descontado**. Se o pedido mínimo é R$ 200,00 e o valor "bruto" da compra é R$ 350,00, imagine que com descontos fica R$ 190,00; logo, o pedido mínimo não é atendido. Ou seja, a regra atualmente é aplicada *sobre o valor descontado*, que é R$ 190,00.

> @raphaelMCarvalho entendi, acho que nós até já discutimos isso, na minha visão a regra do pedido mínimo deve ser sobre o valor descontado. É muito difícil mudar isso?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho tem razão, viagem minha...
