### ISSUE TITLE
E-mail Pedido Entregue - Alterar o texto do e-mail de notificação

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#438]
Incluir o nome da loja na primeira frase que ficará assim: "O pedido #355 criado em 19/04/2017 foi entregue por #nome_da_loja."

![image](https://cloud.githubusercontent.com/assets/20990100/25343434/6e3af9de-28e5-11e7-96f2-694172bc44fc.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho O texto ficou perfeito, mas eu esqueci de pedir para incluir o nome da loja no assunto do e-mail, podemos fazer isso para manter um padrão:

![image](https://cloud.githubusercontent.com/assets/20990100/25997507/af465ce6-36f2-11e7-94e4-d98b1b54f8de.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Sem problemas, vamos adicionar o nome da loja no assunto
