### ISSUE TITLE
Mensagens - Criar forma para apagar mensagens indesejadas

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#439]
Temos que pensar em como podemos apagar mensagens indesejadas como esta:
![image](https://cloud.githubusercontent.com/assets/20990100/25352029/fddbecea-2900-11e7-8eac-0d87c8c3c9b8.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Estamos implementando isso, já adianto que: 

1. caso a mensagem possua resposta, a resposta também será excluída para que não fique órfã na base de dados. Isso não é algo opcional;
2. o usuário terá recebido um e-mail avisando sobre a mensagem e ao tocar para entrar no sistema, poderá se deparar com uma lista vazia de mensagens.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ficou bom, obrigado.
