### ISSUE TITLE
Mudar mensagem de não há orçamentos ou pedidos pendentes

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#441]
Estou achando a performance da página web da produção ruim, as páginas demoram para serem carregadas.

Além disso, a mensagem de "Não há orçamento pendentes" ou "Não há pedidos pendentes" que fica aparecendo até que a página seja carregada dá uma sensação ruim, vejam este vídeo:
https://drive.google.com/file/d/0B_JJI1HknOlueXJjSWEzVzd5Z1U/view

Temos como mudar esta mensagem para aguarde... e só exibir esta mensagem quando realmente não tiverem pendências?

**Comment by raphaelMCarvalho** [comment]
Adicionado spinner enquanto o conteúdo é carregado

![captura de tela de 2017-05-11 11-14-36](https://cloud.githubusercontent.com/assets/20994342/25953935/300e5bde-363b-11e7-813f-68ce19db1794.png)

**Comment by lucasretondo** [comment]
Show, melhor que eu pensava... obrigado





---- On Qui, 11 mai 2017 11:16:06 -0300 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




Adicionado spinner enquanto o conteúdo é carregado
