### ISSUE TITLE
Responsive - Não consigo abrir a página do praconstruir na iphone

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#442]
Não estou conseguindo abrir as páginas do praconstruir da produção e homologação no celular da minha esposa. Já tentei em diversos dias e horários.

![img_5065](https://cloud.githubusercontent.com/assets/20990100/25432478/0052108e-2a5b-11e7-8c67-eac1c812f50a.PNG)
![img_5066](https://cloud.githubusercontent.com/assets/20990100/25432476/004dcd6c-2a5b-11e7-90d4-7f179fbc85fe.PNG)
![img_5067](https://cloud.githubusercontent.com/assets/20990100/25432477/004f8d5a-2a5b-11e7-8acc-35658ed90753.PNG)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo No seu iPhone você consegue abrir a produção e a homolog?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho sim, só no da minha esposa que não funciona de jeito nenhum.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Como a gente não tem muito como testar daqui por estar acontecendo em um dispositivo específico, tenho uma sugestão: limpe o cache do navegador do iOS e tente acessar novamente. Se isso resolver o problema, a gente segue a investigação já reduzindo o escopo.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Foi possível limpar o cache do dispositivo e refazer o teste?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho acabei de refazer o teste após limpar o cache e ainda não abre o site.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Acho que esse vai ser um caso que vamos aproveitar melhor pessoalmente. Teria a possibilidade de você trazer o equipamento pra testarmos num próximo encontro presencial? Daí você combina com o Claudinei e me faço presente.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho pode ser este sábado a tarde?

**Comment by raphaelMCarvalho** [comment]
Pode sim, combinadoEm 9 de mai de 2017 11:49 AM, lucasretondo <notifications@github.com> escreveu:@raphaelMCarvalho pode ser este sábado a tarde?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho mudança de planos, vou na 2ª feira de manhã na Angular, obrigado.
