### ISSUE TITLE
Responsive - Melhorar o imput do orçamento na página inicial

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#444]
Quando o usuário abre a página principal a página fica perfeitamente ajusta na tela:
![img_0736](https://cloud.githubusercontent.com/assets/20990100/25433145/ce57c742-2a5d-11e7-8b84-3b3c9c9649de.PNG)

Porém quando ele clica para digitar a descrição do material a tela da zoon e deixar de ficar ajusta a tela e corta as bordas das campos:
![img_0715](https://cloud.githubusercontent.com/assets/20990100/25433186/e7f163fc-2a5d-11e7-8e27-f4d8c0c17bb6.PNG)

É possível apenas subir o teclado e não alterar o zoom?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Dá uma checada por favor se esse é um comportamento que se repete no Safari em outros testes (o comportamento de dar zoom após tocar no input). Digo isso para descartarmos a hipótese de acionamento acidental do zoom.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho quando clico ele dá o zoon, depois eu consigo diminuir o zoom, mas ele aumenta sozinho ao clicar.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Entendi, vamos investigar se tem como evitar esse comportamento indesejado
