### ISSUE TITLE
Responsive - É impossível criar uma lista de compras no celular

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#447]
Não dá para criar uma lista de compras no celular, o esquema da tabela rolar conforme o usuário passa o dedo é bem legal e funciona bem nas tabela do Meus Orçamento e Meus Pedidos, mas não esta funcionamento bem na lista de compras:
![arquivo_000](https://cloud.githubusercontent.com/assets/20990100/25434534/0c3f9170-2a63-11e7-8023-76b3d94b08f7.png)

Como nós podemos melhorar isso?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho se mudar o nome do campo DE "Outras informações" PARA "Mais" o sistema não aumentaria automaticamente o tamanho do campo material? Tornando assim a tabela mais fácil de navegar?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo A página do print que você enviou está com zoom. De qualquer forma, a tabela no zoom 100% fica visível e permite a navegação horizontal, mas o "Outras informações" fica parcialmente visível. Trocando pra "Mais" acho que dá pra gente dar uma ajustada priorizando a coluna de material sim, no entanto não sei se o termo "Mais" vai passar a ideia que queremos. O que acha?

![2017-04-26 18 25 41](https://cloud.githubusercontent.com/assets/20994342/25450460/65cee2ae-2a95-11e7-8910-4676a2ec7e63.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho é fácil mudar isso? Se sim, vamos fazer um teste, se ficar bom pensamos em um termo melhor, caso contrário não perdemos tempo pensando nisso. O que vc acha?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não é difícil, vamos testar na homolog então

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ao abrir a lista de compras vazia a coluna "Mais" esta pequena, porém ao digitar o materiais ela aumenta
![image](https://cloud.githubusercontent.com/assets/20990100/25599804/85caecbe-2eb5-11e7-86e7-ec17219364a0.png)

![image](https://cloud.githubusercontent.com/assets/20990100/25599810/91cfb72e-2eb5-11e7-902c-a8843c932ef8.png)

Se possível aumentar um pouco a coluna "Unidade".

O que vc acha do termo "Obs"?
