### ISSUE TITLE
Responsive - O usuário não consegue excluir um item da lista de compras

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#448]
O usuário não consegue hoje excluir um item da lista de compras:
![arquivo_001](https://cloud.githubusercontent.com/assets/20990100/25434588/4046b2d2-2a63-11e7-8b63-ee34530a5cb8.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo A página está com zoom, mas testamos aqui e esse modal está mesmo com problema, vamos corrigir.
