### ISSUE TITLE
Responsive - A mensagem de solicitação enviada esta cortada

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#449]
No celular a mensagem de solicitação enviada esta cortada:
![img_0720](https://cloud.githubusercontent.com/assets/20990100/25434644/732bd254-2a63-11e7-8f3f-796430af668f.PNG)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Vamos revisar, possivelmente relacionada à #448
