### ISSUE TITLE
Responsive - Ajustar o tamanho do quadro do termo de uso

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#452]
Hoje o quadro do termo de uso é maior que a tela, é possível ajustar isso?
![img_0727](https://cloud.githubusercontent.com/assets/20990100/25438229/2a777340-2a6f-11e7-99e5-3d2648114e5f.PNG)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo No Android está ok, você teve essa experiência apenas no seu dispositivo iOS ou em mais de um?
![2017-04-26 15 07 22](https://cloud.githubusercontent.com/assets/20994342/25441695/566dbf40-2a79-11e7-8845-6e604e583019.png)
