### ISSUE TITLE
Responsive - Ajustar o cadastro ao tamanho da tela

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#453]
Precisamos ajustar a página de cadastro ao tamanho da tela também:
![img_0728](https://cloud.githubusercontent.com/assets/20990100/25438293/5c5f4374-2a6f-11e7-8926-17bb99858908.PNG)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo O responsive está tranquilo para devices como o Android, por exemplo. Você teve essa experiência no seu iOS? No navegador Safari?

![2017-04-26 15 07 38](https://cloud.githubusercontent.com/assets/20994342/25441627/1838a87a-2a79-11e7-90dd-85c39b8cbef0.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Dá a impressão que o usuário deu zoom na exibição do site, sendo exibido num tamanho maior que 100%. Por exemplo, na captura de tela abaixo eu aumentei o zoom da página no meu celular Android. Nesse caso não é problema do site a configuração de zoom do navegador do usuário.

![2017-04-26 15 14 45](https://cloud.githubusercontent.com/assets/20994342/25441951/0e56bd32-2a7a-11e7-8ddb-b0a80a4488fe.png)

**Comment by lucasretondo** [comment]
Você tem razão, sorry... estou me sentido muito mal depois dessa...
