### ISSUE TITLE
Responsive - Mudar página inicial

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#454]
@raphaelMCarvalho acho que foi vc que me alertou que o botão do como funciona iria atrapalhar a navegação no celular, pois é, vc tinha razão, hoje quando o usuário abre o como funciona no celular ficar preciso em um tela enorme o perde o foco no orçamento.

Por isso estou pensando um mudar a página inicial DE:
![image](https://cloud.githubusercontent.com/assets/20990100/25447408/74d37e40-2a8b-11e7-82e8-1d9ce01309b0.png)

PARA: 
![image](https://cloud.githubusercontent.com/assets/20990100/25447411/7dbb8264-2a8b-11e7-94ec-f71185cefe0b.png)

Também aumentaria a 2ª frase banner principal DE "Queremos ajudá-lo a comprar melhor" PARA "Queremos ajudá-lo a comprar melhor o material básico da sua construção"

O que vocês acham?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Está publicado em produção. A sugestão de mudança do "slogan" no entanto sugiro refletir um pouco mais, ficou muito grande a frase.

**Comment by lucasretondo** [comment]
Ficou bom, concordo sobre a frase, vamos deixar assim, obrigado...












---- On Sex, 05 mai 2017 17:46:17 -0300 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo Está publicado em produção. A sugestão de mudança do "slogan" no entanto sugiro refletir um pouco mais, ficou muito grande a frase.
