### ISSUE TITLE
Seja um Representante - Melhorar o texto

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#455]
Substituir os termos "Visita" por "Cadastramento" e "Captar" por "Cadastrar"
![image](https://cloud.githubusercontent.com/assets/20990100/25485090/f14b0dce-2b32-11e7-9448-de059465710a.png)

**Comment by lucasretondo** [comment]
Vamos deixar somente Cadastramento para ficar padrão com as demais etapas

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não entendi. A correção não foi efetivada?

**Comment by lucasretondo** [comment]
Vocês colocaram Cadastramentos ao invés de Cadastramento.

Detalhes...
