### ISSUE TITLE
Como funciona - Melhorar o texto

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#456]
Precisamos melhorar alguns detalhes do texto do como funciona.

![image](https://cloud.githubusercontent.com/assets/20990100/25485825/9fd07e04-2b35-11e7-8c65-9fc2155c0ca0.png)

DE "Faça os orçamentos dos materiais da sua construção com vários fornecedores em poucos minutos."
PARA "Solicite o orçamento dos materiais básicos da sua construção para as melhores lojas da sua região em poucos minutos."

DE "Compare os orçamentos dos diversos fornecedores e otimize sua compra de forma fácil e ágil."
PARA "Compare os orçamentos e crie os pedidos de compra de maneira fácil e ágil."

DE "Acompanhe o andamento dos seus pedidos e entregas onde você estiver."
PARA "Acompanhe o status dos pedidos pelo site ou aplicativo e só pague após a entrega."

Lembrem se alterar em todas as páginas (Ajuda,...)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo A ajuda recomendo que você faça as alterações que desejar no json e envie pra gente atualizar; digo isso pois é mais garantido por você já ter em mente a mensagem que quer passar em todos os assuntos relacionados a esses três pontos chave. O como funciona vamos atualizar, em todas as ocorrências dele, inclusive as páginas internas onde ele estiver sendo exibido.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não quero revisar o ajuda. O lembreto é que na página do Ajuda tem o como funciona
![image](https://cloud.githubusercontent.com/assets/20990100/25489645/d50a2556-2b40-11e7-8ce5-4bb5f7dc1d65.png)

Não lembro mais onde tem.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Perfeito, onde tiver o como funciona vamos atualizar sim

**Comment by lucasretondo** [comment]
@raphaelMCarvalho é possível fazer esta alteração na produção como hotfix?

**Comment by lucasretondo** [comment]
Vamos padronizar as frase do como funciona para ficar igual ao Android, assim precisamos mudar os texto conforme abaixo:

DE "Faça os orçamentos dos materiais da sua construção com vários fornecedores em poucos minutos." PARA "Você faz a sua lista de compras, escolhe o local e a data da entrega e solicita o orçamento."

DE "Economize tempo e dinheiro na criação dos pedidos" PARA "Economize tempo e dinheiro"

DE "Compare os orçamentos dos diversos fornecedores e otimize sua compra de forma fácil e ágil." PARA "Nós enviamos o seu orçamento para as melhores lojas de materiais de construção da sua região."

DE "Monitore seus pedidos e entregas" PARA "Crie os seus pedidos"

DE "Acompanhe o andamento dos seus pedidos e entregas onde você estiver." PARA "Compare as cotações e crie os pedidos de compra pelo aplicativo, sem sair de casa."
