### ISSUE TITLE
Página após login lojista

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#46]
Realizei o login com o lojista pdcc.parceiro1@mailinator.com e fui direciona para a tela abaixo quando o correto seria a tela Meu Resumo.

![image](https://cloud.githubusercontent.com/assets/20990100/18189459/72038778-7091-11e6-88c0-ebf9c550a0a8.png)

**Comment by raphaelMCarvalho** [comment]
Resolvido, será publicado no servidor até as 18h de hoje.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo foi possível validar essa issue? Em caso positivo, vamos fechando as issues resolvidas.
