### ISSUE TITLE
Cadastro Obra - Não carrega a cidade do CEP 18725-000

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#461]
Não esta carregando os dados ao informar o CEP 18725-000
![image](https://cloud.githubusercontent.com/assets/20990100/25786468/12196bd6-336c-11e7-8c9f-b2ae075f7ea6.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho desculpe, abri este issue com os labels errados, este problema ocorreu com um cliente e depois eu fiz o testo em homolog para confirmar.

**Comment by raphaelMCarvalho** [comment]
Primeiramente, essa issue não é um caso impeditivo, ou seja, o usuário não obtendo os dados do CEP poderia continuar o registro da obra normalmente. Quanto aos detalhes do ocorrido: estamos consumindo uma API em que enviamos o CEP e ela retorna os dados daquele CEP. Feito isso, cruzamos dados de cidade e estado com a base de dados da nossa API. O que ocorre eventualmente é que a base de cidades dessa API que consumimos pode conter casos especiais. No caso do CEP em questão, a API externa estava retornando uma cidade chamada "Holambra II (Paranapanema)" e não era possível cruzar. Casos como esse podem ocorrer novamente.

![screenshot_20170508_152333](https://cloud.githubusercontent.com/assets/20994342/25818893/7e8ef812-3402-11e7-8446-95a0f54f1e02.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho pedi para o cliente tentar novamente, antes não estava carregando a cidade. Obrigado
