### ISSUE TITLE
Cadastro Cliente - Não é possível fazer um novo cadastro com o Facebook

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#462]
Na produção não esta funcionando realizar uma nova cadastro através do facebook.

https://drive.google.com/file/d/0B_JJI1HknOludFc1T0dnSV9UMHM/view

**Comment by raphaelbluteau** [comment]
@lucasretondo No segundo momento em que você clica pra cadastrar e funciona normalmente, o que foi feito de diferente? Era na produção ainda? Pelo vídeo não deu pra entender

**Comment by lucasretondo** [comment]
@raphaelbluteau desculpe, esqueci que o vídeo só grava a tela, a 2ª vez era em homolog.

**Comment by raphaelbluteau** [comment]
@lucasretondo Obrigado, Lucas, já vamos ver o que houve

**Comment by raphaelMCarvalho** [comment]
@lucasretondo O cadastro com Facebook está funcionando em produção, não identifiquei nenhum problema na feature. Veja se seu navegador não está bloqueando pop-ups do Facebook. Veja abaixo sequência em que navegador bloqueou e eu liberei a pop-up.

![screenshot_20170508_153510](https://cloud.githubusercontent.com/assets/20994342/25819353/209a0506-3404-11e7-83f6-1be739568ea9.png)

![screenshot_20170508_153528](https://cloud.githubusercontent.com/assets/20994342/25819358/26302978-3404-11e7-9bfe-455105bf3472.png)

![screenshot_20170508_153610](https://cloud.githubusercontent.com/assets/20994342/25819366/2bd0405c-3404-11e7-8670-ca9126ba8bbe.png)

**Comment by lucasretondo** [comment]
@raphaelbluteau e como uma usuário comum vai saber se precisar desbloquear o pop-up? Não tem como ter uma alerta?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo É o comportamento padrão do navegador pra pop-ups, não sei se tem uma forma de alertar além do alerta que o navegador já faz na barra de endereços

**Comment by lucasretondo** [comment]
@raphaelbluteau este é o ponto, o navegador não exibiu nenhuma mensagem para desbloquear os pop-up, como fazemos para o navegador exibir esta mensagem?

**Comment by raphaelbluteau** [comment]
Vou ver se isso é possível

Em 9 de mai de 2017 10:11 AM, "lucasretondo" <notifications@github.com>
escreveu:

**Comment by raphaelMCarvalho** [comment]
Estudamos algumas possibilidades e chegamos a esse resultado: modificamos o código que realiza autenticação com Facebook de forma que o navegador não mais bloqueará o pop-up

![screenshot_20170510_141211](https://cloud.githubusercontent.com/assets/20994342/25911575/c1578bda-358a-11e7-8e9e-59a9873ac8e6.png)

**Comment by lucasretondo** [comment]
Legal, vou testar. Obrigado tudo hj sem falta.





---- On Qua, 10 mai 2017 14:14:06 -0300 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




Estudamos algumas possibilidades e chegamos a esse resultado: modificamos o código que realiza autenticação com Facebook de forma que o navegador não mais bloqueará o pop-up
