### ISSUE TITLE
Descontos e Acréscimos - O ADM não consegue ver as formas de pagamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#468]
O usuário com perfil ADM não consegue ou alterar as formas de pagamento:

![image](https://cloud.githubusercontent.com/assets/20990100/25967024/26f4a490-3663-11e7-8488-9a3d6942e145.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Por que foi removida a label 'para validar'? Conforme captura de tela, o admin consegue visualizar e alterar as formas de pagamento.

![captura de tela de 2017-05-17 17-45-21](https://cloud.githubusercontent.com/assets/20994342/26175320/a9a1faae-3b28-11e7-847f-4c7f3aed5873.png)
