### ISSUE TITLE
Criar Orçamento - Não estou conseguindo criar nenhum orçamento com o cli2

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#469]
Este comportamento esta ocorrendo somente com o usuário cli2@mailinator.com. Todas as obras são da região de Piracicaba, porém o sistema esta apresentando uma mensagem de erro que não existe nenhum lojista para atender o orçamento.

https://drive.google.com/file/d/0B_JJI1HknOlubDNlTzkwb3Y4dnc/view

**Comment by lucasretondo** [comment]
O mesmo esta ocorrendo com o cli3@mailinator.com

![image](https://cloud.githubusercontent.com/assets/20990100/25969544/af7d549e-366b-11e7-861d-66ed00e0e68d.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Você chegou a verificar se os lojistas da região aceitam cartão de crédito MasterCard?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho sim, com o usuário cli1@mailinator.com isso não ocorre.
