### ISSUE TITLE
Perda de informações

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#47]
Após realizar o login com o usuário pdcc.parceiro1@mailinator.com (senha parceiro1$$) não consegui acessar nenhuma página.

![image](https://cloud.githubusercontent.com/assets/20990100/18189487/bebbe88a-7091-11e6-8b6e-f320e39d5f93.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18189494/c8b8b872-7091-11e6-9c95-220ac0bfa359.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18189495/cd2c6e8a-7091-11e6-8d86-eaa210327801.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18189503/d8a6825a-7091-11e6-97f1-620b165b8c4e.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo este bug tinha relação com outros bugs que foram resolvidos na última semana
