### ISSUE TITLE
Criar Orçamento - Tentei criar um orçamento sem selecionar nenhuma forma de pagamento o sistema travou

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#470]
Tentei criar um orçamento sem selecionar nenhuma forma de pagamento o sistema travou sem exibir nenhuma mensagem de erro.

![image](https://cloud.githubusercontent.com/assets/20990100/25969614/f0bd17e6-366b-11e7-98d7-e1b9b0d0268e.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Só pra esclarecer, quando você diz que travou, significa que travou o navegador ou que a ação não foi concluída e não houve resposta da interface?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho a ação não foi concluída, ficou rodando infinitamente. Depois que eu deu um refresh voltou a funcionar, mas perdi tudo que havia informado.
