### ISSUE TITLE
Responder Orçamento - Colocar o spinner tb no botao "Voltar"

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#471]
Colocar o spinner tb no botao "Voltar" e quanto o botão for cinza colocar o spinner com um cor cinza claro e não laranja.

https://drive.google.com/file/d/0B_JJI1HknOluLTFoekt1X0J4QmM/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo O botão Voltar não se encaixa na experiência de uso do spinner que implementamos. A experiência que temos é a seguinte: o usuário tocou em um botão cuja ação depende de resposta do backend; nesse meio tempo, os botões que efetivamente acionam o backend ficam com o spinner. O botão Voltar não aciona o backend, é apenas a navegação do frontend. Além disso, acredito que não seja uma boa prática impedir que o usuário navegue de volta à tela anterior, até porque a ação que ele ativou será completada independente disso.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho entendi, vc tem razão, obrigado.
