### ISSUE TITLE
Meu Cadastro Lojista - Manter um padrão

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#472]
Padronizar a distância e fonte dos títulos do Meu Cadastro, por exemplo:

1- A distância entre o título "Dados da Empresa" e "Endereço da Empresa" para os campos anteriores e maior que a distância dos títulos "Funcionamento e Entrega", "Principais tipos de Materiais*"

2- Os títulos "Horário de funcionamento*", "Pedido mínimo", "Desconto" e "Acréscimos" não estão em negrito igual os demais

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Dá uma alinhada com a Agência essa melhoria, pois procuramos seguir ao máximo o layout recebido. Quanto mais nos distanciarmos das artes mais difícil vai ficar rastrear essas mudanças e o motivo delas.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não te explicar pq não percebi isso antes, mas não são alterações significativas a ponto de ter que voltar para a NA+, estou pedindo apenas para aumentar um linha em dois casos.

Note que existe uma linha entro último campo do tópico anterior e o novo
![image](https://cloud.githubusercontent.com/assets/20990100/25979358/572fdd24-369e-11e7-8346-c590ae945a7a.png)

Nos exemplos citada essa linha não existe
![image](https://cloud.githubusercontent.com/assets/20990100/25979371/673bc598-369e-11e7-98ef-f2f1f90f7b38.png)

A segunda sugestão pode ignorar.
