### ISSUE TITLE
Resposta Orçamento - Não separar o sinal de "-" nos descontos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#473]
Fica estranho quando quebramos a linha desconte em duas, separando assim o sinal de "-" do valor.

![image](https://cloud.githubusercontent.com/assets/20990100/25971190/c28c1740-3671-11e7-8771-92626cb6d0ef.png)

Não é melhor colocar "(R$ XXX,XX)" ao invés de "-R$ XXX,XX"?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Foi resolvida a quebra de linha mantendo o '-' para manter tanto a consistência com a tela, que indica esses prefixos [ Valor descontos (-) / acréscimos (+) ], quanto para ser de fácil compreensão pro usuário, de que aquele valor está sendo subtraído.
