### ISSUE TITLE
ADM - Inconsistência no relatório

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#474]
Pelo relatório "Meus orçamentos lojas" as lojas abaixo tem orçamentos pendentes:
![image](https://cloud.githubusercontent.com/assets/20990100/25998359/fafa5436-36f6-11e7-94fc-543fa5caa419.png)

Porém quando acesso o site não vejo nenhum orçamento pendente:
![image](https://cloud.githubusercontent.com/assets/20990100/25998389/1eefec2a-36f7-11e7-9694-4327226adad7.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Olá Lucas, não estamos conseguindo reproduzir essa issue. Você lembra se houve algum passo especial no procedimento ou se ocorreu algum problema no fluxo? Se conseguir reproduzir ou se possuir alguns detalhes adicionais agradeço.
