### ISSUE TITLE
Resposta Orçamento - Incluir as formas de pagamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#477]
Estou criando esta issue apenas para documentar a alteração do layout já enviada ao Claudinei.
![parceiros-orcamento-v1 5-ajuste-forma-de-pagamento](https://cloud.githubusercontent.com/assets/20990100/26156601/3dba1230-3aed-11e7-98b8-e5da572917d9.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Sugiro retornar a arte à agência para que seja reformulada para evitar uma experiência ruim por parte dos usuários. Veja bem, foram adotados elementos de UX para fins de visualização que já são utilizados em outras partes do site para representar ações de confirmar e excluir. Veja por exemplo na tela de criar orçamento, ao inserir um produto, aparece o botão de Excluir. Veja também do lado do lojista, quando ele tem que confirmar um pedido. Não podemos ter duas finalidades diferentes como essas utilizando os mesmos elementos, sob pena de confundir os usuários.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vc tem razão, bom ponto. O cara da agência que faz os layouts esta de férias e só volta em 10/junho, vou pedir para ele mudar, mas por enquanto podemos colocar só "Sim" ou "Não"?

**Comment by raphaelMCarvalho** [comment]
![captura de tela de 2017-05-19 11-25-54](https://cloud.githubusercontent.com/assets/20994342/26252384/74a3406a-3c86-11e7-9ac5-0eff4d472bdc.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ficou ótimo...
