### ISSUE TITLE
Criar página como solicitar um orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#478]
Precisamos criar uma página explicando como solicitar um orçamento conforme layout abaixo:
![como-solicitar-seu-orcamento](https://cloud.githubusercontent.com/assets/20990100/26146685/6fd15f24-3ac7-11e7-9f01-c66f92c60b11.png)

Vamos seguir o mesmo modelo das páginas https://pdcc.angularlabs.com.br/otimizacao e https://pdcc.angularlabs.com.br/personalizacao. O layout completo e os GIFs já forma enviados ao Claudinei.

Os textos são:

Escolha o produto
Digite algumas palavras da descrição do material que você deseja que o nosso sistema irá automaticamente procurar os produtos cadastrados. Informe a unidade de medida, quantidade e clique em “Criar Orçamento” para adicionar este material a sua lista de compras.

Lista de compras
Adicione quantos materiais desejar a sua lista de compras clicando no campo “+ inserir produto” ou pressionando “ENTER”. Você também pode solicitar orçamento de materiais não cadastrados, basta preencher os campos livremente.

Selecione o endereço, data da entrega e forma de pagamento
Escolha uma obra cadastrada ou adicione um novo local de entrega, informe a data e período da entrega e selecione quais formas de pagamento você quer utilizar. Lembrando que o pagamento será feito direto com a loja após a entrega. Para finalizar clique em "Solicitar orçamento", agora é só aguardar as respostas das lojas.

Vamos adicionar um link na página inicial na coluna ferramentas, acima do "Otimize o seu pedido" com o nome "Solicite o seu orçamento".
![image](https://cloud.githubusercontent.com/assets/20990100/26146781/c751eafc-3ac7-11e7-9b7c-8e70467a2ba9.png)

Após o botão "Criar orçamento" vamos inserir a seguinte frase "Clique aqui para aprender a otimizar o seu pedido." Sendo aqui um link para a página https://pdcc.angularlabs.com.br/otimizacao

Na página inicial vamos mudar a frase "Saiba mais sobre como otimizar seus pedidos clicando aqui." do como funciona para "Saiba mais como solicitar o seu orçamento clicando aqui." Aqui deverá ser um link para esta nova página.

**Comment by lucasretondo** [comment]
Faltou alterar os textos e incluir a frase depois do botão criar orçamento.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Quando os textos foram inseridos na issue?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Vi agora que a issue foi editada 5 horas atrás. Publiquei o que havia sido feito ontem. Sugiro que as issues não sejam editadas, e sempre sejam usados os comentários para mudanças não ficarem escondidas e passarem despercebidas.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Outro ponto importante: caso seja prática comum a edição das issues e comentários, é necessário que se libere o acesso ao histórico de alterações.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho desculpe, não sabia que você não tinha acesso ao histórico e achei melhor melhorar o comentário do que criar um novo. Vou me policiar para sempre criar novos comentários.
