### ISSUE TITLE
Campo confirmar e-mail

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#48]
O campo "Confirmar e-mail" deve obrigar o usuário a digitar o e-mail.

Não deveria permitir Ctrl C + Ctrl V como no exemplo abaixo.

![image](https://cloud.githubusercontent.com/assets/20990100/18190130/a0590c2e-7096-11e6-8923-ab0f087c5163.png)

**Comment by raphaelMCarvalho** [comment]
Não acho que esta issue devesse ser cadastrada como bug.
