### ISSUE TITLE
Meus Pedidos - Não consegue confirmar entrega detalhada

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#482]
Mesmo depois de selecionar todos os produtos, não é possível confirmar a entrega no template detalhado.

https://drive.google.com/file/d/0B_JJI1HknOluNkVjUlpjNFd6M0k/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Isso aconteceu em decorrência do que chamamos de "condição de corrida". Fizemos uma implementação que deve evitar que novos casos como esse ocorram.
