### ISSUE TITLE
Responsive - Melhor o layout das páginas de ferramentas

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#483]
Precisamos melhor a exibição das páginas https://pdcc.angularlabs.com.br/instrucoes, https://pdcc.angularlabs.com.br/otimizacao e https://pdcc.angularlabs.com.br/personalizacao no celular.

Hoje o texto do banner principal esta quebrado
![img_1370](https://cloud.githubusercontent.com/assets/20990100/26193741/8e32994a-3b8c-11e7-9eac-e1d5cd142c83.PNG)

O título esta se sobrepondo com os icones
![img_1371](https://cloud.githubusercontent.com/assets/20990100/26193768/9dd34b38-3b8c-11e7-8610-25b3ca46f3d3.PNG)
![img_1375](https://cloud.githubusercontent.com/assets/20990100/26193772/9fafdfb6-3b8c-11e7-82e8-fdb8a0ee5ecd.PNG)

E as figuras estão muito pequenas (acho que o ideal seria a figura ficar acima do texto e o texto ocupar a tela inteira)
![img_1372](https://cloud.githubusercontent.com/assets/20990100/26193809/b929ca06-3b8c-11e7-8a9f-84d5c129cfc0.PNG)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho as figuras na página de otimização continuam de lado de propósito ou esquecemos?
![image](https://cloud.githubusercontent.com/assets/20990100/26217259/1b27dfb8-3bdd-11e7-9475-f510a38421d7.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Foi proposital, testamos da forma como estão os gifs mas não ficou interessante

**Comment by lucasretondo** [comment]
Blz...
