### ISSUE TITLE
Resposta Orçamento - Melhorar a mensagem

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#488]
Vamos melhorar a nossa comunicação mudando as mensagem de erro:
DE "Insira a marca" PARA "Informe a marca ou origem"
DE "Há marca(s) não preenchida(s)" PARA "Há marca(s) ou origem(s) não preenchida(s)"
![image](https://cloud.githubusercontent.com/assets/20990100/26528790/0eec1bb6-4389-11e7-88e0-67cfcee8b29f.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo a mensagem "Informe a marca ou origem" é muito longa para esse placeholder. Colocamos "Informe a marca" ao invés disso. A outra mensagem foi alterada como solicitado.
