### ISSUE TITLE
Layout criar orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#49]
Vamos aumentar um pouco a largura das colunas unidade e qtd. Esta cortando em alguns casos reais.

![image](https://cloud.githubusercontent.com/assets/20990100/18190320/57c25306-7098-11e6-89c8-02c7ef0aa61c.png)

**Comment by lucasretondo** [comment]
Continua pequeno... veja #105 Largura coluna Criar Orçamento

**Comment by raphaelMCarvalho** [comment]
@lucasretondo checar cache do navegador:

![2016-09-16 1](https://cloud.githubusercontent.com/assets/20994342/18589364/cc661058-7c00-11e6-9f81-14363f7b1dc6.png)
