### ISSUE TITLE
Página Inicial - Criar novo link

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#491]
Ao analisarmos um mapa de calor de cliques abaixo observamos que vários usuários clicam no PARCEIRO do menu inferior.

![image](https://cloud.githubusercontent.com/assets/20990100/26692250/632490be-46d6-11e7-8ab8-df84d3eb6eb4.png)

Por isso acho válido transformar ele em link para a página Parceiros, o que vcs acham?

Tal valha a pena transformar em link o FERRAMENTAS tb.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo É necessário discutir essa issue do ponto de vista da consistência. Se há a intenção de colocar link em Parceiros e em Ferramentas, qual link você quer colocar em Consumidor? E ao clicar em Ferramentas, pra onde vai?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vamos colocar estes links.

Empresa: https://praconstruir.com.br/nossa-proposta
Consumidor: https://praconstruir.com.br/consumidor/painel/orcamento/
Parceiro: https://praconstruir.com.br/parceiro
Ferramentas: https://praconstruir.com.br/instrucoes
