### ISSUE TITLE
Capturar E-mail

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#492]
É possível capturar o e-mail quando o usuário preencher o e-mail e clicar em cadastrar?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo É possível, mas para evitar que bots fiquem populando a base de dados teríamos que implementar uma checagem adicional além do campo de e-mail, para garantir que é uma pessoa preenchendo. Na prática, antes de chegar à tela de registro a pessoa teria que preencher 2 campos ao invés de 1. Ainda assim, não há garantia de e-mails válidos sendo capturados, a qualidade dessa informação só é assegurada após o cadastro e a confirmação da conta, que é o fluxo padrão já em operação.
