### ISSUE TITLE
ADM - Incluir a cidade no endereço

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#493]
![image](https://user-images.githubusercontent.com/20990100/26948755-e4e45bec-4c6d-11e7-91b1-cb4855a340f9.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não consigo testar essa issue, pois o meu usuário não esta funcionando no homolog. Já tentei resgatar a senha diversas vezes.

**Comment by raphaelMCarvalho** [comment]
Foi criado com a senha padrão 34164579, testa aí 

Enviado do meu iPhone
