### ISSUE TITLE
Criar Orçamento - Aumentar o tamanho da campo Medida

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#496]
Vamos aumentar o campo medido e diminuir a descrição do material.

O exemplo abaixo é com a maior medida cadastrada hj.
![image](https://user-images.githubusercontent.com/20990100/26951155-8f9798e4-4c76-11e7-8522-a0b509fa7965.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Analisando a nova leva de medidas, não há mais necessidade de aumentar o campo de Medida

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não concordo.
![image](https://user-images.githubusercontent.com/20990100/26992237-168cdd1a-4d34-11e7-952b-18efb4f07246.png)
