### ISSUE TITLE
Página Inicial - Incluir novos cidades na página inicial

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#499]
Precisamos incluir novas cidades no banner do mapa da home.

Vamos incluir as cidades de Goiânia/GO, BH/MG, Campo Grande/MS e Campinas/SP.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Este é o arquivo SVG do projeto, é exatamente este arquivo que é exibido, da forma como está. Peça à agência que edite esse arquivo adicionando as cidades. É importante que eles usem esse arquivo e mantenham as dimensões, proporção e esquema de cores, pois retornando o arquivo vamos apenas inserir lá da forma recebida. Se houver alguma modificação, por exemplo na proporção do arquivo, aí será necessário trabalhar no HTML e na folha de estilos para ajustar às novas dimensões do arquivo; estamos enviando esse arquivo do projeto na intenção de evitar quaisquer retrabalhos.

[influence_map.svg.zip](https://github.com/PraConstruir/web_app/files/1094780/influence_map.svg.zip)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vamos criar um novo banner e página para as cidades, mas isso só deve rolar no próximo mês. Por enquanto é possível alterarmos somente os textos das cidades de São Paulo sem passar pelo NA+?

DE:
"Itu - SP
Piracicaba - SP
São José do Rio Preto - SP
Sorocaba - SP"

PARA:
"Campinas e região - SP
Jundiaí e região - SP
São Paulo e região - SP
Sorocaba e região - SP"

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Atualizado
