### ISSUE TITLE
Resposta Orçamento - Regra exibição cadastro

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#50]
Não esta funcionando a regra de negócio para exibir ao lojista somente o itens das categorias atendidas por ele (usuário pdcc.parceiro5@mailinator.com).

![image](https://cloud.githubusercontent.com/assets/20990100/18190799/affae6ac-709b-11e6-8cd5-c2fff3de50fe.png)

**Comment by raphaelMCarvalho** [comment]
Não é um bug, funciona como esperado. Essa regra não existe. Se houver ao menos um item no orçamento que o lojista atenda, ele receberá a solicitação de orçamento. Para itens que ele não atende, existe a opção dele informar que é fora do escopo.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo foi possível validar essa issue? Em caso positivo, vamos fechando as issues resolvidas.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho como é feito o filtro para saber se ele atende? Pq obrigar o lojista a informar o tipo de material no cadastro se não fazemos nenhum filtro para enviar para ele comente os itens relacionados ao tipo de material cadastrado? É muito complicado incluir esta regra?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo , você está enganado quando diz que não fazemos nenhum filtro, fazemos sim. No momento da solicitação do orçamento, o backend verifica a lista de itens, montando uma lista de materiais. Em seguida, ele cruza a lista de materiais com as listas de materiais que os lojistas atendem. Se ao menos um item atende, o orçamento é enviado para o lojista conforme a especificação de requisitos. Se um ou mais itens da lista não são atendidos pelo lojista, então ele pode marcar que o item é fora de escopo. Para fazer da forma como você está descrevendo, precisaríamos fazer essa mudança na especificação e realizar algumas modificações no backend, iria demandar algumas horas de desenvolvimento.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho veja o exemplo abaixo com o lojista parceiro4, ele não selecionar a categoria de material básico...
![image](https://cloud.githubusercontent.com/assets/20990100/18458748/14e5bbae-793a-11e6-98bf-67ad26855c49.png)
![image](https://cloud.githubusercontent.com/assets/20990100/18458752/1a253de2-793a-11e6-804d-1ec72c381bd9.png)

Porém no preenchimento o orçamento aparecem materiais do básico...
![image](https://cloud.githubusercontent.com/assets/20990100/18458761/3773230a-793a-11e6-8b65-ca85e0a0d14d.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo funcionando conforme especificação de requisitos

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Neste caso vamos ter que mudar a especificação, não faz sentido exibir itens que o lojista não entende.
