### ISSUE TITLE
Criar Orçamento - Não esta funcionando o Elastic

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#501]
![image](https://user-images.githubusercontent.com/20990100/28048190-bdbc8230-65c5-11e7-8b54-b5669e7359a6.png)

**Comment by raphaelMCarvalho** [comment]
Olá Lucas, estamos realizando algumas alterações na homolog e estamos cientes quanto ao Elastic, não há necessidade de manter aberta esta issue.

Enviado do meu iPhone

**Comment by lucasretondo** [comment]
Imaginei... tranquilo, obrigado...









---- On Seg, 10 jul 2017 23:45:46 -0300 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




Olá Lucas, estamos realizando algumas alterações na homolog e estamos cientes quanto ao Elastic, não há necessidade de manter aberta esta issue.

 

 Enviado do meu iPhone

 

 &gt; Em 10 de jul de 2017, às 23:16, lucasretondo &lt;notifications@github.com&gt; escreveu:

 &gt; 

 &gt; 

 &gt; —

 &gt; You are receiving this because you are subscribed to this thread.

 &gt; Reply to this email directly, view it on GitHub, or mute the thread.

 &gt;

**Comment by raphaelMCarvalho** [comment]
https://github.com/PraConstruir/web_app/issues/501#issuecomment-314307448
