### ISSUE TITLE
Obras - Tratar exceções na obtenção de coordenadas geográficas de obras

### ISSUE THREAD

**Issue by raphaelMCarvalho** [PraConstruir/web_app#502]
@lucasretondo Nossa API utiliza dados externos para preencher automaticamente o endereço de obras ao serem criadas. Em seguida, tendo o endereço "em mãos", nossa API consulta o Google para obter as coordenadas geográficas (latitude e longitude). Para alguns endereços a API do Google infelizmente não retorna coordenadas geográficas válidas, especialmente quando o endereço possui alguma observação entre parênteses no nome. Devemos pensar em alguma forma de mitigar este problema; uma hipótese (além de tratar os nomes antes de consultar na API do Google) é obter as coordenadas da cidade quando não for possível obter do endereço.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho eu tenho acompanhado este problema já faz um tempo, tenho uma coleção CEPs que não reconhecem de primeira, mas depois que o usuário apaga a última letra e escrever novamente ele funciona.
Acho que a melhor saída para não perder o cliente é usar a coordenada da cidade provisoriamente, para depois temos que conseguir identificar e tratar os casos.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Esse ajuste estará disponível para testes amanhã na homolog.
