### ISSUE TITLE
Termo de uso

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#504]
Excluir o trecho abaixo do termo de uso do site e cadastro web e app.
![image](https://user-images.githubusercontent.com/20990100/28505650-39fc8a1c-6ffc-11e7-854d-6b3d89d14dbe.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Revisando para exclusão desse trecho, vi que há menções sobre royalties e boletos em diversos pontos tanto dos Termos de Uso quanto da Ajuda. É importante que você revise esses pontos, talvez seja necessário reescrever algumas partes desses conteúdos para que façam sentido. Seria possível você fazer isso nas próximas horas e nos enviar apontando os trechos a serem suprimidos ou alterados?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho bom ponto, esses são os trechos do termo de uso que precisamos suprimir:

![image](https://user-images.githubusercontent.com/20990100/28525813-e07d7838-705b-11e7-8923-a8e8cba6784a.png)

![image](https://user-images.githubusercontent.com/20990100/28525826-ea797558-705b-11e7-9198-c4ec4d478db5.png)

![image](https://user-images.githubusercontent.com/20990100/28525842-f4988cd6-705b-11e7-9db0-c49bedb5c762.png)

No ajuda precisamos suprimir a sessão "Cobrança" dos parceiros.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Apenas suprimir Cobrança da Ajuda não é o suficiente. Há diversos pontos da Ajuda que mencionam royalties, não apenas a Cobrança. Há pontos que precisam ser reescritos mesmo, os textos da Ajuda precisam ser revisados.

**Comment by raphaelMCarvalho** [comment]
![captura de tela 2017-07-24 as 11 52 39](https://user-images.githubusercontent.com/20994342/28529332-a5f45faa-7066-11e7-89b2-ccf11d542afe.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho tem razão, vamos lá:

Excluir o frase seleciona abaixo:
![image](https://user-images.githubusercontent.com/20990100/28530064-e33edd5c-7068-11e7-859f-38b25baf667a.png)

Excluir o frase seleciona abaixo:
![image](https://user-images.githubusercontent.com/20990100/28530074-ebfe4fe0-7068-11e7-9299-bb38a0dec36b.png)

Alterar as frases selecionadas:
![image](https://user-images.githubusercontent.com/20990100/28530131-1c4c557a-7069-11e7-9793-12f4cf5b3313.png)
![image](https://user-images.githubusercontent.com/20990100/28530134-1e469d2c-7069-11e7-9c5b-1cb0aa286385.png)
![image](https://user-images.githubusercontent.com/20990100/28530137-204966cc-7069-11e7-8747-b464fea9c764.png)
![image](https://user-images.githubusercontent.com/20990100/28530141-229a64d0-7069-11e7-9541-4e211b5c55c7.png)
PARA: "Para cancelar o pedido envie um e-mail com o número do pedido e o motivo para atendimento@praconstruir.com.br. Para acelerar o seu atendimento utilize o mesmo e-mail cadastrado no Pra Construir."
