### ISSUE TITLE
Não esta calculando pedido

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#51]
Não esta calculando o valor do pedido por material.

![image](https://cloud.githubusercontent.com/assets/20990100/18190863/06785514-709c-11e6-91af-08b6677f3114.png)

**Comment by raphaelMCarvalho** [comment]
Não entendi o bug, você poderia me dar mais detalhes por favor?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo , você poderia dar mais detalhes?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho segue...

![image](https://cloud.githubusercontent.com/assets/20990100/18458584/5e6441d0-7938-11e6-8845-67bda2355089.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo entendi, você quis dizer que a coluna Pedido não apresenta o valor que foi selecionado na linha.
