### ISSUE TITLE
Calculadora Coluna - Melhorar experiência lista de compras

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#515]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Calculadora coluna - lista de compras

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Com o celular na vertical o usuário não consegue ver a lista de compras completa, ele ou vê o nome do produto ou a medida e quantidade.

Agora se ele coloca o celular na horizontal a lista fica completa, melhorando em muito a experiência de uso. É possível obrigar a tela a ficar na horizontal?

Se não, o que vocês acham de incluirmos esta mensagem em acima da tabela:
![image](https://user-images.githubusercontent.com/20990100/29075455-cf98206c-7c28-11e7-953a-30c7c0b3df30.png)

## 3. Captura de tela de como está hoje

Vertical
![image](https://user-images.githubusercontent.com/20990100/29075389-9c1204e2-7c28-11e7-94ed-5a89ec23b76b.png)

Horizontal
![image](https://user-images.githubusercontent.com/20990100/29075391-9de659b2-7c28-11e7-8f59-c97fe7e1ac8d.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não é possível obrigar a rotação de tela do navegador, ainda que fosse, não seria uma boa prática. Sobre exibir a mensagem, não é usual esse tipo de instrução na web para mobile. A solução para tabelas em mobile que utilizamos, que é a utilizada geralmente, é permitir o scroll horizontal, que é o que já ocorre. Embora não seja usual, caso queira exibir a mensagem de qualquer forma, podemos inserir sim.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho no futuro teremos que melhorar isso, por enquanto, vamos exibir esta mensagem aqui e no Criar Orçamento.

Fico envergonhado que ter um site com uma experiência de uso tão ruim no celular. Com a mensagem vou me sentir melhor...

**Comment by raphaelMCarvalho** [comment]
@lucasretondo é o preço que se paga pela utilização de tabelas, infelizmente. Vamos colocar então.
