### ISSUE TITLE
Calculadora Coluna - Tela inicial

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#519]
Por que o campo comprimento esta em cinza e diferente dos demais?

![image](https://user-images.githubusercontent.com/20990100/29120601-67fb76d4-7ce1-11e7-9251-bcb6bc43d398.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo porque de acordo com as regras recebidas, a lista de valores de comprimento depende do que o usuário selecionar da lista de largura.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho entendi.
