### ISSUE TITLE
Orçamento Recebido - Navegação das formas de pagamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#52]
Esta muito ruim a navegabilidade das formas de pagamento.

![image](https://cloud.githubusercontent.com/assets/20990100/18190919/6cce7154-709c-11e6-9c53-0d7491133791.png)

**Comment by raphaelMCarvalho** [comment]
Acredito que essa issue não deveria ser registrada como bug. Foi seguido o layout. Vamos discutir esse enhancement, podemos pensar juntos em alternativas de navegação.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho a navegabilidade que esta ruim, por exemplo

É possível clicar em duas opções de pagamento que ficam sobrepostas...
![image](https://cloud.githubusercontent.com/assets/20990100/18458838/153e4098-793b-11e6-9d70-afab8d9682be.png)

Hoje o usuário ao clicar no "+" é obrigado a clicar na forma de pagamento para voltar, quando o ideal seria abrir a formas ao passar o mouse sobre o "+" e mudar somente quando o usuário clicar sobre a nova opção. Vamos colocar como feedback para usuário sublimar o texto ao passar o mouse.

Boleto não tem parcelado...
![image](https://cloud.githubusercontent.com/assets/20990100/18458886/885daa6e-793b-11e6-91c2-7238aea1401a.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo se mudarmos para que as opções abram somente quando o usuário passar com o mouse, estaremos automaticamente impedindo que usuários com touch screen utilizem essa funcionalidade.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não tinha pensando nisso, para o touch não existe outra solução?

No Explorar ficou bizarro...

![image](https://cloud.githubusercontent.com/assets/20990100/18496034/c2d0e752-79f8-11e6-87c7-c3ecfc23537a.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo qual a versão do Internet Explorer? A opção para o touch é usar toque, já que não há hover

**Comment by lucasretondo** [comment]
@raphaelMCarvalho dado que não podemos eliminar o clique a minha sugestão é:
1) Abrir as opções de pagamento quando usuário clicar no "+"
2) Abrir as parcelas somente quando o usuário clicar e deixar o meio de pagamento selecionado
3) Permitir que o usuário volte (não mudando a forma de pagamento original) ao clicar em qualquer lugar da página fora das forma de pagamento

**Comment by raphaelMCarvalho** [comment]
@lucasretondo por que bug?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho é muito complexo fazer esta melhoria?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo da forma como está descrita acima a complexidade é baixa

**Comment by lucasretondo** [comment]
@raphaelMCarvalho é fácil aumentar o espaço onde podemos clicar com o mouse para abrir a caixa com as opções de pagamento?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo foram removidas as opções de parcelamento, e mantida a navegação por clique.
