### ISSUE TITLE
Calculadora Coluna - Trocar a descrição do ferro cortado e dobrado para aço na Lista de compras

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#522]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Etapa Aço por Projeto estrutural->Resumo do aço->Lista de compras.

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Na Lista de Compras aparece a descrição do produto como "Ferro cortado e dobrado CA-50,kg" ou "Ferro cortado e dobrado CA-60, kg" e seria melhor se aparecesse "Aço cortado e dobrado CA-50,kg" ou "Aço cortado e dobrado CA-60,kg".

## 3. Captura de tela de como está hoje

![image](https://user-images.githubusercontent.com/30830371/29124022-025cd0ea-7cee-11e7-9203-3c6d770bec89.png)

## 4. Captura de tela de como deve ficar após a melhoria (se a descrição detalhada for clara e precisa, esse passo é opcional)

![image](https://user-images.githubusercontent.com/30830371/29124209-a41f47fa-7cee-11e7-94bf-ef284113c8de.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho o produto "Aço cortado..." já existe e é utilizado no cálculo das opções "resumo do aço" e "não sei".

Vou te mandar uma nova versão da planilha no slack para deixar documentado.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho Esta aparecendo na Lita de compras, obrigada.
