### ISSUE TITLE
Calculadora Coluna - Botão de Voltar na Lista de Compras

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#525]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Lista de Compras e acionar o botão Voltar.
Navegador Chrome.

## 3. Descrição do que ocorreu

Estava ontem testando a calculadora, na página da Lista de Compras quando eu clicava em Voltar a calculadora me redirecionava a página anterior de cálculo, voltava uma etapa e estava certinho das seleções que eu fiz. 
Fui testar agora de manha e na página da lista de compras eu cliquei no botão Voltar 1 vez e não funcionou, cliquei mais 1 vez e fui redirecionada para a página de Qual o tamanho dos estribos, mas eu tinha selecionado antes a opção de aço por projeto estrutural (resumo do aço e selecionado por peso, kg).

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Não conseguimos reproduzir o problema, mas suspeitamos que esta anomalia esteja relacionada a um bug que encontramos e resolvemos esta tarde. Faça novos testes para tentar reproduzir o problema na versão mais recente, mas acreditamos que esteja resolvido.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho Pelo que vi ontem e hoje foi corrigido mesmo.
