### ISSUE TITLE
Calculadora Coluna - Calculadora esta reiniciando de acordo com certos dados introduzidos.

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#529]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

"Como irá comprar o aço"

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Após escolher alguma opção de como comprar o Aço deveria passar para a próxima etapa da opção escolhida. Exemplo: Se fosse "Conforme Projeto estrutural" seguisse para a página do Resumo do aço.

## 3. Descrição do que ocorreu

Ao clicar em "Próxima etapa" a calculadora voltou para a página inicial.

## 4. Captura de tela

[Insira as imagens aqui]
Não tenho foto, mas tenho vídeo se quiserem.
## 5. Passos para reproduzir a ocorrência

Primeira página: Largura de 15; Comprimento; 40; Altura 3,00; Quantidade: 4 .
Opção de concreto escolhida: Concreto Usinado
Como irá comprar o aço: Nessa etapa não importa qual das 3 opções eu clicar a calculadora me redireciona ao apertar o botão "Próxima etapa" para a página inicial.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Por favor limpe todos os dados de navegação do seu navegador e tente novamente reproduzir a ocorrência. Caso ainda ocorra, passe pra gente qual o navegador e a versão.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Realizei testes e identifiquei o problema, realmente está acontecendo. Vamos propor uma solução nessa sexta-feira.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Por favor limpe o cache e teste novamente, subimos uma correção para o problema.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho eu limpei e testei a calculadora parou de reiniciar, mas não aparece opção de aço na lista de compra. Até cadastrei outra issue, desculpa.
