### ISSUE TITLE
Menu trocado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#53]
Fiz o login com o lojista pdcc.parceiro2@mailinator.com. Passei pelas telas abaixo a acabei com o menu lateral do consumidor.

![image](https://cloud.githubusercontent.com/assets/20990100/18191000/2e6bfbba-709d-11e6-8830-248fb718b799.png)

Não deveria cair na página com o check list para confirmar a entrega?
![image](https://cloud.githubusercontent.com/assets/20990100/18191005/3cab6a1c-709d-11e6-9af2-575cbc003041.png)

Cliquei em voltar e fui para o menu do consumidor...
![image](https://cloud.githubusercontent.com/assets/20990100/18191030/8556d0f8-709d-11e6-883b-bda9ee2be243.png)

**Comment by lucasretondo** [comment]
outra vez.
![image](https://cloud.githubusercontent.com/assets/20990100/18191237/26e42d34-709f-11e6-8fa0-1d5523ec602d.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18191243/310aa018-709f-11e6-9899-f428b3d617d2.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo resolvido.
