### ISSUE TITLE
Calculadora Colunas - Posição figura - Medidas estribo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#530]
Colocar a figura antes dos campos das medidas.

![image](https://user-images.githubusercontent.com/20990100/29223685-dcd60df8-7e9d-11e7-87c6-b32a70d6494f.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Tem mais alguma página que você gostaria de fazer isso?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho na calculadora de colunas tem a tela de dimensões de estribos, mas para essa eu abri uma nova issue #530.

Como vc quer que eu documente isso nas próximas calculadoras?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Pode ser assim mesmo, é que se tivesse mais alguma a gente já fazia junto nesse pacote
