### ISSUE TITLE
Calculadora Coluna - Lista de compra sem informações de Aço 

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#531]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Etapa final - Lista de Compras.
Google chrome.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Aparecesse na lista a opção de "Aço cortado e dobrado CA-50, kg" ou  "Vergalhão de aço CA-50, barra 12 m"e "Vergalhão de aço CA-60, barra 12 m" ou  "Aço cortado e dobrado CA-50, kg" e  "Aço cortado e dobrado CA-60, kg".

## 3. Descrição do que ocorreu

Na lista de compra não aparece opção de aço.

## 4. Captura de tela

![image](https://user-images.githubusercontent.com/30830371/29223544-511463c8-7e9d-11e7-8e40-e0515fa0819f.png)

## 5. Passos para reproduzir a ocorrência

1-Limpei o cache, depois abri a calculadora. Introduzi 15 cm de Largura, 40 cm de Comprimento, 3 metros de Altura e 4 Quantidades. Selecionei Concreto pronto (usinado), depois "Conforme Projeto Estrutural". Na página de resumo do aço: CA-50, 8mm(5/16"), peso, 50. E na lista de compra não apareceu o Aço.
2-Limpei o cache novamente, depois abri a calculadora. Introduzi 15 cm de Largura, 40 cm de Comprimento, 3 metros de Altura e 4 Quantidades. Selecionei Concreto pronto (usinado), depois "Cortar e dobrar na obra"; 8mm (5/16"); 6 barras; 4,2mm. Na página de "Qual o tamanho dos estribos": 9 cm de Largura; 34 cm de Comprimento e 20 cm de espaçamento. Não apareceu o aço na lista de compra.
3- Limpei o cache novamente, depois abri a calculadora. Introduzi 15 cm de Largura, 40 cm de Comprimento, 3 metros de Altura e 4 Quantidades. Selecionei Concreto pronto (usinado), depois "Não sei ainda" e não apareceu aço na lista de compra.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho parece que voltou pro problema antigo de reiniciar...

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida a cada atualização eu preciso invalidar o cache do arquivo modificado, ficou faltando atualizar um. Veja agora.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho testei ontem e hoje, pareceu ok! Obrigada!
