### ISSUE TITLE
Calculadora Coluna - No Internet Explorer carregar a lista de compra

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#532]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Etapa final-Lista de compra
## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Carregasse a planilha de lista de compra com os materiais, unidades e quantidades.

## 3. Descrição do que ocorreu

Mostra o cabeçalho da lista de compras, mas não mostra o resto.

## 4. Captura de tela

![image](https://user-images.githubusercontent.com/30830371/29224621-7ce9964a-7ea1-11e7-842b-2818ef02faae.png)

## 5. Passos para reproduzir a ocorrência

Limpei o cache do internet Explorer. Na primeira página coloquei de medidas: 20 Largura, 30 Comprimento, 3,2 de Altura e 15 quantidade. Selecionei concreto pronto (usinado) e depois selecionei "Não sei ainda" para o aço. E na última pagina não carregou a  planilha, mesmo depois de alguns minutos ficou assim como na figura que anexei.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida @lucasretondo Vimos que o motivo do problema é a falta de suporte do IE 11 a algumas funções que utilizamos no Javascript. Lucas, você teria como ver nos relatórios do Google Analytics qual o percentual de visitas com esta versão de navegador? Especificamente o IE 11, não o Edge. Sugiro analisarmos esse percentual e com base nele decidir se devemos dar o suporte, pois essa mudança para termos compatibilidade vai demandar algumas horas. Se houver um percentual considerável de visitas, por exemplo superior a 10%, isso justificaria essa refatoração.
No market share o IE 11 aparece com baixo percentual em comparação a outros navegadores:
https://www.w3counter.com/globalstats.php

**Comment by lucasretondo** [comment]
@raphaelMCarvalho e @JuliaAlmeida o IE representa menos de 2% dos usuários.
