### ISSUE TITLE
Cadastro Lojista - Email de configuração de senha não recebido. 

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#533]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Usando o Google Chrome no pdcc.
Final do cadastro de Lojista "Cadastro Parceiro".

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

O "lojista" recebesse um email para configuração de senha no email cadastrado.

## 3. Descrição do que ocorreu

Não recebi nenhum email ao cadastrar um lojista para o email : lojatoulouse@mailinator.com ; almeidatoulouse@mailinator.com e para martellatoulouse@mailinator.com

## 4. Captura de tela

![image](https://user-images.githubusercontent.com/30830371/29289543-3d853c9c-8113-11e7-9d8e-762cd5217dd2.png)
![image](https://user-images.githubusercontent.com/30830371/29290013-003320a0-8115-11e7-90b5-850256d8bb28.png)

## 5. Passos para reproduzir a ocorrência

Realizar o cadastro de novo lojista "parceiro" com um email "mailinator.com".

## 6. Dados envolvidos na ocorrência (e-mails dos usuários)

lojatoulouse@mailinator.com ;
 almeidatoulouse@mailinator.com ;
martellatoulouse@mailinator.com  .

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida o envio de e-mails para endereços que não sejam @mailinator funciono? Digo isso pois como se trata de envio e recebimento de mensagens, o problema pode não estar na API do Pra Construir

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho  testei com meu pessoal do msn.com e também não recebi.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Revisei e me lembrei que na development tivemos uma mudança quanto ao envio de e-mails. É preciso que você passe o e-mail para nós por mensagem para que autorizemos o envio de mensagens para ele antes de realizar cadastros. Isso se faz necessário porque no ambiente da homolog o envio de mensagens se dá através de uma sandbox, com caráter apenas de testes de homologação.
