### ISSUE TITLE
Negociação - Mensagem com nome errado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#534]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Ao enviar a mensagem no pedido (status negociação).

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Na visão do lojista as mensagens enviadas pelo cliente deveriam ter o nome "Cliente" e não "Você". E nas mensagens enviadas pelo lojista deveria aparecer o nome "Você" e não o nome da loja.

## 3. Descrição do que ocorreu

Não mudou os nomes conforme acima e na primeiro vez que a loja respondeu ficou "Você", mas depois mudou para o nome da loja.

## 4. Captura de tela

![image](https://user-images.githubusercontent.com/20990100/29461214-3eaeadf6-8401-11e7-90fd-220869435f9f.png)

![image](https://user-images.githubusercontent.com/20990100/29461239-5690aaa0-8401-11e7-8b15-176cc52013da.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Acabei de testar com um novo pedido e as mensagens do lojista continuam com o nome cliente.

![image](https://user-images.githubusercontent.com/20990100/29487606-7c7ac92c-84d2-11e7-922a-42aa6328fe5e.png)

**Comment by raphaelMCarvalho** [comment]
![captura de tela 2017-08-28 as 00 07 41](https://user-images.githubusercontent.com/20994342/29757850-69446ab6-8b85-11e7-9c95-9be76bbb8abf.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Aparentemente não tem mais a troca, mas assim que o lojista ou cliente enviam a mensagem, não aparece nada:

![image](https://user-images.githubusercontent.com/20990100/29775407-6f1e54aa-8bdb-11e7-8d13-f2dae94dfcb6.png)

![image](https://user-images.githubusercontent.com/20990100/29775409-71b42a1e-8bdb-11e7-91f5-7c6341f9f75b.png)

O nome só aparece depois que o usuário sai e volta para o pedido:

![image](https://user-images.githubusercontent.com/20990100/29775435-8358c504-8bdb-11e7-9d53-b46de1cb3081.png)

![image](https://user-images.githubusercontent.com/20990100/29775438-85da935c-8bdb-11e7-8f8c-c803591ef638.png)

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho parece que estar ok:
![image](https://user-images.githubusercontent.com/30830371/29836694-51367ff2-8ccc-11e7-8800-560cf77fc634.png)
