### ISSUE TITLE
Negociação - O status "Aguardando resposta" não esta no Meu Resumo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#535]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Após solicitar o orçamento.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Que o orçamento com status "Aguardando resposta" aparece-se no Meu Resumo.

## 3. Descrição do que ocorreu

O orçamento 962 não esta aparecendo no Meu Resumo.

## 4. Captura de tela

![image](https://user-images.githubusercontent.com/20990100/29463101-dea1ba32-8407-11e7-8be0-d6d126c58dc7.png)

![image](https://user-images.githubusercontent.com/20990100/29463106-e3ea0972-8407-11e7-8685-f98099290ae7.png)

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho  testei hoje, não aparece orçamento "Agradando resposta" no meu resumo. Nem no site e nem no APP (Android).
![image](https://user-images.githubusercontent.com/30830371/29487469-dff831d6-84cf-11e7-8e6a-da5567fb5cac.png)
![image](https://user-images.githubusercontent.com/30830371/29487470-e81ae822-84cf-11e7-9b34-28a4c411e3e4.png)
![image](https://user-images.githubusercontent.com/30830371/29487488-5103389e-84d0-11e7-9800-a2d7a8afb182.png)
![image](https://user-images.githubusercontent.com/30830371/29487490-5fb148fe-84d0-11e7-8641-19891f60fadd.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho e @JuliaAlmeida acabei de testar novamente e agora na web esta aparecendo, mas no Android e iOS não.

![image](https://user-images.githubusercontent.com/20990100/29487561-83eb4200-84d1-11e7-80da-221f9f631be4.png)

**Comment by lucasretondo** [comment]
Criei uma nova issue no repositório do App, assim vou fechar esta issue.
