### ISSUE TITLE
Negociação - Confirmar o pedido ao clicar no e-mail

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#538]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Quando o lojista recebe o e-mail com um novo pedido.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Ao clicar no botão o lojista deveria ir para a página para iniciar a negociação sem confirmar o pedido.

## 3. Descrição do que ocorreu

Ao clicar no botão pedido o sistema esta confirmando o pedido sozinho.

## 4. Captura de tela

![image](https://user-images.githubusercontent.com/20990100/29487802-bd49fa4c-84d5-11e7-83ab-41744cfbb6fc.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não é um bug, é um comportamento anterior que foi solicitado, de ao clicar no link o pedido ser confirmado automaticamente. Essa parte de negociações relativas à API e envio de e-mails e push **ainda não subiram para o servidor**.
