### ISSUE TITLE
Resposta Orçamento - Melhorar layout

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#539]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Quando o lojista esta respondendo um orçamento.

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Diminuir a distância das mensagens com a tabela principal e colocar o nome das colunas.

## 3. Captura de tela de como está hoje

![image](https://user-images.githubusercontent.com/20990100/29521135-909c8ad8-865a-11e7-9ba6-b36e0dff7548.png)

## 4. Captura de tela de como deve ficar após a melhoria (se a descrição detalhada for clara e precisa, esse passo é opcional)

![image](https://user-images.githubusercontent.com/20990100/29521181-c9fe6e0e-865a-11e7-901a-a9bdd3a43af0.png)

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho acabei de testar com orçamento #1003, continua sem o nome nas colunas para o lojista.
![image](https://user-images.githubusercontent.com/30830371/29583051-33065498-8755-11e7-8c55-99d7037d3ac1.png)
Para o cliente esta assim:
![image](https://user-images.githubusercontent.com/30830371/29583074-48b5f046-8755-11e7-9877-d0020d0833bb.png)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Certifique-se sempre de que não está com cache no navegador. Quanto à tela do cliente, não foi solicitada mudança nela, mas na tela do lojista.

![captura de tela 2017-08-22 as 16 17 45](https://user-images.githubusercontent.com/20994342/29583167-8cbbf420-8755-11e7-8116-9f884e56ed5c.png)

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho  estou estranhando que limpei tudo antes de começar o teste...
Era só pra mostrar como os dois estavam pra mim.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Pode acontecer às vezes de uma atualização estar disponível para alguns usuários e para outros ainda não dependendo da região. Isso ocorre porque estamos usando o CloudFront da Amazon pra entrega do frontend web. A Amazon chama essas regiões de "regiões de disponibilidade". Nisso quando atualizamos, informamos o CloudFront que queremos limpar o cache de arquivos específicos, e isso vai se propagando pelas regiões, a princípio é quase instantâneo, mas não temos garantia.

https://aws.amazon.com/pt/cloudfront/

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho agora apareceu para mim a mudança! Obrigada
