### ISSUE TITLE
Tabela resumo errada

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#54]
Fiz o login e cliquei em Meu Pedido e caiu na tela abaixo sem o botão confirmar
![image](https://cloud.githubusercontent.com/assets/20990100/18191092/004502d0-709e-11e6-863f-a5748c0ab1a0.png)

Depois de clicar na linha caiu na tela correta
![image](https://cloud.githubusercontent.com/assets/20990100/18191104/168521e2-709e-11e6-81ee-170569ea9471.png)

**Comment by raphaelMCarvalho** [comment]
Colocamos um passo anterior à Confirmar entrega, em que o lojista confirma o pedido e então pode confirmar a entrega. Do lado do cliente, ele vê que está aguardando a confirmação do pedido e em seguida aguardando a entrega. Particularmente acho interessante esse passo de confirmação, para daí contar o tempo da entrega. Mas podemos alterar.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vamos colocar para votação junto com o Weslley, eu inicialmente pensava igual você, mas depois de discutir com ele chegamos no consenso de eliminar esta etapa.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo achamos que esse status é necessário no fluxo dos pedidos. A realização do pedido pelo cliente não significa automaticamente que haverá uma entrega pelo lojista, assumir isso é exibir informações para o cliente que podem não condizer com a verdade.
