### ISSUE TITLE
Negociação - Esta notificando quem manda a mensagem

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#543]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Ao enviar uma mensagem no pedido.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Quando o cliente envia a mensagem é esperado que a loja recebe-se a notificação, e vice-versa.

## 3. Descrição do que ocorreu

Quando o cliente manda a mensagem ele este recebendo a notificação, e a loja não.

## 5. Passos para reproduzir a ocorrência

Cliente manda mensagem
![image](https://user-images.githubusercontent.com/20990100/29619836-82d9cb24-87f2-11e7-8501-fec65abca386.png)

Cliente recebe a notificação
![image](https://user-images.githubusercontent.com/20990100/29619859-9200330e-87f2-11e7-9c8d-a3833c52785e.png)

Lojista não recebe
![image](https://user-images.githubusercontent.com/20990100/29619878-9dd0c4c8-87f2-11e7-8cf4-44b35ac323fe.png)

A mesma inversão ocorre quando a loja manda mensagem.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho esta inversão tb esta ocorrendo nas mensagens do orçamento.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho quando o cliente responde mensagem de orçamento pelo celular, nem ele e nem a loja recebem email de nova dúvida no orçamento.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho testei agora pouco. Lojista (Julia Toulouse- QueroObras) mandou uma mensagem na negociação para o cliente (Jose Toulouse). No email que o cliente recebe notificando a mensagem o texto esta colocando o nome do lojista no lugar onde era pra ser o nome do cliente e ao tentar abrir o link "RESPONDER" abre uma página de erro.
![image](https://user-images.githubusercontent.com/30830371/29643178-d9567924-8843-11e7-9462-a866fce154e1.png)
![image](https://user-images.githubusercontent.com/30830371/29643206-005d8440-8844-11e7-9d41-c21d533f70de.png)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida isso ocorreu na fase de orçamento ou na negociação? Há as mensagens em duas áreas, na de orçamentos e na de negociação/pedido.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho na fase de negociação.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho agora aconteceu na fase de orçamento. Lojista Julia Toulouse (QueroObras) mandou uma dúvida no orçamento do Cliente Jose Toulouse. Cliente recebeu esse email:
![image](https://user-images.githubusercontent.com/30830371/29683483-ebaabeae-88e4-11e7-956b-b404c32dade3.png)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida como o problema foi apontado na negociação, acabei não verificando se na fase de orçamento poderia estar ocorrendo o mesmo. Vou verificar agora.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Pronto. Caso você identifique algum outro problema nas mensagens que não se encaixe na descrição dessa issue, sugiro criar novas issues pra não alongarmos muito nesta.
