### ISSUE TITLE
Orçamento - Cliente aparentemente não consegue responder dúvida do orçamento

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#546]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Orçamento enviado, cliente na aba de mensagens do orçamento para responder dúvida do lojista.
APP-ANDROID ASUS ZENFONE

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Ao clicar no botão de enviar a mensagem demonstrasse que a mensagem foi enviada.

## 3. Descrição do que ocorreu

Cliente abriu o orçamento 986 no celular. Abriu a aba de Mensagens e foi responder a dúvida do lojista. Aparenta que a mensagem não foi enviada. Cliquei em voltar e depois abri novamente o orçamento 986 no celular e na aba de Mensagens estava a mensagem enviada.

## 4. Captura de tela

![image](https://user-images.githubusercontent.com/30830371/29626151-409a3bb0-8804-11e7-9067-02d8578ca5ac.png)

Ao abrir novamente o orçamento na aba de mensagem:

![image](https://user-images.githubusercontent.com/30830371/29626176-53a25e9a-8804-11e7-89f9-ec77757bc22e.png)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida @lucasretondo Só uma correção: esta issue não diz respeito à negociação; não foi realizada nenhuma mudança nesta tela no Android, apenas o título da aba que agora ficou "Mensagens". O layout das mensagens dos Pedidos, este sim, foi modificado.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Agora me dei conta de que essa issue é do mobile. Com seu acesso aí você consegue mover para a outra área? Valeu!

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não consigo mover a issue, vamos ter que fechar e criar uma nova.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo beleza, você pode criar lá na área mobile, @JuliaAlmeida ? Obrigado
