### ISSUE TITLE
Notificação - Mensagem de "Falhamos com você" logo após cliente enviar orçamento.

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#549]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Logo após que o cliente pediu o orçamento #1101.

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Somente os lojistas recebessem um email com "Novo Orçamento".

## 3. Descrição do que ocorreu

Lojistas receberam a mensagem de "Novo orçamento".
Cliente recebeu notificação no celular (ANDROID) e email no computador com assunto "Falhamos com você"

## 4. Captura de tela

Orçamento:
![image](https://user-images.githubusercontent.com/30830371/29773749-26326b6a-8bd5-11e7-87b8-43b69d7161b4.png)
Email cliente recebeu:
![image](https://user-images.githubusercontent.com/30830371/29773764-37be6186-8bd5-11e7-9240-e9d16526c107.png)
Notificação no celular:
![image](https://user-images.githubusercontent.com/30830371/29773836-7a772f58-8bd5-11e7-8ef4-fa1711186205.png)

## 5. Passos para reproduzir a ocorrência

No celular (ANDROID) fiz o login para o cliente 5 (Jose Toulouse) e reenviei o orçamento 1101.

## 6. Dados envolvidos na ocorrência (e-mails dos usuários)

cli5@mailiantor.com

**Comment by raphaelMCarvalho** [comment]
Sabe dizer com base nos seus testes se isso acontece apenas quando se solicita produtos que não existem ou não são cadastrados, como esse da captura de tela?

Enviado do meu iPhone

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho tenho outro orçamento que é de produto não cadastrado. Orçamento #996 que é de produto : Não responder. Medida: Nada. Quantidade : 1. E para ele não tive essa reação no sistema.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida @lucasretondo vocês conseguem recriar esse problema? Não consegui aqui

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida @lucasretondo Revisei o código que envolvia essa operação e identifiquei um ponto em que tal anomalia poderia acontecer. Subi uma atualização que faz uma alteração nesse ponto, acredito que não ocorra mais, porém não tenho como reproduzir a issue para me certificar completamente.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho o orçamento que deu esse problema expira para o cliente hoje as 14, depois disso posso tentar reenviar.

**Comment by raphaelMCarvalho** [comment]
Ótimo, geralmente expira entre 14h00 e 14h01

Enviado do meu iPhone

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho reenviei o orçamento e não ocorreu o "erro".
