### ISSUE TITLE
Avaliar lojista não funciona

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#55]
![Uploading image.png…]()

![image](https://cloud.githubusercontent.com/assets/20990100/18191207/e3d8b9b0-709e-11e6-86b4-c55148f478f0.png)

**Comment by raphaelMCarvalho** [comment]
Issue duplicada, o problema já é mencionado na issue #34

**Comment by raphaelMCarvalho** [comment]
@lucasretondo por favor feche esta issue duplicada.
