### ISSUE TITLE
Calculadora - Sumiu o ícone

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#551]
Sumiu o ícone do blog.

![image](https://user-images.githubusercontent.com/20990100/30031376-76a25e9c-9167-11e7-9e09-2960050c87b2.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Em qual tela, qual calculadora? Testando aqui está aparecendo

![captura de tela 2017-09-04 as 11 55 53](https://user-images.githubusercontent.com/20994342/30031484-11c98350-9168-11e7-9488-96c769ae5e84.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho estou na viga.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho realmente a coluna e viga baldrame estão normais.

**Comment by raphaelMCarvalho** [comment]
Acessei na viga, está aparecendo normalmente.

![captura de tela 2017-09-04 as 11 59 18](https://user-images.githubusercontent.com/20994342/30031597-8a7d0588-9168-11e7-8c46-46c1b2229ffd.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Testado no Safari e Google Chrome.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Você não estaria com algum problema de cache aí?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho blz, vou limpar o cache e testar depois, valeu.

**Comment by raphaelMCarvalho** [comment]
Invalidando pois trata-se de cache do navegador no ambiente de homologação.
