### ISSUE TITLE
Criar Pedido - Mudar cor preenchimento frete

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#558]
Não é melhor colocar a cor do preenchimento do campo do frete com cinza claro igual aos descontos?

![image](https://user-images.githubusercontent.com/20990100/30289342-3f1f0f42-9702-11e7-88a7-eaf81336e667.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo A gente discutiu aqui no momento em que estávamos definindo a tela e acreditamos que é importante deixar o valor do frete separado dos demais valores nessa tabela; os cinza claros fazem parte da otimização que o usuário visualiza, já o frete, não.

**Comment by lucasretondo** [comment]
Entendi...





---- On Seg, 11 set 2017 15:43:46 -0300 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo A gente discutiu aqui no momento em que estávamos definindo a tela e acreditamos que é importante deixar o valor do frete separado dos demais valores nessa tabela; os cinza claros fazem parte da otimização que o usuário visualiza, já o frete, não.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Vamos fechar esta issue?

**Comment by lucasretondo** [comment]
Sim.









---- On Sex, 22 set 2017 11:29:01 -0300 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo Vamos fechar esta issue?
