### ISSUE TITLE
Criar Pedido - Incluir valor de frete na coluna de "Pedido em R$" para escolha de 1 loja.

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#559]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Verificar orçamentos -> Escolher loja para iniciar negociação.
Google Chrome.

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Adicionar o valor do frete quando o cliente selecionar os produtos de uma loja só na coluna de "Pedido em R$".

## 3. Captura de tela de como está hoje

![image](https://user-images.githubusercontent.com/30830371/30293707-d544c526-9710-11e7-8c3c-c95fdab47576.png)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Checou se não é cache do navegador? Aqui apareceu

![captura de tela 2017-09-11 as 17 09 47](https://user-images.githubusercontent.com/20994342/30294613-174f1f0e-9714-11e7-957a-5c5122ad930d.png)

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho chequei sim, limpei tudo duas vezes. Pode ser por que eu tive três lojas para escolher?

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Improvável, mas vou checar.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Consegui reproduzir o problema, pra mim aconteceu apenas quando cliquei para otimizar por menor número de lojistas ou melhor avaliação. Quando se escolhe menor custo não acontece, ou se é uma escolha manual.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho eu tinha um orçamento só com dois lojistas. Aparece na coluna quando eu clico somente no produto. Se eu clico no otimizador e o otimizador me dá uma loja só, não aparece na coluna.

**Comment by raphaelMCarvalho** [comment]
![captura de tela 2017-09-12 as 16 21 30](https://user-images.githubusercontent.com/20994342/30344145-80b95500-97d6-11e7-8624-dc284966cc37.png)
