### ISSUE TITLE
Pedido já finalizado volta para confirmar entrega

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#56]
Segue o passo a passo.

![image](https://cloud.githubusercontent.com/assets/20990100/18191271/871fa2be-709f-11e6-895d-a84efc0b8cea.png)

Os botões para confirmar entrega estavam vazios, selecionei e cliquei em voltar
![image](https://cloud.githubusercontent.com/assets/20990100/18191296/ad1c1830-709f-11e6-9d81-38393abaf552.png)

O status volta para confirmar entrega
![image](https://cloud.githubusercontent.com/assets/20990100/18191300/b14fa16a-709f-11e6-964a-8f317988ea51.png)

Depois de clicar sobre o botão confirmar
![image](https://cloud.githubusercontent.com/assets/20990100/18191317/ce4c8f94-709f-11e6-868f-56e80e42c3df.png)

E acabou no menu lateral do cliente
![image](https://cloud.githubusercontent.com/assets/20990100/18191327/e5b23666-709f-11e6-96b9-9e474af97c14.png)

Tá difícil, vou dormir...

**Comment by raphaelMCarvalho** [comment]
Issue duplicada, problema já mencionado na issue #53

**Comment by raphaelMCarvalho** [comment]
@lucasretondo por favor feche esta issue duplicada.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho pq eu devo fechar, são problemas diferentes, concorda?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo na verdade não, esse bug se relaciona não somente à issue #53 , mas a outro bug que resultou no cadastro da issue #34 .
