### ISSUE TITLE
Cadastro simplificado - Usuário não recebeu email de confirmação de cadastro

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#561]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Finalização do cadastro simplificado.
Google Chrome.

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

De acordo coma figura abaixo o novo usuário deveria recebeu um email de confirmação.
Esse email de confirmação não foi recebido para o usuário novo: cli20@mailinator.com como também para o clientejulia@mailinator.com
Emails sobre dúvida de orçamento, nova mensagem na negociação e pedido confirmado foram recebidos pelos usuários.

## 3. Captura de tela de como está hoje

![image](https://user-images.githubusercontent.com/30830371/30618818-7dcfb126-9d72-11e7-91f3-569b67788999.png)

**Comment by raphaelMCarvalho** [comment]
A mensagem está incorreta, vamos modificá-la, o usuário não recebe e-mail ao se cadastrar informando a senha.

**Comment by raphaelMCarvalho** [comment]
![captura de tela 2017-09-20 as 12 51 08](https://user-images.githubusercontent.com/20994342/30653789-6d265862-9e02-11e7-991f-78cf1bb5590d.png)

**Comment by raphaelMCarvalho** [comment]
Fechando esta issue já que esta tela passou a não existir mais na última atualização, e usuários que se cadastram com senha não recebem e-mail.
