### ISSUE TITLE
Cadastro Simplificado - Direcionar para a tela de criar orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#563]
Após o usuário clicar em "Entrar" na tela onde tem a mensagem de e-mail cadastro com sucesso, ao invés direcionar o usuário para a tela de login, é possível já habilitar o usuário e levar ela para a página criar orçamento?

**Comment by raphaelMCarvalho** [comment]
É possível sim, vamos fazer
