### ISSUE TITLE
Cadastro Simplificado - As cidades não conferem com o estado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#564]
A lista de cidades não atualiza após mudar o estado:

![image](https://user-images.githubusercontent.com/20990100/30619847-49ae541e-9d78-11e7-9a63-339e83580e94.png)

**Comment by lucasretondo** [comment]
Ao selecionar o estado pela primeira vez não exibe a lista de cidades. Será que esta relacionado com anterior?

![image](https://user-images.githubusercontent.com/20990100/30619913-9e7f1578-9d78-11e7-94d4-f5ee4b4c68ca.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Há um intervalo de tempo de carregamento ao selecionar o Estado, vamos desabilitar o campo enquanto ocorre o carregamento.
