### ISSUE TITLE
Cadastro Simplificado - Não é possível salvar obra com CEP inválido

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#565]
Não é possível salvar uma obra com o CEP inválido, pq?

![image](https://user-images.githubusercontent.com/20990100/30620005-2224de62-9d79-11e7-8409-693a08e5ea32.png)

**Comment by raphaelMCarvalho** [comment]
Porque o CEP é inválido. Ou o usuário preenche um CEP válido ou não preenche, já que não é obrigatório.

Enviado do meu iPhone

Em 19 de set de 2017, à(s) 20:28, lucasretondo <notifications@github.com> escreveu:

**Comment by lucasretondo** [comment]
Ok, não fique bravo... ahahahha
