### ISSUE TITLE
Cadastro Simplificado - Número não é obrigatório?

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#566]
Pq o número não é mais obrigatório?

![image](https://user-images.githubusercontent.com/20990100/30620018-3c9824ac-9d79-11e7-997f-9085140bbab3.png)

Se formos manter como não obrigatório, vamos ter que tratar o endereço exibido no orçamento, note que o número aparece como "undefined"

![image](https://user-images.githubusercontent.com/20990100/30620040-5be602e8-9d79-11e7-89ee-968f33672b30.png)

**Comment by raphaelMCarvalho** [comment]
O Claudinei levantou que alguns endereços podem não possuir número, por isso retiramos a obrigatoriedade. Vamos corrigir esse undefined então, pode ser?

**Comment by lucasretondo** [comment]
Vamos ter que corrigir isso em todas as telas, não é mais fácil deixar obrigatório?

**Comment by raphaelbluteau** [comment]
@lucasretondo Pela manhã a gente alinha com o Claudinei daí batemos o martelo então
