### ISSUE TITLE
Calculadora Sapata - Alterar formato altura

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#567]
A altura da sapata é em "cm" e não "m" e não devemos exibir as duas casas decimais.

![image](https://user-images.githubusercontent.com/20990100/30766758-a7f92be6-9fcd-11e7-8c71-e2645eaccc17.png)

**Comment by raphaelMCarvalho** [comment]
![image](https://user-images.githubusercontent.com/20994342/30774606-a948d760-a05b-11e7-91bc-b38fd83b15ac.png)

**Comment by lucasretondo** [comment]
Sorry, o requirimento esta errado.





---- On Sáb, 23 set 2017 12:35:26 -0300 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----
