### ISSUE TITLE
Calculadora Sapata - Requisito para opção de armação pronta

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#584]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Escolha como irá comprar o aço

## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Não aparecesse a opção de Armação pronta.
Pois inseri Largura de 80 cm e comprimento de 100 cm

## 4. Captura de tela

![image](https://user-images.githubusercontent.com/30830371/30879865-1742582c-a2d7-11e7-92de-60bda4466c86.png)

## 5. Passos para reproduzir a ocorrência

Largura: 80 cm
Comprimento 100 cm
Altura: 100 cm
19 unidades
Topo reto
Sem broca
Concreto Usinado

**Comment by JuliaAlmeida** [comment]
A opção de armação pronta também aparece para quando seleciono comprimento maior do que 120 cm.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Orequisito especifica a regra conforme o print abaixo:
![pasted image at 2017_09_26 04_43 pm](https://user-images.githubusercontent.com/20994342/30880774-0dfd4fbc-a2da-11e7-9ba2-34ccd8c840d6.png)

Logo, não é um bug.
