### ISSUE TITLE
Menu Calculadoras - Alterar as figuras das calculadoras

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#585]
Sapata Isolada: https://1drv.ms/i/s!Ao7UUz0P8SUSiSAAYq08M4xkIwyE
Viga Baldrame: https://1drv.ms/i/s!Ao7UUz0P8SUSiS7YLv1iXOD7wnQO
Paredes: https://1drv.ms/i/s!Ao7UUz0P8SUSiXzp-XvFLVosLOm8
Coluna: https://1drv.ms/i/s!Ao7UUz0P8SUSiWi1rSFc0Y6Re9Aj
Viga: https://1drv.ms/i/s!Ao7UUz0P8SUSiWoi8k6Hf07neotv
Laje: https://1drv.ms/i/s!Ao7UUz0P8SUSiXoWUjefuCEZXf2F
Contrapiso: https://1drv.ms/i/s!Ao7UUz0P8SUSiXjPr3Sr1hE4FP03

![image](https://user-images.githubusercontent.com/20990100/30883085-7b4cb416-a2e1-11e7-8c4f-70c39edbad60.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Percebi que as imagens estão todas serrilhadas, viu isso? Pode ter sido algum problema na hora de exportar, não é pra ser assim não. Além disso, não estão nas dimensões esperadas de 2000x1500 pixels. Pode dar uma olhada pra gente? Valeu!

**Comment by lucasretondo** [comment]
Vou ver e te retorno, valeu.









---- On Ter, 26 set 2017 17:57:09 -0300 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo Percebi que as imagens estão todas serrilhadas, viu isso? Pode ter sido algum problema na hora de exportar, não é pra ser assim não. Além disso, não estão nas dimensões esperadas de 2000x1500 pixels. Pode dar uma olhada pra gente? Valeu!
