### ISSUE TITLE
Resposta Orçamento - Incluir endereço da loja no mapa

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#59]
É fácil colocar o enderenço do lojista e exibir os trajetos possíveis?

![image](https://cloud.githubusercontent.com/assets/20990100/18221209/7e5b26b0-7150-11e6-8905-24ddbfe0949b.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo colocar o endereço do lojista é tranquilo. Quanto a exibir rotas disponíveis, requer horas de desenvolvimento. Sugiro uma lista de melhorias desejadas com a prioridade, para estudarmos e avaliarmos o custo de implementação.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho o endereço do lojista e o trajeto foram incluídos, porém a solução ainda apresenta um certa instabilidade, veja este exemplo, a primeira vez abriu o mapa certo, na segunda tentativa (0:46) abriu o mapa primeiro com A e B e não a descrição igual ao anterior e ao abrir novamente o mapa não ficou centralizado. Até aqui estava tudo bem ainda, porém o mapa travou depois que eu tentei abrir o link em um pedido.
https://drive.google.com/file/d/0B_JJI1HknOluSTFLdVVYZGNCd0E/view

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não sei se você chegou a testar ontem, em caso positivo, por favor teste novamente hoje, acabei não jogando uma dependência no servidor e o resultado do teste não seria o esperado.
