### ISSUE TITLE
Calculadora Sapata Isolada - Quantidade vergalhão CA-60 

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#592]
# Bug

## 1. Em qual etapa do processo o problema ocorreu (Cadastro, Criação do orçamento, Pedido, etc)

Etapa Final-Lista de compras
## 2. O que era esperado que acontecesse (se possível informar o código do requisito da especificação)

Valor do "Vergalhão  de aço CA-60, barra 12m" 4,2 mm fosse de 4.
![image](https://user-images.githubusercontent.com/30830371/30931457-1e88e334-a39b-11e7-8d4a-98098672457a.png)

## 4. Captura de tela

![image](https://user-images.githubusercontent.com/30830371/30931382-ecdbaa56-a39a-11e7-8186-a6dbc3bd96a1.png)

## 5. Passos para reproduzir a ocorrência

Largura: 90
Comprimento 100
Altura 60
11 sapatas isoladas
Topo reto
Sem broca
Concreto usinado
Não sei ainda (aço)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida investigamos aqui revisando todos os passos pra entender a diferença que você levantou, e apuramos que o Não sei ainda na planilha está utilizando um valor pra conta que vem de input do usuário (se você olhar na planilha, verá que foi utilizado o valor 20), mas no código utilizamos o valor 15 de espaçamento que está especificado nesse mesmo arquivo. No caso, não temos como utilizar um input do usuário que não existe, ele existe apenas na planilha pois já está "settado". Acreditamos que seu resultado foi induzido por esse erro na planilha que sanamos calculando conforme a descrição da planilha. Confirma pra gente se é isso mesmo.

![captura de tela de 2017-09-28 10-19-07](https://user-images.githubusercontent.com/20994342/30968736-a2ba2b86-a436-11e7-9980-8db13fd23bdf.png)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Acredito que você tinha intenção de fechar a issue mas acabou clicando duas vezes, vou fechar, qualquer coisa pode reabrir ok?
