### ISSUE TITLE
Cadastro Simplificado - Não avisa que senha não pode conter menos de 6 dígitos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#593]
Não estou conseguindo criar um novo cadastro utilizando o site pelo celular, já testei em três celular, em todos o botão "Concluir cadastro" não funciona.

![image](https://user-images.githubusercontent.com/20990100/31009108-b90d425a-a4dc-11e7-84e9-f379b40ad9c5.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Testamos aqui e está funcionando normalmente quando a regra de senha é atendida, ou seja, senha com no mínimo 6 dígitos. O problema que está ocorrendo não é o botão não funcionar, mas sim não exibir o alerta para o usuário que está tentando realizar um cadastro com senha sabidamente pouco segura (no caso você tentou cadastrar uma senha de 4 dígitos).

**Comment by raphaelMCarvalho** [comment]
Publicado em produção
![captura de tela 2017-09-29 as 10 18 31](https://user-images.githubusercontent.com/20994342/31017654-9679f92c-a4ff-11e7-9296-11a77f143c43.png)

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho fui testar fazendo um novo cadastro. Não me avisa que a senha tem que ter no mínimo 6 caracteres.
![image](https://user-images.githubusercontent.com/30830371/31308181-5ce87ff4-ab48-11e7-91f1-2361694b97bc.png)

**Comment by raphaelbluteau** [comment]
@JuliaAlmeida Você tem razão, ao ajustar algo para outra issue ocorreu esse bug no ambiente de desenvolvimento
