### ISSUE TITLE
Criar Orçamento - O botão "Solicitar orçamento" não funciona

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#594]
O botão "Solicitar orçamento" e "Salvar" não estão funcionando no celular da minha esposa. É um iphone 7.

![image](https://user-images.githubusercontent.com/20990100/31009151-e33bfff8-a4dc-11e7-97b4-871e47af4d6d.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Testamos em 3 dispositivos iOS, 2 dispositivos Android e em um dispositivo que havia cache o problema ocorreu, mas limpando o cache funcionou normalmente. Nos outros sem cache funcionou sem problemas, logo não há nenhuma ação a ser realizada no desenvolvimento.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Coisas que só deus explica, vou fechar a issue.
