### ISSUE TITLE
Orçamento - Mensagem de *os referidos valores.....

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#598]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Pagina de orçamento.
Cliente verificando os orçamentos enviados.

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Não entendi essa mensagem em destaque na imagem:
![image](https://user-images.githubusercontent.com/30830371/31178475-9e4b24d4-a8ef-11e7-975c-101d80558d00.png)

Se não for fazer referência a preço na tabela de "Personalize seu orçamento" penso que seria melhor retirar essa mensagem.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida a frase foi alterada para fazer menção ao frete na tabela Personalizar seu orçamento

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Fechando a issue já que agora a frase existe apenas para evidenciar que o frete faz parte do valor otimizado e possui relação com a tabela apresentada.
