### ISSUE TITLE
Não é possível editar uma obra cadastrada

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#6]
Ao clicar no botão "Editar" de uma obra cadastrada, nenhuma ação é executada ou mensagem exibida.

![image](https://cloud.githubusercontent.com/assets/7696307/17610950/667633d4-6019-11e6-8f90-161ad141f81e.png)

**Comment by raphaelMCarvalho** [comment]
Resolvido.

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio @lucasretondo Foi possível validar esta issue?
