### ISSUE TITLE
Otimização menor preço

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#60]
Não esta funcionando...

![image](https://cloud.githubusercontent.com/assets/20990100/18221248/00374538-7151-11e6-847a-cd56f0e3268e.png)

**Comment by raphaelMCarvalho** [comment]
Lucas, quais foram os passos para chegar ao resultado apresentado na tela? Pela captura de tela, a otimização de Menor Custo por Item não está selecionada, e sim apenas um item do parceiro4. A célula Menor Custo Por Item fica colorida quando a otimização está selecionada (clicando em cima dela para selecionar).

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Estava faltando o feedback do ponteiro do mouse ao passar pelo otimizador, talvez por isso você não tenha conseguido testá-lo (clicando no título da tabela referente ao tipo da otimização). Tente agora por favor.
