### ISSUE TITLE
Calculadora Sapata Corrida - Mudar nome do campo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#603]
Acho que ficou estranho os campos não ficaram alinhamos devido ao tamanho do nome. O que vocês acham de mudar DE "Quantidade de arranques (unidades)" PARA "Qtd de arranques (unidades)"?

![image](https://user-images.githubusercontent.com/20990100/31363046-42768116-ad32-11e7-9820-96a9009ec69a.png)

**Comment by JuliaAlmeida** [comment]
Concordo

**Comment by raphaelMCarvalho** [comment]
O texto foi modificado de forma a caber em apenas uma linha
