### ISSUE TITLE
Cria negociação - Mudar texto 1

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#604]
O que vocês acham de mudarmos este texto DE "Um produto mais caro poderá ser escolhido visto que podem haver descontos e/ou condições especiais de frete que tornarão o preço final menor." PARA "Um produto mais caro poderá ser escolhido quando houveram descontos e/ou condições especiais de frete que tornarão o valor total menor."

![image](https://user-images.githubusercontent.com/20990100/31363472-ace641ba-ad34-11e7-97f9-8dde16c0c4f2.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Pode ser, apenas confirmando, ajustei o verbo destacado, acho que você quis escrever dessa forma mas pode ter errado ao digitar:

> Um produto mais caro poderá ser escolhido quando **houverem** descontos e/ou condições especiais de frete que tornarão o valor total menor.
