### ISSUE TITLE
Cria negociação - Mudar explicação

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#605]
Fiz uma revisão no texto das explicações, veja se vocês concordam com as minhas alterações.

![image](https://user-images.githubusercontent.com/20990100/31363498-cfa73592-ad34-11e7-9da6-b755958e8a77.png)

Nossos otimizadores comparam os preços e condições de pagamento de várias lojas para ajudar você a economizar tempo e dinheiro. Temos três opções de otimização: menor custo total, melhor avaliação ou menor quantidade de lojas.
Para que você entenda bem como funciona o processo de otimização, destacamos abaixo algumas informações importantes:
•	Cada loja configura percentuais de descontos e acréscimos conforme às formas de pagamento. Na tabela de preços é mostrado o valor total destes descontos e/ou acréscimos para os produtos que foram selecionados em cada loja conforme a forma de pagamento escolhida;
•	O otimizador poderá selecionar um produto aparentemente mais caro, mas que, com o desconto dado pela loja, acabará ficando mais barato. Vejamos um exemplo: a loja A vende um produto por R$89,90 e não oferece desconto no pagamento com dinheiro, já a loja B, que vende esse mesmo produto a R$95,90, oferece 10% de desconto quando o pagamento é em dinheiro; nesse caso, o otimizador selecionará a loja B, mesmo sendo aparentemente mais caro, pois, com o desconto de 10%, o produto terá um valor final de R$86,31, que é menor do que o do loja A;
•	A loja pode cobrar frete para fazer a entrega dos produtos e esse valor também é considerado no processo de otimização. Diante disso, poderá ser selecionado um valor aparentemente mais caro, mas que, devido à ausência de cobrança do frete tornará o valor total do pedido mais barato. Vejamos um exemplo: a loja A estabeleceu o valor de R$100,00 para o frete, já a loja B não o cobra o frete (a entrega é gratuita). Se um determinado produto custa R$300,00 na loja A e R$360,00 na loja B; o otimizador selecionará a loja B, pois o valor final do pedido para a loja A seria de R$400,00 (devido ao frete) enquanto o valor final para a loja B permaneceria em R$360,00. Uma economia de R$40,00!
•	O processo de otimização também leva em consideração o valor do pedido mínimo exigido pela loja. Diante disso, um produto mais caro pode ser selecionado pelo otimizador durante a compra para satisfazem esta condição imposta pela loja. Vejamos um exemplo: se a loja A estabeleceu o valor do pedido mínimo de R$200,00 e a loja B de R$100,00, será possível comprar um produto de R$150,00 somente com na loja B, pois esse valor não atinge o valor mínimo para a compra com a loja A. Mas fique tranquilo que o otimizador sempre escolherá o menor valor (R$) possível entre as lojas disponíveis, fornecendo a melhor combinação de preços que atende este requisito e forneça o MENOR VALOR FINAL;
•	A otimização por melhor avaliação considera o menor custo total como critério de desempate caso duas ou mais lojas tenham a mesma nota de avaliação. Nota alcançada a partir da informação dadas por vocês, clientes.
•	A otimização por menor quantidade de lojistas concentra a seleção dos produtos no menor número de vendedores e usa o critério de menor custo total como desempate primário e o critério de melhor avaliação como desempate secundário.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Algumas modificações que você efetuou no texto tornaram orações que estavam gramaticalmente corretas em orações incorretas. Podemos fazer as correções por aqui ou você gostaria de revisar aí novamente?

**Comment by lucasretondo** [comment]
Pode alterar ai.









---- On Ter, 10 out 2017 09:47:07 -0300 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo Algumas modificações que você efetuou no texto tornaram orações que estavam gramaticalmente corretas em orações incorretas. Podemos fazer as correções por aqui ou você gostaria de revisar aí novamente?
