### ISSUE TITLE
Calculadora Calçadas - Trocar o nome do "Concreto usinado...."

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#608]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Lista de Compras, etapa final da calculadora de Calçadas.
## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Trocar o nome do concreto usinado de : "Concreto usinado aplic. p/ contrapiso" PARA : "Concreto usinado aplic. p/ calçada"

## 3. Captura de tela de como está hoje

![image](https://user-images.githubusercontent.com/30830371/31382937-a7a1d948-ad8f-11e7-8833-c71c16c3081a.png)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Esse produto, "Concreto usinado aplic. p/ calçada", não existe no sistema.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho , esta certo, não existe mesmo. Vamos adicionar esse produto.

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho conversei com o Lucas, adicionaremos o produto no começo da semana que vem.
