### ISSUE TITLE
Não esta carregando o último preço e marca

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#61]
![image](https://cloud.githubusercontent.com/assets/20990100/18221339/269023ca-7152-11e6-9ca9-30e38a61cd7f.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo subimos uma atualização que está trazendo o preço, porém está exibindo o valor já multiplicado pela quantidade. Arrumando esse detalhe já aviso para que você possa validar.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo o problema apontado ontem quanto ao valor multiplicado pela quantidade foi resolvido

**Comment by lucasretondo** [comment]
@raphaelMCarvalho no primeiro teste os preços e marcas aparentemente estavam sendo carregados corretamente, mas sem respeitar o unidade, no vídeo abaixo temos um exemplo onde o primeiro orçamento de areia 10 k é respondido normalmente, já no segundo orçamento o preço da areia fina é carregado, porém neste caso a unidade é m3, ou seja, não deveria ter carregado o preço.
1º orçamento
![image](https://cloud.githubusercontent.com/assets/20990100/18779570/e5b71c60-814f-11e6-88f5-af6eb6c61cae.png)
2º orçamento
![image](https://cloud.githubusercontent.com/assets/20990100/18779582/f6ac6764-814f-11e6-909a-912da5ff4180.png)
Vídeo completo
https://drive.google.com/open?id=0B_JJI1HknOluYk1SUG4ycHMxcWc

Ignorei o fato acima e continuei os teste com o parceiro2, porém este a carga dos preços histórico não funcionou.
1º orçamento
![image](https://cloud.githubusercontent.com/assets/20990100/18779714/95b7ad5a-8150-11e6-9a60-eb9dfdfbe281.png)
2º orçamento
![image](https://cloud.githubusercontent.com/assets/20990100/18779736/a99249c0-8150-11e6-9aa7-148aadcc5aae.png)
Vídeo completo
https://drive.google.com/open?id=0B_JJI1HknOlua3o3UFB0Q3k3UU0

**Comment by raphaelMCarvalho** [comment]
@lucasretondo sobre o botão gravar não estar funcionando, acompanhe o status da issue #14

**Comment by raphaelMCarvalho** [comment]
@lucasretondo acredito que você possa ter se enganado em algum momento nas respostas de orçamento, respondendo o mesmo preço de produto pra unidades diferentes da areia. Acompanhando pelo vídeo vemos um caso similar que funcionou como esperado:

- 30s: pedra britada n. 0 ou pedrisco (4.9 a 9.5 mm) - m3 - R$ 90,00
- 1m15: pedra britada n. 0 ou pedrisco (4.9 a 9.5 mm) - m3 - R$ 90,00 (ok, mesma unidade, carregou do histórico)
- 2m20: pedra britada n. 0 ou pedrisco (4.9 a 9.5 mm) - SACO DE 20KG - sem preço (ok também, unidades diferentes, não carregou do histórico)

Olhando no banco de dados, temos estes registros pra areia fina:

![2016-09-23 3](https://cloud.githubusercontent.com/assets/20994342/18801016/bf1c52e8-81b6-11e6-8302-8159770d5924.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho eu deve ter algum problema, acabou de acontecer novamente.
![image](https://cloud.githubusercontent.com/assets/20990100/18804529/9d2c9028-81d2-11e6-8f10-89a86215aa25.png)
![image](https://cloud.githubusercontent.com/assets/20990100/18804532/a79e2a6c-81d2-11e6-9834-ffe39ffc1f0c.png)

https://drive.google.com/file/d/0B_JJI1HknOluYXhhNE9TajJhNnM/view

**Comment by wespatrocinio** [comment]
@raphaelMCarvalho Mostramos o problema para o Claudinei no sábado. A suspeita é que esteja associado com o campo de quantidade.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho acho que você já identificaram também que a marca uma vez informada não é possível apagar. Esta no radar de vocês corrigir este bug também? Quer que abra uma nova issue?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo você se refere a apagar a marca do histórico de preços, que é o tópico dessa issue, sendo que na próxima vez que o lojista respondesse um orçamento, aquele preço viria sem marca?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo @wespatrocinio conseguimos identificar a causa do problema, e esperamos ter uma correção na segunda-feira

**Comment by raphaelMCarvalho** [comment]
@lucasretondo @wespatrocinio a correção está no ar
