### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#611]
https://drive.google.com/file/d/0B_JJI1HknOluWV9QdkJ1X0xpUlE/view

loj2@mailinator.com
loj2$$

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Havia cerca de 30 produtos com categorias que não existem mais e que não foram migradas automaticamente pelo script que criamos. Efetuei a migração manualmente e já incorporei à rotina de inicialização do sistema para que seja automático quando em produção.

**Comment by lucasretondo** [comment]
Parou a mensagem. Mas ele acabou recebem alguns orçamentos vazios: 

![image](https://user-images.githubusercontent.com/20990100/31907050-749da540-b811-11e7-8b20-3a8a7a51e26d.png)

Isso pode ter influenciado?

Note que o orçamento tem areia e concreto:
![image](https://user-images.githubusercontent.com/20990100/31907084-8f045fa0-b811-11e7-8f12-088a0cdffa65.png)

E o loj2 não tem no cadastro:
![image](https://user-images.githubusercontent.com/20990100/31907093-96069ed0-b811-11e7-9fc3-bfe789e6cd3c.png)

**Comment by raphaelMCarvalho** [comment]
Ignore esses orçamentos anteriores, são produto de testes que estávamos realizando na migração, conte a partir de agora mesmo.
