### ISSUE TITLE
SLA - Prazo diferente para a loja responder no final de semana

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#613]
Precisamos padronizar os prazo das lojas. Notem que o prazo para as lojas responderem os orçamentos solicitadas no dia 28/10 (sábado) é até 30/10 as 18h. Já o prazo dos orçamento solicitados em 29/10 (domingo) é 30/10 as 14h. Não faz sentido esta regra.

![image](https://user-images.githubusercontent.com/20990100/32171987-2be67408-bd61-11e7-812b-8740a42dc743.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Fechando a issue já que com a mudança do SLA esse problema não existe mais
