### ISSUE TITLE
Iniciar negociação - Aparece uma tela estranho

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#617]
Ao clicar em iniciar negociação aparece esta tela estranha abaixo.

![image](https://user-images.githubusercontent.com/20990100/32835581-c1f67df6-c9ed-11e7-8c97-b9976e59a3c7.png)

E fica em looping, não permitindo iniciar a negociação.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Eu havia renomeado o arquivo de template dessa tela ontem e acabei não subindo para a homologação o ajuste. Limpe o cache e voltará a funcionar.

![screen shot 2017-11-15 at 10 21 22](https://user-images.githubusercontent.com/20994342/32835829-c9e1e892-c9ee-11e7-8db0-be40a3e94933.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho deu certo, show...
