### ISSUE TITLE
Árvore de produtos - Evitar telas com somente uma opção

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#618]
É possível criar uma regra para evitar este tipo de situação:

![image](https://user-images.githubusercontent.com/20990100/32835866-e8f8b9c2-c9ee-11e7-92f6-ba8a741404f5.png)

O usuário só tem um opção para escolher.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ficou animal, esta alteração foi no Backend? No Android esta esta assim?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Foi na web a alteração, teria que fazer no Android também

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Acho bom fazer lá também. Quer que eu abra uma nova issue?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não precisa não, tranquilo, a gente já vai encaixar o ajuste a partir de amanhã
