### ISSUE TITLE
Geolocalização esta errada

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#628]
A obra 1362 é da cidade de Bernardino Batista / PB, mas no mapa esta como SP.

![image](https://user-images.githubusercontent.com/20990100/32899330-d7571b58-cad1-11e7-988f-dd2fbf77195c.png)

Isso fez com que o orçamento 1566 fosse para as lojas de SP ao invés das lojas da PB.

**Comment by lucasretondo** [comment]
Aconteceu tb com o orçamento 1618.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Os aplicativos e a API dependem de serviços de terceiros para, dado um endereço informado pelo usuário (endereço que pode conter erros, já que são campos abertos) obter um par de coordenadas lat/lng. No caso, utilizamos um serviço da Google para obter estes valores e assumimos que eles estão corretos quando vem a resposta da API deles. Estes dois casos que você apresentou evidenciam que a resposta nem sempre é correta, não é fácil tratar isso, vai ser preciso estudar uma solução para adicionar um passo extra, que é checar a validade dos dados com base em informações que sabemos estar corretas (**as únicas informações de endereço que temos certeza são cidade e estado, o resto pode ser pura abobrinha do usuário e que não temos mais como validar**).

Este problema passou a ocorrer porque, a pedido, deixarmos estes campos abertos (sem preenchimento automático) ao remover a obrigatoriedade de CEP, em decorrência daquele caso específico de loteamento sem CEP. Isso acontece no desenvolvimento de sistemas, ao adaptar algo pra um caso específico podemos abrir espaço pra problemas que a princípio não eram previstos.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho nós informamos o CEP para a API do Google retornar a lat/lng? E quando o usuário não informa o CEP, o que nós informamos para o Google?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não, a gente não envia CEP para o Google, a API deles precisa receber um endereço. O CEP a gente envia para uma outra API que retorna o endereço. O que enviamos para o serviço do Google é o endereço informado, ou seja, logradouro, número, complemento, bairro, cidade e estado. Veja que no primeiro caso, por exemplo, o usuário informou como logradouro a palavra "sitio." e complemento "casa".

**Comment by lucasretondo** [comment]
@raphaelMCarvalho se enviarmos para o Google somente a cidade e estado ele retornar o lat/lng?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Sim, retorna, mas geralmente com lat/lng no centro político da cidade. O único down side dessa estratégia, a meu ver, é que como a regra de negócio se utiliza de raio de entrega, pode ocorrer de um lojista que a princípio se encontra dentro do raio da obra não atender o orçamento, já que a obra foi salva com lat/lng do centro da cidade.

Essa é a API da Google, veja esse exemplo pra São Carlos:
https://maps.googleapis.com/maps/api/geocode/json?address=S%C3%A3o%20Carlos,%20SP

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Acho que não devemos afrouxar esta regra para todos os casos. Temos que verificar se o endereço informado é igual ao preenchimento automático, se for igual, informamos para o Google todos os campos. Se o endereço for diferente (ou seja, o usuário editou), buscamos no Google somente pela cidade e estado.

Quando ele não informa o CEP nós já usamos esta regra, certo?

E como evitaremos que o usuário mude o endereço direto no mapa?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Aí que está, é na linha do que eu disse, não é simples fazer da forma como você descreveu, é trabalhoso. Vamos ter que estudar. O comportamento é o mesmo atualmente pra ambos os casos, com ou sem CEP a API envia o endereço pra Google e coleta o lat/lng, não há distinção. Pode haver distinção a partir do momento que estudarmos uma solução pra isso.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo O objetivo de existir o mapa é exatamente para permitir que o usuário altere a posição caso o retorno da API pro endereço esteja incorreto ou impreciso.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho entendi, que m...

**Comment by raphaelMCarvalho** [comment]
Vou discutir amanhã com a equipe e a gente chega a alguma solução

Enviado do meu iPhone

Em 20 de nov de 2017, à(s) 19:51, lucasretondo <notifications@github.com> escreveu:

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Este ajuste se encontra em produção. Em termos simples, a cada obra salva é realizada uma validação das coordenadas geográficas recebidas, sendo realizado um cálculo para verificar se as coordenadas estão dentro de uma margem específica de distância relativa ao centro da cidade informada. Caso esteja dentro dessa margem, as coordenadas recebidas são salvas. Caso não esteja, as coordenadas são descartadas e as do centro da cidade são usadas ao invés das recebidas.
