### ISSUE TITLE
Página confirmar entrega errado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#63]
Quando clico para abrir o pedido para confirmar a entrega pode item
![image](https://cloud.githubusercontent.com/assets/20990100/18221397/1a6f51c8-7153-11e6-933e-8af71202dbc1.png)

Sou direcionado para uma página onde eu só tenho a opção de voltar
![image](https://cloud.githubusercontent.com/assets/20990100/18221401/2cf6013e-7153-11e6-909c-8c633fff610e.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo, a ação para confirmar o pedido está no botão Confirmar entrega. Nos outros pontos da linha, é aberta a página de detalhes.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho o confirmar entrega pode ser feito pela botão da tabela resumo ou item a item, correto?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo entendi. Então o lojista também pode confirmar a entrega item a item, correto? Não apenas o cliente

**Comment by lucasretondo** [comment]
@raphaelMCarvalho acho que vocês trocaram as bolas com o confirmar pagamento...

![image](https://cloud.githubusercontent.com/assets/20990100/18458374/095c0eb2-7937-11e6-9eef-f601a75d4531.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ainda precisa de ajuda?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo esclarecido já, valeu
