### ISSUE TITLE
Página nossa proposta - Mudar o texto da página

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#630]
Vamos mudar o texto da página nossa proposta para ficar igual ao blog:

O QUE É O PRACONSTRUIR?

O PraConstruir é uma ferramenta digital idealizada para ajudar as pessoas a construírem o seu sonho. Conectamos os proprietários dos imóveis em construção ou reforma com as melhores lojas para facilitar a análise de preços e compra dos materiais de construção.

QUAL É A NOSSA PROPOSTA?

Quem já construiu sabe o quanto é difícil “tocar” uma obra. Todos os dias surgem imprevistos e uma nova lista de compras.

Consciente desta realidade, nós trabalhamos todos os dias para criar ferramentas e parcerias para transformar a experiência de construir em algo prazeroso, maximizando o orgulho e eliminado o estresse.

Não perca mais tempo indo nas lojas para fazer orçamentos, use gratuitamente a nosso site ou aplicativo e faça os orçamentos e pedidos de compra dos materiais da sua construção sem sair de casa.

Manter última frase: Faça o seu cadastro e use as nossas ferramentas gratuitamente, temos certeza que você irá gostar.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ainda esta o texto antigo:

![image](https://user-images.githubusercontent.com/20990100/33127628-65bc535c-cf70-11e7-9548-3485501636c6.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não tínhamos entendido que era para descartar o primeiro parágrafo completamente, alteramos apenas o que vinha após isso. Agora foi descartado.
