### ISSUE TITLE
Pedido e Entrega - Compactar o layout da avaliação Cliente e Lojista para caber em uma página

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#64]
O layout da página de avaliação esta um pouco diferente o enviado. De qualquer forma acho melhor diminuirmos a distância entre as linhas e diminuir a altura da caixa de motivos de tal forma que o botão Enviar caiba em uma única página.

Página
![image](https://cloud.githubusercontent.com/assets/20990100/18221455/da403634-7153-11e6-9f5c-2404541edbd8.png)

Enviado
![image](https://cloud.githubusercontent.com/assets/20990100/18221462/eb66d846-7153-11e6-9ebf-c09c4aabf40e.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não recomendo reduzir o espaço entre os itens de checkbox pois prejudica um pouco a leitura dos mesmos. Reduzimos a altura da caixa de mensagem pra atender ao que foi solicitado, quanto a 'caber em uma página' (lembrando que o tamanho da porção visível do navegador depende da resolução da tela do usuário e se o navegador está maximizado ou com largura e altura reduzidas).

![captura de tela de 2016-10-04 16-25-21](https://cloud.githubusercontent.com/assets/20994342/19089455/b51dc8ce-8a50-11e6-99b3-f2b3284adb06.png)
