### ISSUE TITLE
Calculadora Sapata Corrida - Valores da lista de compras

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#641]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Etapa final de Lista de compras.

## 2. Descrição detalhada da melhoria (quanto mais clara e precisa, melhor)

Confirmar valores de cimento, areia e pedra.
Pelas minhas contas deveria ser: 
cimento: 70
areia: 8
pedra: 10

## 3. Captura de tela de como está hoje

![image](https://user-images.githubusercontent.com/30830371/33089114-d22f757c-ced6-11e7-9319-a855179e8435.png)

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Olá, você pode compartilhar conosco os dados de entrada pra confirmarmos a saída?

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho  desculpa, esqueci de por.
68 m
10 unidades
30x40 cm
Topo reto
com broca 30cmx3m
Concreto feito na obra 1:5:7
"Não sei" como opção de compra do aço
