### ISSUE TITLE
Regra pedido mínimo

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#65]
A regra do pedido mínimo deve ser sobre o valor bruto ou descontado?

![image](https://cloud.githubusercontent.com/assets/20990100/18221499/8540bb12-7154-11e6-84ef-a4fcc32aef68.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo no momento é realizado sobre o valor descontado. Caso deva ser sobre o bruto, basta definirmos isso. O que acha?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho eu acho melhor sobre o valor descontado. Vc tem certeza, eu tive a impressão que o sistema estava calculado sobre o valor bruto.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Vou confirmar
