### ISSUE TITLE
Calculadora de Pintura - Adicionar imagem da capa

### ISSUE THREAD

**Issue by JuliaAlmeida** [PraConstruir/web_app#651]
# Melhoria

## 1. Em qual etapa do processo foi detectada a oportunidade de melhoria (Cadastro, Criação do orçamento, Pedido, etc)

Adicionar imagem da capa da calculadora. Imagem foi enviada pelo slack.
https://www.shutterstock.com/pt/image-photo/set-painting-tools-paint-brushes-tray-272823011?src=Uqo17ODnWDone_qwChcE3Q-1-5

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida O Shutterstock é um serviço que licencia conteúdos como imagens e vídeos, não são geralmente imagens gratuitas. Você poderia ver com o Lucas se vocês irão assinar algum dos planos para baixar a imagem? Segue captura de tela ao clicar em Baixar e cadastrar uma conta gratuita:

![screen shot 2017-12-05 at 15 27 52](https://user-images.githubusercontent.com/20994342/33621151-04db405a-d9d1-11e7-9d8b-d5c327368d5f.png)

**Comment by JuliaAlmeida** [comment]
@raphaelMCarvalho pedi para o pessoal da Na+, mais tarde vão disponibilizar a imagem. Desculpe o transtorno.

**Comment by raphaelMCarvalho** [comment]
@JuliaAlmeida Imagem atualizada
