### ISSUE TITLE
Mudar URL da página de lojas e inserir botão

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#652]
Vamos mudar a URL da página com as lojas de materiais de construção
DE: https://praconstruir.com.br/lojas
PARA: https://praconstruir.com.br/lojas-de-material-de-construcao

Vamos incluir também nesta tela o botão navegante de solicitar orçamento.

**Comment by lucasretondo** [comment]
Acho que o botão pode surgir assim que começar a rolar.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Está lá, para visualizar a mudança de URL talvez seja necessário limpar o cache
