### ISSUE TITLE
Criar Orçamento - Mudar mensagem

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#653]
Precisamos mudar esta mensagem devido a mudança do SLA:
![image](https://user-images.githubusercontent.com/20990100/33829142-1ceb0b38-de56-11e7-8817-1de1d2a56b96.png)

O que vocês acham de mudar
DE "Você receberá as respostas até 10/01/2018 às 09:30."
PARA "Aguarde, daqui a pouco você receberá as cotações."

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Acredito que o "daqui a pouco" gera uma expectativa muito alta e facilmente poderá causar frustração no usuário. O que acha da mensagem abaixo?

"Agora é só aguardar, assim que chegarem as cotações você será notificado."

**Comment by lucasretondo** [comment]
@raphaelMCarvalho gostei, manda bala na web e apps.
