### ISSUE TITLE
Cadastro Lojista - Não é possível mudar o nome

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#654]
Não estamos conseguindo mudar o nome fantasia do usuário itabira1@mailinator.com (senha pra12345).

**Comment by raphaelMCarvalho** [comment]
@lucasretondo 
![screen shot 2017-12-11 at 14 51 58](https://user-images.githubusercontent.com/20994342/33842859-e49bcd58-de82-11e7-9c7e-9044b92c888b.png)
