### ISSUE TITLE
O orçamento 1963 e 1964 não caiu para ninguém

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#656]
O orçamento 1963 e 1964 não caiu para nenhuma loja. Quando entramos no ADM o prazo fica em circulo.

![image](https://user-images.githubusercontent.com/20990100/34041326-bfbd25fa-e17e-11e7-9e33-1c5ce3ad8995.png)

![image](https://user-images.githubusercontent.com/20990100/34041333-c520f300-e17e-11e7-91d7-f8448ef52c8e.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Identificamos o bug, ele se encontrava no momento em que era determinada a data de expiração do orçamento. Já corrigimos e estamos subindo a correção. Os orçamentos afetados por esse problema vamos corrigindo manualmente até o período da tarde.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Consultei na base de dados e os orçamentos afetados são os de id: 1963, 1964 e 1965. Já estamos corrigindo manualmente estes, quanto ao backend, a correção do hotfix já está no ar e testada.

**Comment by lucasretondo** [comment]
Blz, obrigado.









---- On Sex, 15 dez 2017 12:46:44 -0200 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo Consultei na base de dados e os orçamentos afetados são os de id: 1963, 1964 e 1965. Já estamos corrigindo manualmente estes, quanto ao backend, a correção do hotfix já está no ar e testada.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo O orçamento 1965 estava com status Salvo apenas, sem produtos. Já corrigi os outros, veja se está tudo ok quando puder.

**Comment by lucasretondo** [comment]
O orçamento 1964 continua sem nenhuma loja.



Abs



Lucas



---- On Sex, 15 dez 2017 16:58:36 -0200 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo O orçamento 1965 estava com status Salvo apenas, sem produtos. Já corrigi os outros, veja se está tudo ok quando puder.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Tem certeza? Eu olhei aqui no relatório e estão lá as lojas, com orçamento pendente pra elas responderem. Lembrando que na área administrativa, no status Aguardando respostas, aparecem as respostas quando elas chegam. Segue captura de tela do relatório.

![screen shot 2017-12-15 at 17 13 23](https://user-images.githubusercontent.com/20994342/34056760-72cee37c-e1bb-11e7-8384-7dda3c150959.png)

**Comment by lucasretondo** [comment]
Tem razão, agora deu certo, vai saber.



Obrigado





---- On Sex, 15 dez 2017 17:15:21 -0200 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo Tem certeza? Eu olhei aqui no relatório e estão lá as lojas, com orçamento pendente pra elas responderem. Lembrando que na área administrativa, no status Aguardando respostas, aparecem as respostas quando elas chegam. Segue captura de tela do relatório.
