### ISSUE TITLE
Árvore de Materiais - Não carrega os serviços

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#659]
A árvore não esta carregando os serviços:

![image](https://user-images.githubusercontent.com/20990100/34320611-6230d9be-e7e5-11e7-92f2-edc83858640c.png)

![image](https://user-images.githubusercontent.com/20990100/34320612-6b065bb8-e7e5-11e7-85ba-cf023c70ce02.png)

**Comment by raphaelMCarvalho** [comment]
Testei aqui e funcionou normalmente. Tente de novo, pode ter sido alguma intermitência de rede.

**Comment by lucasretondo** [comment]
Deu certo.
