### ISSUE TITLE
Orçamento Recebido - Exibição da marca de somente um item

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#66]
O parceiro3 informou a marca, mas não tem como o cliente ver.

![image](https://cloud.githubusercontent.com/assets/20990100/18221519/c1c70d20-7154-11e6-9dfb-cb803dafdbc1.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo quais foram os passos pra chegar a esse resultado? É importante para que possamos reproduzir

**Comment by raphaelMCarvalho** [comment]
@lucasretondo foi possível reproduzir essa issue? Havendo qualquer novidade me informe por favor

**Comment by lucasretondo** [comment]
@raphaelMCarvalho expliquei este caso para o Caludinei no sábado. Se tiver alguma outra dúvida me acione. obrigado.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo beleza, Lucas. Só confirmando: o problema relatado foi resolvido ou você fechou por engano a issue?
