### ISSUE TITLE
Resposta Automática - Excluir o menu lateral

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#661]
Vamos excluir o menu lateral para ter mais espaço e ficar iguais a página anterior:

![image](https://user-images.githubusercontent.com/20990100/34320766-1328ee4e-e7e8-11e7-8474-689aa3b275c4.png)

![image](https://user-images.githubusercontent.com/20990100/34320773-1df12d5a-e7e8-11e7-985d-33737ba2da91.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Essa mudança é bem problemática, tanto da parte de experiência de uso quanto pela implementação. Pela ótica da experiência de uso, veja que sempre ao tocar num item de menu, abre-se o conteúdo na região à direita, mantendo-se o menu.Se fizéssemos essa alteração, estaríamos criando uma quebra nessa experiência. Pela ótica da implementação, não é trivial obter esse resultado. Minha sugestão é manter o menu como está.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Perceba que a página que você deu de exemplo é visualizada quando um usuário ou toca num item que é apresentado na região de conteúdo (à direita do menu), ou se veio através do link do e-mail. Nunca ao tocar num item de menu.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ok, vc me convenceu.
