### ISSUE TITLE
Resposta Automática - Mudar layout do botão Salvar

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#662]
Vamos usar o mesmo padrão de layout nos botões e incluir o botão Voltar.

![image](https://user-images.githubusercontent.com/20990100/34320783-4773ad42-e7e8-11e7-9240-e119231cafb8.png)

Layout padrão:

![image](https://user-images.githubusercontent.com/20990100/34320785-51d1d8cc-e7e8-11e7-99f0-9025d1214d49.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Não faz sentido o botão Voltar nesta tela, o botão Voltar existe quando há um caminho definido pra onde voltar, o usuário tocou no item de menu, ele pode ter vindo de muitos lugares diferentes. Nesse exemplo que você deu do botão Voltar, o usuário tocou num item que estava sendo exibido na região de conteúdo, não num item de menu. No caso de exemplo faz sentido o botão Voltar, já que ele volta pra lista onde estava, no caso da Resposta Automática, não.

Podemos alterar o estilo do botão Salvar, no entanto.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho blz, esquece o botão voltar.
