### ISSUE TITLE
Resposta Automática - Aparentemente não está salvando

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#664]
Primeiro cadastrei os preços abaixo:
![image](https://user-images.githubusercontent.com/20990100/34320856-935d9e56-e7e9-11e7-9b04-06d3e2458403.png)

Depois quando sai e voltei os preços "não" estavam salvo aparentemente:
![image](https://user-images.githubusercontent.com/20990100/34320869-b0cdf49a-e7e9-11e7-906a-cbe8706df9c0.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Tentei reproduzir o erro mas no meu caso estavam salvos sim, só não aparecia o ícone às vezes. Esse é o problema? Você quis dizer que salva mas não aparece o ícone em frente ao nome do produto?

**Comment by lucasretondo** [comment]
Sim, o ícone não esta sendo exibido e o status não esta sendo carregado.







---- On Qua, 27 dez 2017 23:42:50 -0200 Raphael Carvalho &lt;notifications@github.com&gt; wrote ----




@lucasretondo Tentei reproduzir o erro mas no meu caso estavam salvos sim, só não aparecia o ícone às vezes. Esse é o problema? Você quis dizer que salva mas não aparece o ícone em frente ao nome do produto?

**Comment by lucasretondo** [comment]
Preenchi o produto areia média com o status disponível e salvei:
![image](https://user-images.githubusercontent.com/20990100/34527222-08ef75c2-f08c-11e7-9ff8-bbed3b88f587.png)

Depois sai e voltei o status não foi salvo:
![image](https://user-images.githubusercontent.com/20990100/34527247-1dd97b04-f08c-11e7-8d51-ebfec5f70ab3.png)

Já o produto areia fina foi salvo:
![image](https://user-images.githubusercontent.com/20990100/34527279-36299f36-f08c-11e7-8e7f-d5df7dfd5a27.png)

Acho que o produto areia média já tinha sido informado antes de corrigir esta issue. Será que isso pode influenciar?

**Comment by raphaelMCarvalho** [comment]
Você chegou a limpar o cache do navegador antes de testar? Caso não tenha, por favor limpe e tente novamente, realizei esses testes antes do almoço e funcionou.

Enviado do meu iPhone

Em 3 de jan de 2018, à(s) 13:45, lucasretondo <notifications@github.com> escreveu:

**Comment by lucasretondo** [comment]
Sim, limpei.

De qualquer forma vou limpar e testar novamente.

Estranho que isso ocorreu com a loj1, na loj2 não deu este problema.

**Comment by lucasretondo** [comment]
Acabei de limpar o cache e deu o mesmo erro.

Ao abrir a primeira vez:
![image](https://user-images.githubusercontent.com/20990100/34527596-2b5fe140-f08d-11e7-96a1-93c8b94e1191.png)

Ao salvar:
![image](https://user-images.githubusercontent.com/20990100/34527607-348bce64-f08d-11e7-847d-d84869c8233d.png)

Ao sair e voltar:
![image](https://user-images.githubusercontent.com/20990100/34527619-3e62c97e-f08d-11e7-8c94-a60a3221ab70.png)

**Comment by lucasretondo** [comment]
Com a loj3 esta ocorrendo o mesmo erro. Não é melhor apagar todos os dados já salvos para fazermos um teste limpo?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Como acontece com um lojista e não com outros, pode ter algum outro bug. Me passa os dados dos lojistas loj1 e loj3 que eu vou investigar.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho este erro repetiu com as seguintes lojas:

loj1@mailinator.com - loj1$$
loj3@mailinator.com - loj3$$
loj4@mailinator.com - loj4$$

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Subi agora um ajuste, veja se funcionou pra você. Limpe o cache pra garantir que está com as últimas novidades.
