### ISSUE TITLE
Respostas Automática - Não esta carregando o preço

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#671]
Quando o lojista salva um produto com resposta automática o sistema para de carregar o histórico do preço.

![image](https://user-images.githubusercontent.com/20990100/34423837-27579560-ec06-11e7-959e-bfb1cc248bd5.png)

**Comment by raphaelMCarvalho** [comment]
Havia valor previamente pra esse produto e unidade pro lojista no histórico? Não há uma relação direta entre a resposta automática e o histórico de preços, mas vou revisar

Enviado do meu iPhone

Em 28 de dez de 2017, à(s) 19:34, lucasretondo <notifications@github.com> escreveu:

**Comment by lucasretondo** [comment]
@raphaelMCarvalho acho que fiz confusão devido as várias versões do cadastro de materiais, foi mal.
