### ISSUE TITLE
Resposta Automática - Mensagem de erro não esta relacionada a tela atual

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#672]
Não esta gravando o status do produto, isso obrigado o usuário a informar o status de todos os produtos sempre que for atualizar a lista.

![image](https://user-images.githubusercontent.com/20990100/34470288-842d60e6-ef15-11e7-9913-a12abd43b934.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo O problema apontado se enquadra na issue #664 já aberta
