### ISSUE TITLE
Resposta Automática - Não está funcionando

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#673]
A resposta automática não esta funcionado, já testei com vários materiais.

**Comment by raphaelMCarvalho** [comment]
![screen shot 2018-01-03 at 15 40 05](https://user-images.githubusercontent.com/20994342/34532191-6ca128c6-f09c-11e7-8ce2-f040ae0d3670.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Vou limpar o cache pela quinta vez e tentar novamente.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Quando é mudança na API, não é necessário limpar o cache. Pra facilitar seus testes, nas próximas vezes vou informar isso.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho no site esta funcionando, mas no app continua sem resposta automática.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho olhe o exemplo do orçamento 2556 da loj1@mailinator.com (loj1). Ele tem o cimento cadastrado com resposta automática, mas orçamento esta como pendente.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Nesse caso, funcionou da forma como planejamos no desenvolvimento. Foi decidido não responder automaticamente caso o cliente informe uma marca ou preencha o campo de observação. Como ele solicitou Votoran, o sistema decidiu não responder automaticamente. Caso o cliente solicitasse sem informar nada além do produto e unidade, a resposta automática iria com a marca Votoran para o cliente. Essa decisão tem uma justificativa simples: o campo marca é um campo aberto tanto para o cliente quanto para o lojista, não há valores de marca pré-definidos na base de dados, tomar decisões com base nisto pode ocasionar erros inesperados.

![screen shot 2018-01-03 at 16 42 27](https://user-images.githubusercontent.com/20994342/34534398-21f54e3e-f0a5-11e7-8b07-95c4b3e733b0.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho concordo com a regra, mas neste caso campo observação esta vazio.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Você tem razão, confundi o campo de observação com o histórico de preços! Vou investigar

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Revisei o código e a base de dados e não me saltou aos olhos nenhum problema evidente. Nisso resolvi criar uma obra com meu usuário em Piracicaba e solicitar um orçamento, e recebi resposta automática do loj1@mailinator.com (Primeiro de Maio, certo?). Veja se faltou algum passo na descrição do problema. O orçamento é o 2558.

![screen shot 2018-01-03 at 17 06 35](https://user-images.githubusercontent.com/20994342/34535233-7cde3308-f0a8-11e7-9c73-2e37371b5307.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho quando solicito pelo site funciona a resposta automática, o pau esta quando solicito orçamento pelo Android.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Obrigado, Lucas, tenho uma suspeita do que pode ser, já corrijo e subo pra API.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho blz.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo O problema era uma checagem na API, além de checar se o campo de informação estava nulo, também era necessário verificar se estava vazio (são dois estados diferentes).

![screenshot_1515009409](https://user-images.githubusercontent.com/20994342/34537438-8c42d69e-f0af-11e7-82f7-41c7ba1c43cd.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho show, funcionou.
