### ISSUE TITLE
Solicitar orçamento - Não estou conseguindo solicitar orçamento pela web

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#674]
Já tentei com todos os tipos de usuários (novos e velhos) e com nenhum deles eu consegui solicitar orçamentos pelo site.

Em todos dá o erro de internal server error.

![image](https://user-images.githubusercontent.com/20990100/34531349-1d24f9f6-f099-11e7-8e6c-bd9e09a08153.png)

**Comment by raphaelMCarvalho** [comment]
![screen shot 2018-01-03 at 15 37 53](https://user-images.githubusercontent.com/20994342/34532140-35b8e6e6-f09c-11e7-8a21-b2007cd760e1.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho deu certo agora.
