### ISSUE TITLE
Orçamento finalizado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#68]
O preço do primeiro item foi informado como opção 1 e quando o orçamento passou para o status finalizado ele foi para a opção 2.

![image](https://cloud.githubusercontent.com/assets/20990100/18221564/af4e91e4-7155-11e6-82f5-eae651beeeb3.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo refizemos testes aqui nas condições que você descreveu e está funcionando como esperado, o resultado não foi como na captura de tela.
