### ISSUE TITLE
Regras cadastro de desconto

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#70]
Não existe nenhuma regra de validação para o cadastro de descontos.

![image](https://cloud.githubusercontent.com/assets/20990100/18221593/45371636-7156-11e6-9e6e-a0ec5c402c17.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo para alinhamento, o que você espera ver como regra de validação dos descontos?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho vou fechar este bug uma vez que nós não teremos mais opções de alçadas de valore como o novo otimizador.
