### ISSUE TITLE
Erro na submissão de cadastro de cliente

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#72]
Na segunda tela de cadastro de cliente, com os dados da obra, ao clicar no botão **"Próximo passo: cadastro de senha"**, o processo não é feito com sucesso e aparece uma mensagem **"Bad request"**, sem significado. O mesmo ocorre se eu clicar em **"Pular passo"**

![image](https://cloud.githubusercontent.com/assets/7696307/18221739/9dc51250-7159-11e6-98a0-684f67189464.png)

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio Para reproduzir o problema, foi feito o seguinte:

1. Preenchido todos os campos obrigatórios da primeira tela
2. Na segunda tela, não se preenchia nada e clicava-se em "Primeiro passo: Cadastro da Senha"
3. Nesse momento, mensagens de validação dos campos de obra eram destacados.
4. Em seguida, preenchia-se os campos obrigatórios e clicava-se novamente no botão para Cadastro de Senha
5. O erro "Bad Request" aparecia.
