### ISSUE TITLE
Link orçamento arquivado não esta funcionando

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#73]
![image](https://cloud.githubusercontent.com/assets/20990100/18221830/b8cb2ede-715b-11e6-9d65-fc0db41e4d22.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho o link funcionou, mas falta os botões "Voltar" ou "Desarquivar" no inferior da página detalhada...

![image](https://cloud.githubusercontent.com/assets/20990100/18573253/14e85c82-7b98-11e6-9f1c-d5bffc882f3f.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo o bug que você menciona nessa issue está resolvido. Nesse caso, se há outras issues, registre-as em novas issues, senão a coisa fica bagunçada. Já te adianto que é preciso verificar se há esse layout de tela específica para orçamentos arquivados com botão Desarquivar no rodapé, não localizei aqui nos meus arquivos. Se há, já anexe na issue.

PS.: o botão Voltar foi adicionado e a coluna foi removida, conforme issue #79 . Imagino que você não tenha visto a atualização por algum problema de cache no navegador. Tente limpá-lo e verifique novamente por favor.

![2016-09-16](https://cloud.githubusercontent.com/assets/20994342/18583105/e7da66b2-7bde-11e6-80f9-d39264258103.png)
