### ISSUE TITLE
Criar Orçamento - Excluir direto quando item dos orçamento vazio

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#75]
Podemos excluir esta mensagem quando a linha estiver vazia?
![image](https://cloud.githubusercontent.com/assets/20990100/18221886/0392af40-715d-11e6-957b-b0f645c8c600.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo podemos, vamos fazer essa modificação.
