### ISSUE TITLE
Cadastro Obra - Barra de rolagem ao adicionar obra

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#76]
É possível mudar a posição da barra de rolagem conforme sugestão abaixo?

![image](https://cloud.githubusercontent.com/assets/20990100/18221912/bc371068-715d-11e6-95bc-57b36f3daeba.png)

**Comment by raphaelMCarvalho** [comment]
Esse é o comportamento padrão dos componentes utilizados. Podemos ver a possibilidade de fazer essa alteração e o tempo necessário para executá-la (definam o quão desejável é). É importante ressaltar que colocar a barra de rolagem no componente vai reduzir o espaço para conteúdo dentro dele (a barra geralmente fica dentro, e não fora).

**Comment by lucasretondo** [comment]
Vamos orçar o tempo necessário, mas para mim hoje tem baixa prioridade.
