### ISSUE TITLE
Meus Orçamentos Cliente - Não exibir botão orçamento arquivado quando vazio

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#78]
Temos que incluir uma mensagem quando não existir orçamentos arquivos.
![image](https://cloud.githubusercontent.com/assets/20990100/18221943/7e61d7fe-715e-11e6-8401-c7bad53bb895.png)

O ideal é não exibir o botão orçamento arquivo quando não existirem orçamentos arquivados.
![image](https://cloud.githubusercontent.com/assets/20990100/18221948/966d036e-715e-11e6-81f7-9e15c1d517d1.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo concordo, não exibiremos se não houverem arquivados.
