### ISSUE TITLE
Orçamento aguardando resposta

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#79]
É possível excluir a linha da tabela da coluna Outras informações?

Temos que incluir um botão "Voltar" no final da página.

![image](https://cloud.githubusercontent.com/assets/20990100/18221964/2edc1680-715f-11e6-9eab-19bf514533e2.png)

**Comment by raphaelMCarvalho** [comment]
Não entendi, Lucas.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho Segue o exemplo:
![image](https://cloud.githubusercontent.com/assets/20990100/18275699/86725bea-741e-11e6-95e3-4bed533db5a1.png)

Sobre a inclusão do botão "voltar" no padrão laranja, ok?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo Entendi. A coluna é bug, o botão voltar é melhoria.

**Comment by raphaelMCarvalho** [comment]
Há estes botões atualmente. O botão Voltar não pode receber destaque nesse layout. Para manter consistência e não confundir o usuário, colocaremos ele da mesma cor que o Salvar e voltar mais tarde.

![2016-09-15](https://cloud.githubusercontent.com/assets/20994342/18554195/c8b99cbc-7b39-11e6-935b-83417a8a8faf.png)

**Comment by lucasretondo** [comment]
@raphaelMCarvalho de acordo sobre o botão, mas a linha da coluna continua aparecendo...

![image](https://cloud.githubusercontent.com/assets/20990100/18573228/ddb50ba2-7b97-11e6-8ab5-541ff0e6eb23.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo está resolvida a issue, acredito que tenha sido algum problema de cache no navegador. Veja na captura de tela anexa:

![2016-09-16](https://cloud.githubusercontent.com/assets/20994342/18583148/21ab8164-7bdf-11e6-87fc-53d1ad355fb9.png)
