### ISSUE TITLE
Cadastro Obra - Cadastro duplicado

### ISSUE THREAD

**Issue by wespatrocinio** [PraConstruir/web_app#8]
Foi possível cadastrar duas Obras com exatamente o mesmo endereço.

![image](https://cloud.githubusercontent.com/assets/7696307/17611077/6a1b437a-601a-11e6-9bc8-e6526fd6f7c6.png)

**Comment by raphaelMCarvalho** [comment]
@wespatrocinio só confirmando, este seria um bug e melhoria ou apenas uma melhoria?

**Comment by raphaelMCarvalho** [comment]
@lucasretondo e @wespatrocinio , permitir o cadastro de mais de uma obra com mesmo endereço para o mesmo cliente seria o bug? Queria esclarecer o que é o bug e o que é a melhoria nessa issue.

**Comment by wespatrocinio** [comment]
@raphaelMCarvalho como este detalhe não foi especificado, então seria uma Melhoria e não Bug. Entretanto, pensando em futuro, é importante ter uma base de cadastro com alta qualidade, e isso implica em trabalhar os dados duplicados.

Como esse caso é de borda e não tem, segundo nossa expectativa, impacto no negócio no curto prazo, vamos ver como resolvemos isso depois.
