### ISSUE TITLE
Respondendo orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#80]
Eu estava respondendo o orçamento normalmente. Quando cliquei em enviar fui direcionado para esta página erroneamente.

![image](https://cloud.githubusercontent.com/assets/20990100/18221983/9f377a32-715f-11e6-8e2e-ace3be8de605.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo acreditamos que essa issue foi solucionada com a resolução da #92
