### ISSUE TITLE
Notificação - Criar para dúvida

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#81]
Não temos nenhuma notificação ou alerta quando existem dúvida pendentes.

Somente enviamos o e-mail.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo não me recordo de termos isso previsto no layout proposto, mas seria importante haver essa notificação na web sim. Peçam para o pessoal fazer uma proposta de layout. Essa issue deve ser registrada como enhancement.
