### ISSUE TITLE
Salvar orçamento lojista

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#84]
Temos que criar a funcionalidade de salvar o orçamento para os lojistas, por exemplo, se eu tenho uma dúvida eu não posso salvar o orçamento até o cliente responder a dúvida.

![image](https://cloud.githubusercontent.com/assets/20990100/18457434/2577bf4a-792f-11e6-8351-183173225be1.png)

**Comment by raphaelMCarvalho** [comment]
Já cadastrada a issue #83
