### ISSUE TITLE
Página inicial verificar orçamento

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#85]
A otimização menor custo deve ser carregada assim que o usuário abrir o orçamento

Atual
![image](https://cloud.githubusercontent.com/assets/20990100/18457769/e0cdb04a-7931-11e6-821f-0695da53f723.png)

Correto
![image](https://cloud.githubusercontent.com/assets/20990100/18457855/8950b4ce-7932-11e6-8532-9b9c0687478a.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo funcionando como esperado, Lucas. Lembrando que, conforme os requisitos, o sistema deve manter o estado. Nesse caso, se o usuário abriu a primeira vez e depois fez uma outra seleção, ao abrir novamente a tela, não estará selecionado o otimizador de menor custo.
