### ISSUE TITLE
Menor custo - Produto não selecionado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#86]
A otimização do menor custo não esta selecionado o produto ripa.

Atual
![image](https://cloud.githubusercontent.com/assets/20990100/18457876/b42c2d36-7932-11e6-8407-56e300603658.png)

Correto
![image](https://cloud.githubusercontent.com/assets/20990100/18457942/354048da-7933-11e6-8e39-89dd50e82bf7.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo nesse caso em tela, no momento do teste, sabe me dizer quais eram os pedidos mínimos de cada lojista?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não sei, vou fechar este bug e se o erro voltar a aparecer eu abro um novo...
