### ISSUE TITLE
Layout aguardando confirmação pedido

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#88]
Precisamos padronizar o layout do cabeçado aplicando a fonte maior e negrito (igual demais cabeçalhos) na linha selecionada

![image](https://cloud.githubusercontent.com/assets/20990100/18458095/77e8ed3a-7934-11e6-8861-16c9cbeb7561.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo como está de acordo com o layout recebido, marquei como melhoria
