### ISSUE TITLE
Ordenação meus pedidos

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#91]
A ordem do status não esta correta e temos que mudar o testo DE "Aguardando confirmação do pedido" PARA "Aguardando confirmação" em negrito laranja, liberando espaço para aumentar a coluna "Lojista" 

![image](https://cloud.githubusercontent.com/assets/20990100/18458446/975164ba-7937-11e6-8556-3c52124c3492.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo , meus comentários:

1. Quanto à ordem dos pedidos, é duplicado, isso já foi mencionado na issue #39 
2. Sobre mudança de texto, ok
3. Sobre negrito, ok
4. Quanto a aumentar a largura da coluna lojista, é bug, ok

PS.: vamos evitar tratar de pontos diversos numa mesma issue, fica complicado pra categorizar em alguns casos, veja acima que temos 1 duplicada, 2 melhorias simples que faremos e 1 bug na mesma issue.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo atentar para cache no navegador ao validar

**Comment by lucasretondo** [comment]
![image](https://cloud.githubusercontent.com/assets/20990100/18620039/ea3a292a-7de0-11e6-86c9-8bc65780f401.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo por que esta issue não seria duplicada em relação à issue #39 ?
