### ISSUE TITLE
Orçamento finalizado

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#92]
Ao clicar em "Finalizar e ir para próximo pendente"...
![image](https://cloud.githubusercontent.com/assets/20990100/18458638/f2eadada-7938-11e6-89bb-8e3eb7f78a4e.png)

O usuários é direciona para orçamento já respondido...
![image](https://cloud.githubusercontent.com/assets/20990100/18458644/007dafb0-7939-11e6-83f3-71d3d18fd2f0.png)

Quando existe um orçamento pendente...
![image](https://cloud.githubusercontent.com/assets/20990100/18458647/047781ae-7939-11e6-92fc-7c17f53e2ba7.png)

O melhor é exibir este botão somente quando existirem outros orçamentos pendentes

**Comment by raphaelMCarvalho** [comment]
@lucasretondo mantendo o fluxo especificado, quando não há pendentes, a tela padrão para este caso é exibida
