### ISSUE TITLE
Checkbox no orçamento pendente

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#93]
Por é exibido este botão ao preencher o orçamento? É possível eliminar este check?

![image](https://cloud.githubusercontent.com/assets/20990100/18458697/9bd206f0-7939-11e6-9ab3-44a735e71dfa.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo qual navegador e versão você estava utilizando no momento em que realizou essa operação?

**Comment by lucasretondo** [comment]
@raphaelMCarvalho segue...

![image](https://cloud.githubusercontent.com/assets/20990100/18529431/63058c32-7aa3-11e6-8f24-a7fc7e11fe06.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo testamos em diversos navegadores e esta anomalia não surgiu, inclusive não há checkbox no código desta página em questão. Você ainda está visualizando esse checkbox no Google Chrome? Se sim, nos informe os passos necessários para reproduzir essa anomalia. Caso contrário, pode fechar a issue.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho este problema ocorre quando se passa o mouse sobre um item que esta configurado para exibir a caixa de texto, veja os outros exemplos abaixo.

Ao passar o mouse sobre o campo unidade
![image](https://cloud.githubusercontent.com/assets/20990100/18617537/4afdfa72-7da8-11e6-8726-f6e3ad539109.png)

Ao passar o mouse sobre outras informações
![image](https://cloud.githubusercontent.com/assets/20990100/18617539/54948b1e-7da8-11e6-8351-dd6da4ab7741.png)

Ao passar o mouse sobre o campo marca
![image](https://cloud.githubusercontent.com/assets/20990100/18617542/594e8588-7da8-11e6-87fb-419156f07f71.png)
![image](https://cloud.githubusercontent.com/assets/20990100/18617544/63bb5686-7da8-11e6-9906-452ad132ed14.png)

Digitando com o mouse por cima
![image](https://cloud.githubusercontent.com/assets/20990100/18617546/6b1bd4d2-7da8-11e6-8369-eef9eeda4d62.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo a conclusão a que chegamos é que este é um problema referente ao navegador desatualizado que você estava utilizando pra realizar o teste. Esse checkbox que apareceu para você na verdade é um popover que utilizamos pra exibir o conteúdo quando este não cabe na célula da tabela (quando tem as reticências). O que ocorreu é que o navegador teve problemas ao validar quando exibir esse popover, e exibiu quando não era necessário (como estava sem conteúdo, ficou parecendo um checkbox). Não foi possível reproduzir esse problema em diversos navegadores que utilizamos, utilizei até mesmo o Chrome numa versão pouco posterior que consegui encontrar para download, a 48, e o problema não ocorreu.

O que cabe discutir é se compensa o esforço de tratar esse tipo de problema que afeta uma versão antiga de navegador (46), sendo a versão atual a 53, e considerando que o Chrome realiza atualizações automáticas. Se você passar por este problema após atualizar o navegador, deixe mais detalhes pra gente aqui.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho eu já atualizei o navegador e este popover continua acontecendo. Como não é um item crítico mudei o label para Não será corrigido para discutirmos após a entrega do MPV.

![image](https://cloud.githubusercontent.com/assets/20990100/18975584/8a7f6b2c-8681-11e6-8fc0-186f29963a4d.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18975593/9622d07c-8681-11e6-96eb-b0223763a324.png)
