### ISSUE TITLE
Cálculo do SLA para resposta dos lojistas

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#97]
Fiz uma solicitação de orçamento as 14h36 em 13/set, porém o sistema informou como para as respostas 14/set as 6h quando o correto é 13/set as 16h36.

**Comment by raphaelMCarvalho** [comment]
@lucasretondo favor informar ID do cliente, lojistas e ID do orçamento para verificarmos esse caso específico

**Comment by lucasretondo** [comment]
@raphaelMCarvalho não consegui anexar o print screen quando vi este erro, vou tentar replicar novamente e copio as telas...
