### ISSUE TITLE
Layout Explorer vs. Chrome

### ISSUE THREAD

**Issue by lucasretondo** [PraConstruir/web_app#99]
Os layouts entre os dois navegadores estão diferentes.

![image](https://cloud.githubusercontent.com/assets/20990100/18495918/e713cc2a-79f7-11e6-9ee4-ab725af5895c.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18495922/eb30198a-79f7-11e6-8760-1ef895983c17.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18495929/f9332a4a-79f7-11e6-86e2-1ca562ff33ca.png)

![image](https://cloud.githubusercontent.com/assets/20990100/18495946/0f5780d2-79f8-11e6-8e8d-568ed9a366c8.png)

**Comment by raphaelMCarvalho** [comment]
@lucasretondo favor sempre informar as versões dos navegadores.

**Comment by lucasretondo** [comment]
@raphaelMCarvalho ok, sempre usei as versões já informadas...
